### ISSUE TITLE
Not supporting mobile touch in angular project

### ISSUE THREAD

**Issue by ariesxje** [angular-slider/angularjs-slider#10]
I tried to use this plugin in an angular project.
It is great that it enables slider inside ng-repeat, but it is not working on mobile.
I know that it works on mobile originally, but just not working on my angular project.

Just wonder how to make it work on mobile? Any additional plugin like modernizr?
(I have already included angular-touch and have ngTouch module in my app)

**Comment by netzaffin** [comment]
I'm not sure if closing this issue was the best decision. I can't easily switch angular with jQuery, this will break the application in my case. Any idea how to solve it instead of ignoring it?

[Live Example](https://app.tomvote.com/answer-demo/92d20eeae89c8d31fd199fdfaa60522f)

**Comment by ValentinH** [comment]
The issue was closed a long time ago and the demo website works on mobile. So please open an new issue if you want. Something might be wrong in your project...
