### ISSUE TITLE
Possible to prevent a range slider from crossing over one another?

### ISSUE THREAD

**Issue by DirtyRed578** [angular-slider/angularjs-slider#145]
i have a year range slider and the draggable circles cross over each other making it difficult to select a single year. the user has to carefully adjust the draggable circles to get a specific year. If the circles were not able to cross over each other, then selecting a single year from a year range would be much easier. Is it possible? I will take a gander at your JS and try to customize, if you can point me in any right direction i would be greatly appreciative. EXCELLENT DIRECTIVES BTW!  thank you very much

![range](https://cloud.githubusercontent.com/assets/5614428/10408657/db45da0a-6eb8-11e5-800c-74026e77c5b3.PNG)
![single](https://cloud.githubusercontent.com/assets/5614428/10408658/db476974-6eb8-11e5-99c8-faa02ee37ef9.PNG)

**Comment by ValentinH** [comment]
Indeed, it would be a nice feature. I already started some work but it wasn't complete, see in #112.

**Comment by ValentinH** [comment]
I have just added a `minRange` option to prevent the range to be below a specific value. For you problem if you set `minRange: 1` then the circles won't be able to overlap.
