### ISSUE TITLE
How to make handle slider be read only.I am just want  range drag

### ISSUE THREAD

**Issue by FantasyLions** [angular-slider/angularjs-slider#196]
Hi
 In my project  just need drag range.What should I do?

**Comment by ValentinH** [comment]
If I understand correctly what you want, this is not possibly currently but this would be a good feature. If you can describe a little bit more I could implement it quite soon.

**Comment by FantasyLions** [comment]
I am so sorry my English is so poor.I'm trying to say about it
I want to use this slider in the video clip.The video playback time is 50s I just want clip 10s and the 10s is fixed so just nedd drag the rangebar

**Comment by ValentinH** [comment]
Ok so the slider should be draggable like on this  demo http://jsfiddle.net/5mcr5h7r/, but the user should not be able to directly change the min/max values?

**Comment by FantasyLions** [comment]
yes! Is this meaning

**Comment by ValentinH** [comment]
It's available now using the `draggableRangeOnly` option added in 2.3.0.
