### ISSUE TITLE
Unwanted model rounding on options change

### ISSUE THREAD

**Issue by mattesCZ** [angular-slider/angularjs-slider#207]
I'm trying to switch between two sliders - first is with default precision (0) and step (1), second has `precision: 1` and `step: 0.1`. The default value of model for second slider is `0.4`.
While switching from first slider definition to second, everything updates fine, only the default value of model is rounded with precision of the first slider. For `0.4`, it rounds it to `0`.
I've found out that the watch expression of `rzSliderModel` is evaluated before the new options - `rzSliderOptions` and the function `thrLow` updates the value of model to `0`.

Is there a way to force options to be updated before the slider value?

It can be simply fixed like this:
```javascript
this.scope.$watch('rzSliderModel', function(newValue, oldValue) {
  if (newValue === oldValue)
    return;
  self.applyOptions();  // added applyOptions()
  thrLow();
});
```
But it is probably not the best way. It calls `applyOptions` on every model change.

Any ideas to make it better?

**Comment by ValentinH** [comment]
Indeed this is a bad behaviour. I reproduced your example here: http://jsfiddle.net/fdkgmbq2/ .

I'm taking a look at the best way to fix this.

**Comment by ValentinH** [comment]
I fixed it by simply defining the watch on options before the one on model. Then the order of calls is correct... :D I hope this behaviour won't change later.

**Comment by mattesCZ** [comment]
Great, thanks.
