### ISSUE TITLE
Allow for tooltip on tick hover

### ISSUE THREAD

**Issue by coolblades** [angular-slider/angularjs-slider#209]
Hi,
great job on this slider!
I am using it now. For my case I have date slider and date string is long, so I don't want to show the tick label (many ticks), but like to have hover to show the date when one mouse over a tick.

Is it possible to add this feature?

Thanks!

Jonathan

**Comment by ValentinH** [comment]
Indeed, this is a good idea. Let me check the best way to do it and tell you if its feasible quickly.

**Comment by ValentinH** [comment]
This is done. I just added a `ticksTooltip` that works in the same way than `ticksValuesTooltip`.

**Comment by coolblades** [comment]
wow, that was quick.
I tried the example, and Slider with ticks and tooltips is what I am looking for, but when mouse over a tick, the ticks shifted and you get a brief popup before it disappeared....

**Comment by ValentinH** [comment]
What browser are you using?

**Comment by ValentinH** [comment]
Indeed I could reproduce the issue you mention in Firefox. It works fine in Chrome and Safari...
I'll try to fix it.

**Comment by ValentinH** [comment]
It should be fixed (it is for Firefox at least). I used the `tooltip-append-to-body` option of ui-bootstrap so the tooltip is appended to the body instead to the hovered element.

**Comment by coolblades** [comment]
cool.
yes I was testing with Firefox and IE11, didn't try it on Chrome (I have chrome as well).
I also have IE8 on Windows XP VM :)

**Comment by ValentinH** [comment]
Is it OK with IE11? I don't ask for IE8 because I know it doesn't work. ^^

**Comment by coolblades** [comment]
sorry didn't try, didn't find a link to test your changes. Do you have quick test for me to hit with IE11?
thanks

**Comment by ValentinH** [comment]
The example I mention above should be fixed (http://angular-slider.github.io/angularjs-slider/). I previously forgot to generate the dist files.

**Comment by coolblades** [comment]
excellent! It is working in Firefox and IE11 now.
Thank you so much!

**Comment by gauravlodha** [comment]
Hi there, really great job on this slider!
Its really helping me a lot.

Facing one issue, i am using latest bootstrap (Bootstrap 4)
tool-tip appending withing the body but not showing.

Its working with old bootstrap version but i cant replace it with older version now, my whole UI will be 
distorted if i do that.

can you please help me with Bootstrap 4 version

Thank you.

**Comment by ValentinH** [comment]
Unfortunately, latest bootstrap is not supported. I don't even know how hard it would be to support it since I've never used it.

**Comment by gauravlodha** [comment]
Hey thanks for quick response, can you resolve this issue or give me any alternate solution?

**Comment by ValentinH** [comment]
No I can't. I don't actively maintain this library anymore as I don't use it anymore. I only try to answer to question and fix bugs.
