### ISSUE TITLE
Provide a parameter for the rounding feature

### ISSUE THREAD

**Issue by TikiTDO** [angular-slider/angularjs-slider#210]
Would it be possible to gate this feature: https://github.com/angular-slider/angularjs-slider/blob/master/src/rzslider.js#L638 behind a parameter? 

I have a situation where the slider is used in conjunction with an input field. When a user changes an input field connected to a slider with a sufficiently large step, the rounding function makes it very difficult to enter values.

For example, for a slider with a step of 100,000 it's practically impossible to enter anything without the value getting rounded down to 0.

**Comment by ValentinH** [comment]
OK why not. I'm looking at it right now. Do you want the value displayed on the slider to be rounded or also not to be rounded (when modified from the input)?

**Comment by TikiTDO** [comment]
Actually, sorry. I realized there's a better way of handling this scenario. I just changed my input field to update the angular value on a blur event. Otherwise this will probably become a constant quest to quash all sorts of bugs from this usecase.

**Comment by ValentinH** [comment]
Yes I was also going to tell you that you might use an intermediate value so that the input and the slider are not directly tied.

**Comment by ValentinH** [comment]
Anyway, I pushed a PR so if you really need it, I can merge it. Otherwise, I prefer not to overload the slider with too many specific features.

**Comment by TikiTDO** [comment]
That's probably a good idea. The ceiling and floor made sense from a DRY perspective, since you had to enter that info anyway, but the enforceStep doesn't really make as much sense since you could just not set a step.
