### ISSUE TITLE
Option to disable all events but the pointer drag

### ISSUE THREAD

**Issue by kaspertygesen** [angular-slider/angularjs-slider#212]
I have an application where the sliders take most of the screen space on mobile phones.
When the user wants to slide, its very likely that they will unintentionally click one of the sliders and change the value.

I have removed the events from the elements, selBar, fullBar and ticks which gives me the desired behavior.
I can now scroll without having to carefully place my finger between the sliders.

Can you add an option to disable these events, so that the only way to change the value is to drag the actual pointer?
Or even better, prevent changing the value on vertical drags for horizontal sliders.

**Comment by ValentinH** [comment]
Indeed I understand the issue. I could add a `onlyHandles` option to do what you described. Your "even better" part seems too complicated to me so I will go with the first idea of only responding to pointers event. Is that ok for you?

**Comment by kaspertygesen** [comment]
That would be great :-)

**Comment by ValentinH** [comment]
This has been added to master via the `onlyBindHandles` option.
Demo: http://jsfiddle.net/ValentinH/L60736oj/

I'm doing a release ASAP.
