### ISSUE TITLE
showSelectionBar in opposite direction

### ISSUE THREAD

**Issue by dnlmzw** [angular-slider/angularjs-slider#213]
I need the selection bar to travel: From position of handle -> Max. position, instead of how it is now: From min. position -> position of handle. I couldn't find a way to configure it to make this happen.

Currently:
|=========o----------------|

Need:
|----------------o=========|

**Comment by ValentinH** [comment]
Currently this is not possible. I'm taking a look at it to see if it could be done quickly.

**Comment by ValentinH** [comment]
It was easy. Just need to add the unit test coverage and it's OK on my side. Tell me if this corresponds to what you need.

**Comment by ValentinH** [comment]
Available with 2.4.0 by using the `showSelectionBarEnd` option.

**Comment by dnlmzw** [comment]
Great! Works perfectly. Happy for such fast response.
