### ISSUE TITLE
Problem when slider started.

### ISSUE THREAD

**Issue by ViniciusForcinito** [angular-slider/angularjs-slider#215]
Hi Valentin, first of all tanks for the slider it is very useful.

I use the slider with custon display function, but i have a problem: Whem the slider is started the bar and the max pointer are not in the correct places, After the first click the slider work very well.

Can you help me?

Start:
(https://cloud.githubusercontent.com/assets/16479157/12038537/2a711ff6-ae40-11e5-9f9b-dca67de57a32.jpg)

After first click:
(https://cloud.githubusercontent.com/assets/16479157/12038551/46ff6150-ae40-11e5-8902-6a532ed8238e.jpg)

The slider function:
(https://cloud.githubusercontent.com/assets/16479157/12038559/5550345a-ae40-11e5-819e-4451546a61e0.jpg)

**Comment by ValentinH** [comment]
You are probably facing the following issue: https://github.com/angular-slider/angularjs-slider#my-slider-is-not-rendered-correctly-on-load

**Comment by ViniciusForcinito** [comment]
This is it.

Thanks Valentin.

**Comment by ValentinH** [comment]
You're welcome. ;)
