### ISSUE TITLE
Custom labels for certain values?

### ISSUE THREAD

**Issue by m1rc0** [angular-slider/angularjs-slider#216]
Hi there,

awesome work you did with this directive.

My question is, is it possible to set custom labels for certain values. E.g. I've a slider from 0 to 10 and want to have additional labels at 3 (low), 5 (medium) and 10 (high). Would that be possible?

Thank you very much

**Comment by ValentinH** [comment]
Yeap, you can do it this way: http://jsfiddle.net/f62rdpgo .

**Comment by m1rc0** [comment]
Awesome, thank you very very much!!
