### ISSUE TITLE
Minification

### ISSUE THREAD

**Issue by brucesithole** [angular-slider/angularjs-slider#217]
Firstly, this is a great angular add on. Thanks so much for this! =] Just having issues when I minify the file. Any plans or thoughts on getting a minification safe version?

https://docs.angularjs.org/tutorial/step_05#a-note-on-minification
http://frontendcollisionblog.com/javascript/angularjs/2015/03/31/something-no-one-tells-you-about-minifying-angularjs-controllers-until-its-too-late.html

Two articles that helped me with my app.js file.

**Comment by ValentinH** [comment]
Thanks ;). Why don't you use the minified file from the dist folder?

**Comment by brucesithole** [comment]
The minification is happening automatically as Im using an MVC app and doing script bundling. Anyways,I will try using the minified file so that hopefully the bundling process wont minify it again. Thanks

**Comment by ValentinH** [comment]
Yes it should be OK since most of problems come from the dependencies annotation issue which is already handled by our build process.

**Comment by brucesithole** [comment]
Thanks for the quick responses,just tested it and it works =] Awesome.
