### ISSUE TITLE
onEnd Callback is delay is easily observable.

### ISSUE THREAD

**Issue by hardeepmonty** [angular-slider/angularjs-slider#218]
The onEnd callback when it is called is usually after 1-1.5 sec when I release my drag.
On Mac El Capitan Chrome Version 47.0.2526.106 (64-bit).

Can we reduce this delay to make it instantaneous, or a configuration.

**Comment by ValentinH** [comment]
On this example, do you also see the "last value" updated after 1 sec: http://jsfiddle.net/3ktynd2a/ ?

**Comment by hardeepmonty** [comment]
Im not sure if it is 1 sec, but is definitely not instantaneous the way onChange is called.

**Comment by ValentinH** [comment]
Do you see such a difference on the following example: http://jsfiddle.net/kbfzysco/ ?

**Comment by hardeepmonty** [comment]
Yes, It's the same behaviour, all others are updating without any delay, but the onEnd is taking much longer to get updated.
After I release my drag it is almost a sec when onEnd updates the value.

**Comment by ValentinH** [comment]
OK I'll test it tonight on my mac since I don't have one here...

**Comment by ValentinH** [comment]
Just tested on Mac El Capitan Chrome Version 47.0.2526.106 (64-bit) and I couldn't reproduce your issue. See the screencast below:
![test2](https://cloud.githubusercontent.com/assets/2678610/12101152/7ead8e68-b333-11e5-8998-9c96c42d0cea.gif)

Are you sure you don't have any extension slowing done your browser?

**Comment by hardeepmonty** [comment]
Are you trying three finger drag or click and move to drag the handle ? I just observed the problem is not with click and move but with three finger drag.

**Comment by ValentinH** [comment]
I actually didn't know that three finger drag was working on the slider! ^^ The problem is that when this gesture is used, the mouseup event is fired with a delay...

See here: http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_onmousedown

**Comment by hardeepmonty** [comment]
yeah, I guess we can close this, understanding this is not the problem with angularjs-slider, thanks.

**Comment by ValentinH** [comment]
Indeed, I've tried browsing the web to find someone complaining about this delay but couldn't found anything...
