### ISSUE TITLE
Question: smooth moving of the handle

### ISSUE THREAD

**Issue by vroudge** [angular-slider/angularjs-slider#219]
Hello!

First of all: thank you for this really awesome component. Too bad you're not very well referenced on google, I wish I had found you before. Your component is by far the best I've come across.

I was wondering if there is any way to smooth the slider when you move it left or right, except adding more steps ? Like, you know, interpolation. Just like here: http://www.cubyn.com/invite

I couldn't find it in the doc, but I might be wrong.

Cheers

**Comment by UncleDave** [comment]
A quick way to animate the slider between steps is to add the following to your stylesheet:

```css
rzslider .rz-pointer {
    transition: left 0.15s ease-in-out;
}
```

It's not quite what you're asking for, as the slider still only snaps to steps - but it does make it a bit more shiny.

**Comment by ValentinH** [comment]
Indeed, CSS transition is the way to go: http://jsfiddle.net/yqkn2Lvu/ .

It works well when you click on the bar but if you drag the slider then there is a weird behaviour because there is a delay due to the transition...
