### ISSUE TITLE
Timeout in Slider

### ISSUE THREAD

**Issue by sjaakiejj** [angular-slider/angularjs-slider#220]
I've started playing with this library, and whilst I love most of it I ran into an issue. When the slider is rendered on the page, the sliders start at 0 and then snap into the correct position after half a second or so. Whilst it's not detrimental to the usage of the directive, it doesn't look very pretty. Looking at the source code, I noticed this part:

```javascript
       $timeout(function() {
          self.updateCeilLab();
          self.updateFloorLab();
          self.initHandles();
          self.manageEventsBindings();
        });
```

Removing the timeout solves the issue and doesn't appear to break the slider in any way, so I'm curious as to what the reason is to have it in there.

**Comment by ValentinH** [comment]
Indeed, I just tested it on Chrome on the Timeout is useless.
However, it was probably added for synchronisation purpose so I need to test on several browsers to ensure we are not breaking anything by removing it.

**Comment by elifer5000** [comment]
I found another issue with $timeout, but this time in the function callOnChange. I call a function when the user moves the slider that updates a view. This update takes about 50 ms. If I move the slider back and forth too quickly it sometimes gets stuck, and after a while I get a lot of repeated change events on the last value I selected. If I remove the timeout inside callOnChange it works correctly, and the view is updated smoothly.

I recreated the effect in the following jsfiddle by using a long loop, which in my computer takes about 50 ms to finish. You might need to change it depending on your computer's performance:

https://jsfiddle.net/6j4qntvg/9/

(Tested on Chrome 47, OSX)

I guess the timeout is there to make sure that the slider values are updated before calling the callback, but wouldn't it make more sense (also performance-wise) to ditch the timeout and pass the new values as parameters to the callback? (Even though even after removing the timeout the values seem to be correct)

**Comment by ValentinH** [comment]
Indeed you're right, the timeouts are there to ensure that the model is updated before calling the callbacks. 
In my opinion, it's not handy to pass the model values to the callbacks because you might want to call method from the callbacks that use the model values. Then, you want to be sure that the values used by these kind of methods are the latest ones...

Could you provide another fiddle with your fixes so I can see the behaviour you're mentionning? You can even submit a PR so we can discuss there.
