### ISSUE TITLE
max and min val validation

### ISSUE THREAD

**Issue by jitenderchand** [angular-slider/angularjs-slider#221]
Set slider value from input type text box and restrict user to entered value which is less then min and greater max.

**Comment by ValentinH** [comment]
If I understand correctly what you want, you should try setting the `enforceRange`  option to true.

**Comment by jitenderchand** [comment]
I set enforceRange true but it is not letting user to type value. for example. I have set minValue 10 and maxValue 50 and if you want to type 20 in minValue then it will not allow you to type.

https://jsfiddle.net/954eve2L/34/

**Comment by ValentinH** [comment]
Indeed, enforceRange prevent any value that is not in the range so when you have 10 and you remove the 1 to type 2, then the value becomes 0 and so is not in the range anymore.

For such a use case, I would use intermediate variables to store the text input values and update the sliders value only when input are valid.
