### ISSUE TITLE
New Feature - Add pointer colour to options

### ISSUE THREAD

**Issue by mtucciar** [angular-slider/angularjs-slider#222]
Hey guys!

I've been using this tool and it's really great, so keep up the awesome work! I forked the repo and made a change to add pointer colour to the options. This allows Controllers to update it nicely. I'm not entirely sure how you can see my changes, but they're pretty simple. Hopefully you can absorb this idea/code into your master!

**Comment by ValentinH** [comment]
You can submit a pull request. ;)

**Comment by mtucciar** [comment]
Haha sweet thanks! This will be my first time doing this surprisingly :)

**Comment by BlackIPS** [comment]
Hello everybody,

I've created a feature for the pointer color request and already created a pull request for this. I'd tested it while developing some internal application and it works perfectly so far. 

Please review the new feature at https://github.com/angular-slider/angularjs-slider/pull/253

Best regards,
Steffen

**Comment by ValentinH** [comment]
#253 merged and released under 2.8.0
