### ISSUE TITLE
Only showing a number instead of slider.

### ISSUE THREAD

**Issue by realisation** [angular-slider/angularjs-slider#226]
I've installed with NPM and am doing `require('angularjs-slider') at the top in the file for module declaration where I have `var app = angular.module(fullname, ['ui.router', 'ngResource', 'ngStorage', 'rzModule' ]);` 

In my HTML I have: ` <div> <rzslider
                    rz-slider-model="slider.value"
                    rz-slider-options="slider.options"></rzslider>
        </div>`

And in controller: 

        $scope.slider = {
            value: 150,
            options: {
                floor: 0,
                ceil: 450
            }
        };

But when I run my app, where this should be, I only see $scope.value, 150.

I have a gulp build system. Is that a problem?

**Comment by ValentinH** [comment]
Do you use require on purpose?

**Comment by realisation** [comment]
Sort of - the project I'm on used a generator and that's how the resulting scaffolding imports modules. But that is I think how it should be, at least a little bit, because before I included that, it was saying rzModule can't be found, must be mispelled, or whatever that error is.

**Comment by ValentinH** [comment]
OK and what is the error now?

**Comment by realisation** [comment]
There is no error - it's just showing `slider.value` on the page instead of a slider.

**Comment by ValentinH** [comment]
Did you import the css file correctly?

**Comment by realisation** [comment]
Aha! I wonder how I do that with this gulp build system.

**Comment by ValentinH** [comment]
This is not really related to your build system. You need to import the css in your index.html file...

**Comment by realisation** [comment]
Actually, my build system doesn't even have an index.html.

**Comment by realisation** [comment]
Hehe just pulling your leg

**Comment by ValentinH** [comment]
How did you install the slider library in your project? With bower?

**Comment by realisation** [comment]
NPM

**Comment by ValentinH** [comment]
I just read quickly the yeoman doc but it seems that it requires libraries to be installed with bower. It might then handles automatically the include of files...

**Comment by realisation** [comment]
Thank you :) , I will give that a shot
