### ISSUE TITLE
Outline of pointer when selecting/dragging the slider

### ISSUE THREAD

**Issue by elifer5000** [angular-slider/angularjs-slider#230]
It would look much nicer if, when dragging the slider, you didn't see the outline of the pointer element. 

![image](https://cloud.githubusercontent.com/assets/4311278/12296595/605d819a-ba11-11e5-8bf0-6be1c74a480a.png)

This can be achieved by adding to the css:

```
.rz-pointer:focus {
    outline: none;
}
```

**Comment by ValentinH** [comment]
Actually this was added with the keyboardSupport feature in order to show which slider handle is focused. If you set the `keyboardSupport` option to false, you won't get any outline...

**Comment by elifer5000** [comment]
I see, thanks!
