### ISSUE TITLE
Range slider – minimum range?

### ISSUE THREAD

**Issue by envision** [angular-slider/angularjs-slider#231]
Is it possible to set a minimum range. For example with floor 0, ceil 24, step 1 – is it possible to set minimum range to 1?

**Comment by ValentinH** [comment]
You mean an option to prevent the user from setting a range below 1? If yes, then this is not possible yet but seems to be related to #145 .

**Comment by envision** [comment]
Great, thanks @ValentinH ! I'll waiting for a new subversion release until updating our code.
