### ISSUE TITLE
Avaiable via CDN?

### ISSUE THREAD

**Issue by Gillardo** [angular-slider/angularjs-slider#232]
Is this library available via cdn like https://cdnjs.cloudflare.com?? If not, can it be?

**Comment by ValentinH** [comment]
I have submitted a request to add it to cdnjs ;)

**Comment by ValentinH** [comment]
Well it seems that I have to submit a pull request because they don't add libraries manually anymore... https://github.com/cdnjs/cdnjs

**Comment by lrobert** [comment]
Here's the request link: cdnjs/cdnjs#6743. Just referencing the request here so it's easy to see whenever it gets closed by cdnjs.

**Comment by enric-sinh** [comment]
I have requested it to cdnjs. It is already added.
Here is the PR: [cdnjs/cdnjs#6795](https://github.com/cdnjs/cdnjs/issues/6795).

**Comment by ValentinH** [comment]
No problem, at least it got faster with yours! :D
