### ISSUE TITLE
Changing value externally snaps to nearest step

### ISSUE THREAD

**Issue by Liam-Ryan** [angular-slider/angularjs-slider#236]
This could just be user error so apologies if so.

http://jsfiddle.net/dnjf0hu7/4/ 

I've tried overriding the onEnd function and explicitly setting the enforceRange to false. I think what's happening is that after changing the value externally the onChange event is being called for the slider which has had the value changed externally which in turn is calling the slider that first was changed and so on. 

Is there something I've missed in documentation or another way to achieve what I want? ( Sliding snaps  to steps but sliding one bar can alter the other outside of the set steps )

Thanks

**Comment by ValentinH** [comment]
You should take a look at #210 and the resulting PR: #211 .

**Comment by Liam-Ryan** [comment]
Thanks very much. 

It would be nice for my use-case as I'm re-implementing an existing calculator which currently has this functionality. Logically it can be done using an intermediate value and rounding but it's quite useful to have the immediate visual feedback of the slider with the value displayed above it.

I understand if you don't want to add this feature and thank you very much for an excellent module.

**Comment by ValentinH** [comment]
I'll add it when I get time.

**Comment by Liam-Ryan** [comment]
Thank you, I really appreciate it

**Comment by ValentinH** [comment]
Does the PR above suit your needs? Here is your example using this new option: http://jsfiddle.net/dvs3o1hu/

**Comment by Liam-Ryan** [comment]
Yes that's perfect, thank you

**Comment by ValentinH** [comment]
OK I'll merge it later when the other PR is ready so I can do a single release

**Comment by ValentinH** [comment]
PR merged in master.
