### ISSUE TITLE
Slider value is chaned after programatical modification.

### ISSUE THREAD

**Issue by Filson14** [angular-slider/angularjs-slider#237]
Hi!
I am really confused with this issue. I use slider to present some time frames. Values are in milliseconds since 1970-01-01 and I use translate function to parse this for slider labels.

The problem is that when I set slider.value it changes itself right after that. For example, i choose from datepicker some day, want to set midnight on the slider but slider.value is one hour later. In some cases it adds two days and one hour instead. I tried almost everything to figure it out and debug. Even using $scope.$watch on slider.value and manually delete one hour, I can see in console that the value is subtracted and right after that increased by an hour.

I hope You can figure out the answer or at least a clue. Is there something in angularjs-slider source code that changes that? Maybe I missed sth.

**Comment by ValentinH** [comment]
In order to help you, the best would be to get some code using JSFiddle to reproduce the issue.

At least, can you paste here the slider config you are using?

**Comment by Liam-Ryan** [comment]
I think this is the same behaviour I described in  #236  ?

**Comment by Filson14** [comment]
**Liam-Ryan**, I looked at that issue before, tried to use enforceStep and Range with different configs. I'm affraid it would be hard to create in a minute a jsfiddle which fully presents the problem, i'll try.

My slider config:
vm.slider = {
      value: 0,
      parts: 10,
      options: {
        floor: 0,
        ceil: 604800000,
        translate: function(value) {
          return formatterService.formatDateTime(moment(value, 'x').format());
        },
        //readOnly: true,
        enforceRange: false,
        enforceStep: false,
        draggableRangeOnly: true,
        onEnd: function(id, value, high) {
          setExplorePeriod(moment(value, 'x'), moment(high, 'x'));
          vm.isTimeFrames = true;
        }
      }
    };

I dynamically set step for the slider, and also slider.value and slider.high. The main goal with slider here is to do the presentation.

**Comment by ValentinH** [comment]
Be aware that `enforceStep` is not available currently since it's only in a Pull Request. Moreover, `enforceRange` won't be useful for your case since it's only used to force (or not) the values to be between floor and ceil.

What is the step value you set dynamically? Because if it's different than 1, then @Liam-Ryan is probably right and your issue is linked to his.

**Comment by Filson14** [comment]
I get it. I used `enforceStep` and `enforceRange` just to try if it works with it. The step is the ammount of hours or days (but in milliseconds so yes, it's different than 1). Let's say that slider minimum is monday and maximum is sunday so with the step equals 1 day (in ms) i get 7 ticks etc.

I also thought that [#236](https://github.com/angular-slider/angularjs-slider/issues/236) is quite similar, but still couldn't solve this :/

**Comment by ValentinH** [comment]
OK then: is the value you set coherent with the step setting?

**Comment by Filson14** [comment]
Sure. I forgot to say that slider.options.ceil and slider.options.floor are also set one hour later. JSFiddle in progress.

**Comment by ValentinH** [comment]
Your problem is indeed that your values are not coherent with the step. This is actually due to the UTC offsets. In order to fix this (and if it's OK for your usecase), you should work with UTC date to get and format your dates.

Working fiddle: http://jsfiddle.net/2umvx8dm/

**Comment by Filson14** [comment]
Thanks for your work! I'm not sure if I fully get it why it works like that. In both cases the step is the same.

I need to save date in ISO format to my server so I will use UTC in slider and, while the time frame is changed, I will create new date in ISO format and set all of the parameters (day, hour, minute etc) based on the UTC date. Hope it will work.
Once again, thank you very much for your help!

**Comment by ValentinH** [comment]
The problem with non UTC date was that if you divide the sliders value by the step you obtain floating results which get rounded to be displayed on the slider.

**Comment by Filson14** [comment]
But all the values are in milliseconds so they are integers/doubles without floating parts, aren't they?

**Comment by ValentinH** [comment]
Yeap but in order to be displayed on the slider each value need to be a multiple of the step.

**Comment by ValentinH** [comment]
Actually your issue made me think about the roundStep function that is used internally: it was way too strict since it was not accepting values that were not multiple of the step (as I said above) and this was wrong. Indeed, a slider with a floor=7, ceil=77 and step=5 is valid but was trans form into floor=5 and ceil=75.

Now: http://jsfiddle.net/r0vgzdLa/
Before: http://jsfiddle.net/grwetym8/

**Comment by Filson14** [comment]
Oh ok, I have got the point. I'll update the plugin and make it work.
