### ISSUE TITLE
touchstart, mousedown events absorbed

### ISSUE THREAD

**Issue by ppseprus** [angular-slider/angularjs-slider#238]
I wanted to bind events to the slider, but I was unable to log touchstart or mousedown.
I tried using the onlyBindHandles option too, but could not resolve this issue.
Am I missing something?

    $('#rzSlider').bind('touchstart touchend mousedown mouseup', function(event){
	    console.log(event)
    });

Peter

**Comment by ValentinH** [comment]
Why do you want to bind events and on which element?

**Comment by ppseprus** [comment]
I'm trying to wrapp it as an angular directive and I need to look for tapping.
Did not know how to solve the problem other than binding the above two events.

**Comment by ValentinH** [comment]
It is already a directive. What feature do you want to build?

**Comment by ppseprus** [comment]
I know.
I have to have a handler which appears on tap and has controlls (to adjust by hundredths), however, when dragged, only whole numbers are allowed.
This might not be an "issue".. but I could not figure out why it absorbs these events.

**Comment by ValentinH** [comment]
If you want to display other information than numbers, you simply need to use the translate option.

**Comment by ValentinH** [comment]
About events, in order to have a working slider, `event.stopPropagation();` is called internally.

**Comment by ppseprus** [comment]
You're right. Translate will work. Is there a way to only translate one of the values when the slider used as a range?
Also.. I found the `event.stopPropagation();`, but I could not figure out how to "disable" it without actually changeing your code.

**Comment by ppseprus** [comment]
Sorry for the confusion. For some reason, I misunderstood the translate fn.

**Comment by ValentinH** [comment]
Yes, removing the `stopPropagation` is not a good idea, you will probably break some features.

For the translate, you can write your own logic based on the value passed to this function, so everything is possible ;)

**Comment by ppseprus** [comment]
I mean, only translate `model`or `high`, not both..

**Comment by ppseprus** [comment]
Wait.. I just realised, we went a bit off-track. This still does not solve the tap issue...

**Comment by ValentinH** [comment]
I see... Nope this is not possible since translate is used for every values displayed on the slider: model, high, floor, ceil, ticks.

**Comment by ValentinH** [comment]
I didn't understand what you needed to do on tap.

**Comment by ppseprus** [comment]
Show the handler, which is otherwise hidden. :/

**Comment by ValentinH** [comment]
What do you call "Handler"?

**Comment by ppseprus** [comment]
"I have to have a handler which appears on tap and has controlls to adjust by hundredths"

The problem is that, when `step` is set to .01, a user cannot actually drag things with precision. On a mobile screen a pixel would be approx. .04 of value.
I have to have that precision, so when an `.rz-pointer` is tapped, a handler (my handler) appears with a + and  - sign. By clicking those, you're actually able to change the values by hundredths.

**Comment by ValentinH** [comment]
OK I get it. You can try to use the `onStart` callback from the options.

**Comment by ValentinH** [comment]
Here's a demo: http://jsfiddle.net/t7b5yutp/

**Comment by ppseprus** [comment]
Great! This will work! Thanks for the help! I really really appreciate it! : )
...And I live this slider!

**Comment by ValentinH** [comment]
You're welcome :wink:
