### ISSUE TITLE
Change Label positions

### ISSUE THREAD

**Issue by willianjusten** [angular-slider/angularjs-slider#240]
How can I put labels on the side and stop hiding when get close to the value? You put inline left position with JS on the max label...

Like this:

![screen shot 2016-02-01 at 8 30 49 pm](https://cloud.githubusercontent.com/assets/3991845/12733575/b9ec1c7e-c922-11e5-9619-9739bc1c8bc0.png)

**Comment by ValentinH** [comment]
I would use the `hideLimitLabels` option and display them manually. Then for the current value, you just need css:
http://jsfiddle.net/kfmrpzw3/

**Comment by willianjusten** [comment]
Hey, thanks I did exactly that xD
