### ISSUE TITLE
Show selection bar from 0, when negative

### ISSUE THREAD

**Issue by levipadre** [angular-slider/angularjs-slider#243]
Hi,

Thanks for the directive, it's pretty cool.
I was wondering, that how can I set up the selection bar from zero.
[http://jsfiddle.net/7b15e7wt/](http://jsfiddle.net/7b15e7wt/)

Floor value is -10, ceil value is 10, init value is 0. But unfortunately the line starts from -10 and not 0.

Is that possible somehow?

Thanks

**Comment by ValentinH** [comment]
Currently you can only show the bar from the left (`showSelectionBar`)  or from the right (`showSelectionBarEnd`). 

Just to be sure of what you need, tell me if I get it correctly:
- if model = 5 : -10 ---------------------------------|==========O------------------- 10
- if model = -5: -10 ---------------O=========|--------------------------------------- 10

**Comment by levipadre** [comment]
Yes, this is exactly what I need.

**Comment by ValentinH** [comment]
OK do you think you can try to do it in a PR?

**Comment by levipadre** [comment]
Perfect, it's working like a charm! Thank you so much, it was so quick!
I will watch when you push to master, until then I'm using this branch.

Cheers!

**Comment by ValentinH** [comment]
I just need to add the test coverage so it should be done by the end of the week.

**Comment by levipadre** [comment]
Sounds perfect, thanks!

**Comment by ValentinH** [comment]
PR merged in master.
