### ISSUE TITLE
Slider default value

### ISSUE THREAD

**Issue by Hesesses** [angular-slider/angularjs-slider#244]
https://jsfiddle.net/c8x5xh4c/

When the `$scope.refreshSlider();` is commented out I cant set the default value for slider with ng-init.

Any ideas why this is happening?

**Comment by levipadre** [comment]
Try to put the condition into the model:
```
rz-slider-model="hesevalue == undefined ? hesevalue = 1 : hesevalue = hesevalue"
```

**Comment by Hesesses** [comment]
Seems to work (default value has been set) but when using the slider it gives an error

**Comment by ValentinH** [comment]
Why don't you set the model value in the JS file?

**Comment by Hesesses** [comment]
@ValentinH I have many dynamic templates / form controls, so having the logic inside the template would be easier for me.

**Comment by ValentinH** [comment]
Ok here is a quite dirty workaround:wrap the slider inside a div and do the ng-init on the div: https://jsfiddle.net/koof9g6q/

**Comment by Hesesses** [comment]
:+1: :+1:
