### ISSUE TITLE
Double-Display of Value When Range Is a Single Value

### ISSUE THREAD

**Issue by eriksendc** [angular-slider/angularjs-slider#245]
Hi All,

I have a case where I'm using the slider like this:

`<rzslider rz-slider-model="activityLevelSlider.min" rz-slider-high="activityLevelSlider.max" rz-slider-options="activityLevelSlider.options"></rzslider>`

I set up the slider in my controller like this:

        $scope.activityLevelSlider = {
            min: 1,
            max: 3,
            options: {
                floor: 1,
                ceil: 3,
                translate: function (value) {
                    switch (value) {
                        case 1: return 'low';
                        case 2: return 'average';
                        case 3: return 'high';
                    }
                }
            }
        };

The 2.6.0 behavior was showing "low - low" for example, when both ends of the range were on 1. I dug into rzslider.js and found `updateCmbLabel: function() {...`. In there was a line of code like this:

`this.translateFn(lowTr + ' - ' + highTr, this.cmbLab, false);`

I wrapped that in an if like this:

          if (lowTr === highTr) {
              this.translateFn(lowTr, this.cmbLab, false);
          } else {
              this.translateFn(lowTr + ' - ' + highTr, this.cmbLab, false);
          }

I'm a total newbie at contributing and don't really know how to use git or github yet. I'll try to do some learning about that so I can contribute myself. But I thought I'd post this here in the meantime.

Thanks,
Brian Eriksen

**Comment by ValentinH** [comment]
This is a similar request than #112 but we sort it differently. Since you are the second person who needs it we can add it to master. If you want it ASAP, you can provide a PR or I can do it later.

**Comment by eriksendc** [comment]
Hi Valentin,

Thanks so much for considering my idea. I don't need it ASAP, and I do appreciate the pointer to how to contribute. Again, I'm still quite new at using GIT and running test and all that. If I get time this weekend or next I'll try and learn so I can contribute directly. If you decide to add this functionality yourself let me know.

Thanks again, and thanks for the great slider control!

Regards,
Brian Eriksen

**Comment by envision** [comment]
@ValentinH I just upgraded to 2.12.0 and came up with this issue – it didn't appear with 2.4.0:

With range where min and max values are set to be same as floor and ceil.

Slider loads like this:
![first](https://cloud.githubusercontent.com/assets/1790545/14761899/9dd0c02e-0975-11e6-86cd-1173efa4b6c9.jpg)

...and after clicking the marker once, it suddenly jumps to be like this:
![second](https://cloud.githubusercontent.com/assets/1790545/14761905/aebb2794-0975-11e6-9e12-1e21be4aaadb.jpg)

**Comment by ValentinH** [comment]
Check this: https://github.com/angular-slider/angularjs-slider/blob/master/README.md#my-slider-is-not-rendered-correctly-on-load

**Comment by envision** [comment]
Thanks @ValentinH – I'm using the slider on a modal screen, and adding this to modal's controller this problem was solved (as for my knowledge Angular UI's modal instance doesn't have proper event for hooking into here...?):

```
setTimeout(function() {
	$scope.$broadcast('rzSliderForceRender');
}, 100);
```

**Comment by ValentinH** [comment]
There is a demo with a slider inside a Angular ui modal on the demo site ;)
