### ISSUE TITLE
Feature request: An option to hide values on top of the handles would be nice to have

### ISSUE THREAD

**Issue by oguzgelal** [angular-slider/angularjs-slider#248]

**Comment by ValentinH** [comment]
This was already requested in #99 , but I don't really want to add such a feature since we can do it with CSS:
````
.rz-bubble {
     display: none
}
```

All labels hidden: http://jsfiddle.net/2n4ay3oh/
Only the values ones: http://jsfiddle.net/fax330z1/

**Comment by oguzgelal** [comment]
@ValentinH Yep that was what I did actually, just thought it would be more convenient. Closing this then.

Btw, awesome library. After spending endless hours with `nouislider` and still failing to get it to work properly, this was a lifesaver! Thanks for all the :fish:

**Comment by ValentinH** [comment]
Thanks :smiley:
