### ISSUE TITLE
translate function should add html and not text to label

### ISSUE THREAD

**Issue by MaaikeB** [angular-slider/angularjs-slider#251]
I have a slider with the original value and and below it to the original value I want to show a value that is based on the original value.
So for example: USD 63,000 - EUR 56,000

<img width="301" alt="screen shot 2016-02-04 at 4 45 40 pm" src="https://cloud.githubusercontent.com/assets/5782705/12818287/e3ffdfee-cb5e-11e5-95b6-e263f1ef6307.png">

Whenever the user changes the slider value, I want to return the two values from the translate function, the second value wrapped in a div with a class so I can position it below the original value. 

Yet, since the translate function only adds text and not html to the label, it will display it all as a string, including the <div></div>.

**solution**

at line 617 of rzslider.js, change
`label.text(valStr);`
to 
`label.html(valStr);`

**Comment by ValentinH** [comment]
Great idea! Do you want to submit a PR for this?

**Comment by MaaikeB** [comment]
will do

**Comment by ValentinH** [comment]
Perfect :) You can follow this guide if you need: https://github.com/angular-slider/angularjs-slider/blob/master/CONTRIBUTING.md

**Comment by MaaikeB** [comment]
@ValentinH just updated to the newer version and it works like charm, thanks!
