### ISSUE TITLE
pass to translate function the type value

### ISSUE THREAD

**Issue by MaaikeB** [angular-slider/angularjs-slider#252]
Same scenario as in issue #251.
In the translate function I want to return a different value if it it is the 'slider-value' (user chosen value) than if it is the minimum or maximum values. 
Right now I have no way to differentiate in the translate function which element I am dealing with, since the only argument I get is the value (and the sliderId in case of multiple sliders).
It would be good if the label element can also be passed as an argument to the translate function.

**Comment by ValentinH** [comment]
Yes good idea too. ;)

**Comment by ppseprus** [comment]
I also had this issue, however, `floor` and `ceil` are somewhat constants in my usecases (so I could compare) and the other two values I cached `onStart`, therefore, I was able to differentiate. : )

**Comment by ValentinH** [comment]
@ppseprus Just for your information, the feature discussed in this issue has been implemented and is available with the latest release ;)

**Comment by ppseprus** [comment]
@ValentinH Thanks! :)

**Comment by MaaikeB** [comment]
@ValentinH just updated to the newer version and it works like charm, thanks!

**Comment by ValentinH** [comment]
:smiley:
