### ISSUE TITLE
Template path issue on update to latest version

### ISSUE THREAD

**Issue by nishadk123** [angular-slider/angularjs-slider#254]
I did a bower update all on one of my development projects today.
Angular version is 1.5.0 and angularjs-slider version is 2.8.0. 
After this update i have started getting template path error.
Please find the screenshot attached.
![imgpsh_fullsize](https://cloud.githubusercontent.com/assets/2525644/12891985/1b10d368-ceb0-11e5-9b05-7944eae04a7e.png)

**Comment by ValentinH** [comment]
Are you sure that you are using the dist files and not the src ones?

**Comment by nishadk123** [comment]
Apologies!
It was a mistake from my end that i used files from src and not dist.
Many thanks!
