### ISSUE TITLE
Problem with onChange in ng-repeat

### ISSUE THREAD

**Issue by queejie** [angular-slider/angularjs-slider#255]
The sliders work well in a regular div, but if I place the div within an ng-repeat div, the onChange event is not triggered. I have localized the error, and I do not believe it is related to the $index variable.  If I replace the loop with 5 copies of the tag, referencing the items from 0 to 4, it works fine.

`   <div ng-repeat="choice in choices track by $index">
        <div style="{{'height:' + (choices.length*1.5) + 'em;'}}">
            <rzslider
                    rz-slider-model="alignment[$index].utility"
                    rz-slider-options="{id:qid+'_'+$index,floor:min,ceil:max,vertical:true,showTicksValues:true,onChange:$parent.slideChange}"
            >
            </rzslider>
        </div>
        <div class="clearfix"></div>
        <div class="rubric" ng-bind-html="choices[$index].n|space2Break"></div>
    </div>
`

(I cannot figure out how to get newlines and tabs to be visible in this markup.)

EDIT: Actually, I was wrong about working if I made separate copies.  It appears to be a problem referencing and indexed array of values for the model.

**Comment by ValentinH** [comment]
I need a JSFiddle reproducing the issue to investigate further. ;)

**Comment by ValentinH** [comment]
Closing as no feedback for 2 weeks.

**Comment by Hossam-Hazem** [comment]
having the same problem slider works fine outside ng-repeat, when ng-repeat is applied, slider breaks even when using static values in rz-slider.options

**Comment by pietrofxq** [comment]
Having a similar issue. When I first add an item to the array, the slider value is correct but the slider handle stays at 0%. When another item is added, the handle position for that new item is correct, but the first item always has the handle at 0%.

**Comment by ValentinH** [comment]
It might be related to: https://github.com/angular-slider/angularjs-slider#my-slider-is-not-rendered-correctly-on-load

**Comment by pietrofxq** [comment]
You're right - thanks. I was broadcasting the event when the item was added to the slider, but it has to be called when the slider is visible in the page

**Comment by ValentinH** [comment]
Great! :+1:

**Comment by swil85** [comment]
Hi, 
i have a similar problem,
slider alone work great,
but in ng repeat, the value is not set at end.
https://jsfiddle.net/cmz7Ln84/6/
If you change value on two first slider (repeat), the span show not updated value.
If you change FIRST value of alone slider, everything is updated,
If you change first ONE of repeat slider, then alone slider, only the repeat slider unmodified is affected …
Dont understand !
Hope you can help me.

Thank you in advance.

**Comment by swil85** [comment]
A friend find a solution, by using an object for value.

**Comment by queejie** [comment]
I ended up using ng5-slider, instead.

Sent from my iPhone

On Mar 27, 2019, at 5:27 AM, Sébastien WILHELM <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
i have a similar problem,
slider alone work great,
but in ng repeat, the value is not set at end.
https://jsfiddle.net/cmz7Ln84/6/
If you change value on two first slider (repeat), the span show not updated value.
If you change FIRST value of alone slider, everything is updated,
If you change first ONE of repeat slider, then alone slider, only the repeat slider unmodified is affected …
Dont understand !
Hope you can help me.

Thank you in advance.
