### ISSUE TITLE
Slider doesn't display, just the value as an integer

### ISSUE THREAD

**Issue by darrennoble** [angular-slider/angularjs-slider#256]
When I try putting a slider on a page all that shows up is the default value as an integer.  Here is an example of what I'm seeing:  http://plnkr.co/edit/7s4gm5QVUNDy9AHuhwlc?p=preview

**Comment by ValentinH** [comment]
You forgot to include the CSS file: http://plnkr.co/edit/E7uaZcB7llFYq2GzJrCr?p=preview :wink:

**Comment by darrennoble** [comment]
Thanks, don't I feel stupid... :)

I figured there was probably something dumb like that I was missing.

**Comment by ValentinH** [comment]
No worry, sometimes the most obvious mistakes are the hardest to sort out... ;)
