### ISSUE TITLE
Issues with the alignment of the handle

### ISSUE THREAD

**Issue by angryhawk1** [angular-slider/angularjs-slider#257]
For some reason, the alignment of the handle mismatches the alignment of my ticks. I am using it in an application where the number of ticks change based on the data received and using css to style it won't work for me. At the moment I am doing : 
 $scope.min = $scope.floor = $window.moment('2014-03-04T00:00:00+00:00', dateFormat).valueOf();
 $scope.max = $scope.ceil = $window.moment('2014-05-04T00:00:00+00:00', dateFormat).valueOf();
And, I have set the show ticks to true. 
Please help.

**Comment by ValentinH** [comment]
Please submit a JSFiddle showing the problem.

**Comment by angryhawk1** [comment]
This code doesn't seems to be running at the moment..but we are trying to do something similar
with the help of moment.js
https://jsfiddle.net/954eve2L/124/

By using the translate function, there is a mismatch between the number of ticks and months
![capture](https://cloud.githubusercontent.com/assets/12782416/12933897/06bfd748-cf8b-11e5-802c-6b2c2cbac156.JPG)

The mismatch is mainly due to difference in the days of months and the translation function. 

Steps array can be one good alternate solution but it does not support range at the moment. 

Any hint or suggestion would be appreciated.

**Comment by ValentinH** [comment]
Steps array does support range: http://jsfiddle.net/mLqtvL25 .
You forgot a parenthesis in your fiddle: https://jsfiddle.net/y8bjp7tm .

Indeed, since the number of days in a month is different each month, you can't use a fixed step (which should always match the values of the slider), I would go with stepsArray to do this since it's much easier.

**Comment by angryhawk1** [comment]
Hey thanks for the update on the stepsArray. I used it and it works well but after using it, the values are not translated anymore. 
Please take a look : 
https://jsfiddle.net/y8bjp7tm/14/

**Comment by ValentinH** [comment]
Yea this is because you need to put directly the values you want to be displayed in the array.

**Comment by angryhawk1** [comment]
Can't we send numerical values and later on get it translated for stepArray as we would be needing timestamps for further computation ?

**Comment by ValentinH** [comment]
The slider is a UI component so we provide it with data for display purpose.
However, you can have an array containing the numerical values and map them to the stepsArray option with a display function: https://jsfiddle.net/xuz8ahk6

**Comment by angryhawk1** [comment]
Thanks a lot Valentin, the solution worked for me :+1:

**Comment by ValentinH** [comment]
Great :smile:
