### ISSUE TITLE
Ability to specify steps, but not be fixed to those steps

### ISSUE THREAD

**Issue by lookfirst** [angular-slider/angularjs-slider#259]
I've got a slider of 1-200. 

I'd like to show ticks in steps of 10, but be able to drag to numbers between those steps.

**Comment by ValentinH** [comment]
This is not currently possible but I have already thought about it... I need to find the best way to provide such a feature.

**Comment by lookfirst** [comment]
:+1: @ValentinH

**Comment by ValentinH** [comment]
I have started some work on #264

**Comment by Paul-Todd** [comment]
Love the implementation in #264 exactly what I was looking for!

**Comment by ValentinH** [comment]
#264 merged and available in 2.12.0 release :)

**Comment by lookfirst** [comment]
Thanks @ValentinH 👍 ❤️  :metal:
