### ISSUE TITLE
CSS animations make the slider and tick value go out of sync

### ISSUE THREAD

**Issue by lookfirst** [angular-slider/angularjs-slider#260]
This animation...

```
.rz-pointer {
	-webkit-transition:all linear 0.15s;
	-moz-transition:all linear 0.15s;
	-o-transition:all linear 0.15s;
	transition:all linear 0.15s;
}
```

Create a slider from 1-200 with a step of 1.

If you drag the slider semi-quickly, the tick value above the blue dot doesn't move in sync with the blue dot. It follows it. I'm guessing this would work better if the tick value `<span>` tag lived within the blue dot span and just moved when the blue dot moved. This would also simplify the code a bit cause you wouldn't have to redraw the tick value location in CSS, just have the whole container move together.

**Comment by ValentinH** [comment]
I'm not sure of exactly which config you are talking about so could you provide a JSFiddle showing the issue please?

**Comment by lookfirst** [comment]
Sure, I forked your example in the README and added the CSS above.

http://jsfiddle.net/latchkey/z08wcxrp/1/

Drag the slider around and notice how the tick value follows the dot.

**Comment by ValentinH** [comment]
You should try like this: http://jsfiddle.net/neLz7hkn/

**Comment by lookfirst** [comment]
:+1: thanks man. =)
