### ISSUE TITLE
When only one value is possible, ranged slider should show entire slider as selected

### ISSUE THREAD

**Issue by rabbitfang** [angular-slider/angularjs-slider#261]
If a ranged slider only has one possible value (i.e., `floor === ceil`), the slider should show as entirely selected.

This is what currently happens:
![Current behavior](https://cloud.githubusercontent.com/assets/2784296/13011063/9c11cfdc-d16a-11e5-9b16-314ca2361a78.png)

This is what I would expect to happen:
![Expected behavior](https://cloud.githubusercontent.com/assets/2784296/13011106/ca787dbc-d16a-11e5-82c4-72f19db923f2.png)

I was able to simulate the entire range being selected via the `translate` option.

Demo jsfiddle: https://jsfiddle.net/L2kxuqxf/

**Comment by ValentinH** [comment]
In my opinion, a value should be a single point on the slider. In your proposition, there would be 2 points with the same value and this is not logic.
I won't implement such a feature since the whole architecture is based on this simple idea.

**Comment by rabbitfang** [comment]
This situation can come up (and it is for me) if the slider's range is determined dynamically (e.g. due to what the user has set) and there is only one value. In this situation, the entire slider is representing a single point not two. It might make more sense, visually, if the points are not shown when there is only one possible value.

I don't believe this use case is uncommon or invalid.

**Comment by ValentinH** [comment]
I think that you should hide the slider when there is only one value ad simply display the value.
