### ISSUE TITLE
Question regarding events

### ISSUE THREAD

**Issue by ppseprus** [angular-slider/angularjs-slider#262]
Is it possible to trigger the `onEnd` event on a slider?
Or any other event as a matter of fact..

**Comment by ValentinH** [comment]
The best way is to use the `onEnd` option which is a callback.

**Comment by ppseprus** [comment]
Okay, sorry. So the `onEnd` is a property to which the user can add a function, which will be called "on end". Is there a way, to trigger this on end, so that all the functions that are attached to it, would be called.

I don't think you remember, but I'm the one, who's tring to wrap the slider as another directive.

#238

**Comment by ValentinH** [comment]
I'll try to answer more precisely later but I gotta go so I just answer fast for now: you can attach a function to the intended property so if you want to call all the functions , call them directly.

**Comment by ppseprus** [comment]
Yeah. Your right. But let's assume that I have callbacks directly attached to the slider, and in the application I also event listeners, listening for the `slidEnded` event...

**Comment by ValentinH** [comment]
If you attach callbacks directly to it, then I don't see a way to achieve what you want. Regarding the slideEnd event, I don't really like it and I often think about removing it ^^
