### ISSUE TITLE
Issue with passing in an options object?

### ISSUE THREAD

**Issue by oller** [angular-slider/angularjs-slider#263]
Have searched and couldn't find anything particular around this, I'm passing in an `options` object into the slider via `rz-slider-options="optionsObject"`

When I `{{ echo }}` this object to debug I can see it there in the view with valid values...

```
          options: {
            floor: 0,
            ceil: 1000000,
            step: 1,
            minRange: 10,
            translate: function(value) {
              ctrl.formatThousands(value);
            }
          }
```

However the slider initialises fine, respects the other inline properties set, but doesn't act on the `options` at all.  

The whole embed code is as below:

```
<rzslider 
    rz-slider-on-change="ctrl.onSliderChange()" 
    rz-slider-model="ctrl.slider.min" 
    rz-slider-high="ctrl.slider.max"
    rz-slider-options="ctrl.slider.options">
</rzslider>
```

Could there be anything overwriting these settings?  Cheers!

**Comment by ValentinH** [comment]
First of all, the `rz-slider-on-change` is not a valid attribute, you need to use the onChange option. 

I have try to reproduce your example here: http://jsfiddle.net/f956wm8m/

**Comment by oller** [comment]
Thanks for the quick response @ValentinH.  No question that's definitely working.  Just dug into the bower.json and turns out the version of the slider was rather old!  Bumped to latest and all working!

Thanks again
