### ISSUE TITLE
Use expression binding for rz-slider-options

### ISSUE THREAD

**Issue by rabbitfang** [angular-slider/angularjs-slider#265]
The current code uses two-way binding for the slider options, which can cause infinite digest loops (see https://jsfiddle.net/txupy024/). The slider code never modifies the options value, so the two way binding is not needed.

The fix is a two line change, and I would be able to make the contribution myself.

**Comment by ValentinH** [comment]
I think that it is not a good practice to set a function  that return an object. You should bind to an object directly since it is easier to check for the $digest cycle. With expression binding, can you set callbacks such as onChange or onStart?

**Comment by rabbitfang** [comment]
> I think that it is not a good practice to set a function that return an object.

The function will not necessarily return a new object for every invocation. The function's body could just a single line, perhaps using a parameter to change the return value. For example,

```javascript
$scope.getSliderOptions = function(category) {
  return categoryService.getInfo(category).sliderOptions;
}
```

Permitting expressions also allows usage such as
```html
<div ng-repeat="category in categories">
  <h1>{{category}}</h1>
  <rzslider
    rz-slider-model="values[category]"
    rz-slider-options="options[category] || defaultOptions"></rzslider>
</div>
```

> You should bind to an object directly since it is easier to check for the $digest cycle.

Yes, binding directly to an object would be best, but it is not always the best option.

> With expression binding, can you set callbacks such as onChange or onStart?

Yes. Any time that angular detects a change in the options, the [`applyOptions`](https://github.com/angular-slider/angularjs-slider/blob/5a82c85/src/rzslider.js#L400) function is called, which updates the internal *copy* of the options which includes the `onChange` and `onStart` callbacks. The `rzslider` directive does not store a reference to the options itself anyways, but instead makes a copy so that it can use default options properly.

**Comment by ValentinH** [comment]
Well I'm not sure of how to implement what you are talking about so if you can submit a PR that passes all the unit tests, I could better understand.

**Comment by rabbitfang** [comment]
Could a release be made that includes #266 please? This issue is blocking my project.

**Comment by ValentinH** [comment]
Yes I'll do it when I get the time. If you want to prepare the job, you can submit a PR with the bower/npm version updated, the dist files generated and the Changelog. Thanks to this I'll only need to create a tag and call npm publish.

**Comment by rabbitfang** [comment]
Release PR created in #271
