### ISSUE TITLE
Ceil is equal to NaN after changing the state

### ISSUE THREAD

**Issue by ainouss** [angular-slider/angularjs-slider#267]
The first time the slider works fine, but when I leave the state and come back to it, the slider freezes (ceil not correct it is NaN),
 I tried `$timeout(function () {
    		$scope.$broadcast('rzSliderForceRender');
});`

but it did not solve the problem.

**Comment by ValentinH** [comment]
Could you provide a JSFiddle showing the issue pls?

**Comment by ainouss** [comment]
Okay, I'm not sure if I can reproduce it, because I need angular router to switch between states.

**Comment by ainouss** [comment]
Any idea wow to force ceil to be taken on consideration ?

**Comment by ValentinH** [comment]
![Show me code](http://i.imgur.com/lVtnshJ.jpg)

**Comment by ainouss** [comment]
hahahaha Okay :D

**Comment by ValentinH** [comment]
I'm kind of joking but if you check the previous issue, 99% of the time, once I got the JSFiddle the issue was fastly resolved ;) 

At least, I need to see what html you are using to include the slider and what options you are passing to it   :)

**Comment by dmbjsn** [comment]
Hey @ainouss , I just had the same problem. The solution for me was to move the init of the options object from postLink to preLink. Don't know if this works in your case, but give it a try. **In short, I went from this:**
```
link: function(scope, elem, attr) {
    scope.slider = {};
    scope.slider.options = {
        ceil: someNumber
    }
}
```
**to this:**
```
link:  {
    pre: function(scope, elem, attr) {
        scope.slider = {};
        scope.slider.options = {
            ceil: someNumber
        }
    }
}
```

**Comment by ainouss** [comment]
@ValentinH I laughed hard when I've seen your comment, I really appreciate your efforts :) :)

**Comment by ValentinH** [comment]
:laughing:

**Comment by ainouss** [comment]
@dmbjsn Y'oure right ! it solved my problem :), thank you !

**Comment by dmbjsn** [comment]
@ainouss did the pre-solution work for you?

**Comment by guti1690** [comment]
Other solution to fix this is using the **ngIf **directive with a flag in the rzslider directive:

`<rzslider ng-if="ctrl.slider.isVisible" rz-slider-model="ctrl.slider.value"></rzslider>`
