### ISSUE TITLE
Option "getPointerColor" not in CDN.js version of code

### ISSUE THREAD

**Issue by paulnurkkala** [angular-slider/angularjs-slider#268]
### Steps to reproduce
1. Search CDN.js version of code for "getPointerColor" and the option will not be found
2. Caused some confusion while I was working on this 

### Expected behaviour
Maybe CDN.js needs to be updated, or maybe I just misunderstood something?

https://cdnjs.cloudflare.com/ajax/libs/angularjs-slider/2.5.0/rzslider.js
https://cdnjs.cloudflare.com/ajax/libs/angularjs-slider/2.5.0/rzslider.min.js

**Comment by ValentinH** [comment]
You need to use the latest version which currently is 2.8.0:
- https://cdnjs.cloudflare.com/ajax/libs/angularjs-slider/2.8.0/rzslider.js

The problem is that there is no 'latest' version for CDNJS so I need to remember to update the doc at each new version...
