### ISSUE TITLE
slider value is incorrect when using stepsArray

### ISSUE THREAD

**Issue by tjrosario** [angular-slider/angularjs-slider#269]
### Steps to reproduce
1. Use an array for stepsValue, showTicks: true
2. In the view template render the slider value, ie - {{ slider.value }}
3. Notice the incorrect value as you interact with the slider

### Expected behaviour
Slider value should result in the value of the selected step

### Actual behaviour
Slider value looks to result in the index of the step (ie - 0, 1, 3, 4, etc)

**Comment by ValentinH** [comment]
This is working as design, see the doc: 

> **stepsArray** - Array: If you want to display a slider with non linear/number steps. Just pass an array with each slider value and that's it; the floor, ceil and step settings of the slider will be computed automatically. The rz-slider-model value will be the index of the selected item in the stepsArray.
