### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by Liam-Ryan** [angular-slider/angularjs-slider#270]
Is it possible to switch the direction of the slider by setting a flag for right to left? I haven't been able to find anything in the documentation and switching floor and ceiling seems to work as far as calculating values but the sliders stay stuck at the rightmost extreme of the bar

**Comment by ValentinH** [comment]
Nope this is not currently possible but this could be a cool feature.

For now, you can do a work-around by using the `stepsArray` and `showSelectionBarEnd` like in this example: http://jsfiddle.net/hm9nntmm/

**Comment by Liam-Ryan** [comment]
Thanks I'll see if I can work it in easily at this stage. Would you mind
leaving this open and I'll see if I can put together a pull request in the
near future?

**Comment by ValentinH** [comment]
Yes sure, I'd be glad to provide support for it if needed ;)

**Comment by Liam-Ryan** [comment]
I'm just starting to work on this feature, what approach would you recommend for quick testing and deployment? I notice grunt serve does not run the demo, is there a task that watches files and runs the demo?

**Comment by ValentinH** [comment]
`grunt serve` should serve the demo at `localhost:9000/demo/index.html`.
Then to test your new feature, simply add a block in the demo.html and demo.js.

**Comment by Liam-Ryan** [comment]
Thanks I'm making good progress but the bars and labels are aligned in the incorrect direction when I enable RTL, could you point me towards the logic which controls drawing the bars or even just the variable that is used to refer to the range divider bar rather than the overall slider bar? 

![image](https://cloud.githubusercontent.com/assets/6696533/13199061/6c8c1b60-d812-11e5-99ac-cfc51e5da615.png)

**Comment by Liam-Ryan** [comment]
Hi Valentin, 

I'm almost ready to commit a PR but I've noticed some differences in the code style in places

` if (this.tracking === 'rzSliderModel' && newValue > this.scope.rzSliderHigh) {
                if (this.options.noSwitching && this.scope.rzSliderHigh !== this.minValue) {
                  newValue = this.applyMinRange(this.scope.rzSliderHigh);
                }
                else {`

vs 

`  if (newOffset <= this.dragging.lowLimit) {
              if (this.minH.rzsp === 0)
                return;
              newMinValue = this.minValue;
              newMaxValue = this.minValue + this.dragging.difference;
            } else if (newOffset >= this.maxPos - this.dragging.highLimit) {
              if (this.maxH.rzsp === this.maxPos)`

and 

`   if (newMaxValue > this.maxValue) {
                  newMaxValue = this.maxValue;
                  newMinValue = newMaxValue - difference;
                }
              } else {
                newMaxValue = newValue;
                newMinValue = newValue - differen`

Can you let me know which is the preferred style for if/else blocks? Thanks

**Comment by ValentinH** [comment]
Good news! About the code style, there is an editor config file that can be automatically applied by using the corresponding plugin. Which editor are you using?

**Comment by Liam-Ryan** [comment]
I'm using Webstorm. I was about 60% through the unit tests and noticed some
of the mouse tests failing when using a range in RTL, it's allowing the min
or max to go below or above the floor/ceiling if you drag the entire bar
with a preset range. Do you know where in the code this is handled off the
top of your head?

Also is there a way that I can incrementally update my fork for feedback
without breaking the "use grunt commit" instruction in contributing.MD?

Thanks again

**Comment by ValentinH** [comment]
The part that prevents from going above/below ceil/floor is here: https://github.com/angular-slider/angularjs-slider/blob/master/src/rzslider.js#L1416

About the commit, you should do the first one with `npm run commit`, and then you can do several other ones and just rebase/squash everything when the PR is ready to be merged.
You should already push a commit so I can tell you if you are going in a correct direction. ;)

**Comment by ValentinH** [comment]
About Webstorm, I'm using it too and there is a plugin that handles EditorConfig. Thanks to it, I simply press CMD+ALT+L to reformat everything.

**Comment by ValentinH** [comment]
Feature available in 2.10.X
