### ISSUE TITLE
How to pass ID attribute into model?

### ISSUE THREAD

**Issue by t2developer** [angular-slider/angularjs-slider#275]
<div class="row" ng-repeat="transaction in ctrl.propertyTransactions">
<rzslider rz-slider-model="transaction.salePrice"
                                      rz-slider-options="ctrl.salePrice.options"></rzslider>
</div>

function ScenarioShowCtrl($scope, scenario, PropertyAssetResource, PropertyTransactionResource, ScenarioResource) {
self.salePrice = {
        options: {
            floor: 0,
            ceil: 1000000,
            step: 2000,
            showSelectionBar: true,
            translate: function (value) {
                return '$' + value;
            ,
        }
    };
}
I'm trying to pass the id of transaction into the options, how do I do that? I think the self.salePrice object is singleton for the controller. I tried to run a function and return the options object but that didn't work. Pretty much what I want to do is customize the options and the onEnd function based on the item in ng-repeat

**Comment by ValentinH** [comment]
There is an `id` option that can be relevant for your use case.

**Comment by t2developer** [comment]
I am trying to pass id from the view to the slider object with no success. is the ID you're talking about referring to the ID of the slider object?

**Comment by t2developer** [comment]
I am using ng-repeat so it's having some difficulty with multiple sliders and I need to change up the options but when I do the options from the view, it doesn't allow the onEnd function or any functions from the view, only from the controller

**Comment by ValentinH** [comment]
Are you talking about the ID attribute of a DOM element? If yes, then no there is no way to retrieve it from the options.

**Comment by t2developer** [comment]
yes, so how can you customize for each slider based on a value in the item of a loop?

**Comment by ValentinH** [comment]
If you want a more detailed support, you should provide a JSFiddle reproducing what you want to do.

**Comment by ValentinH** [comment]
Our answers are sent at the same time and I am on mobile so their order in this thread are not what I expected.

You should use the ID option for such a feature.

**Comment by t2developer** [comment]
I had to create multiple objects for each item in my list in order to customize each slider but my colleague and I finally got it to work. Thanks for the quick response!
