### ISSUE TITLE
Ability to set a limit that's different than ceil.

### ISSUE THREAD

**Issue by hworld** [angular-slider/angularjs-slider#278]
This is more of a feature request. I'd like to show a slider where the user can choose a percentage between 0% and 10%. However, I'd like to show the slider up to 100%, but limit them from going past 10%. 

I tried looking through the options, but I couldn't find anything for it. I was kind of able to do something by watching the model value and setting a cap to 10 and force rendering it after, but it's crazy wacky and bugs out visually.

**Comment by ValentinH** [comment]
Currently, this is not possible.

You could do something different by setting a "soft" limit: if the value is above 10, then change the slider color to red with `getSelectionBarColor ()` and/or `getPointerColor()` and reset the value on `onEnd()`.

**Comment by ValentinH** [comment]
Something like this: http://jsfiddle.net/gzbfo8ca/

**Comment by hworld** [comment]
Oh, cool. Not a bad solution at all for something that can be done immediately! Will run with this for now and switch over if the hard limit gets done in future. Cheers!

**Comment by ValentinH** [comment]
OK so for now I keep it open, but won't implement it unless they are more people needing it.

**Comment by bplmp** [comment]
I second this suggestion. In the app I'm building it is important that users know that the maximum for a slider is a certain value, although it could be higher in other cases.

Also in this case it is important for users to compare different sliders with different limits, whereas if I set them using ceiling, both sliders would look the same at maximum, even though they would have different values.

(Here's an image to make this slightly less confusing. The sliders are set at their maximum)
![image](https://cloud.githubusercontent.com/assets/11858154/14319677/0e728356-fbe0-11e5-9035-1b85641dce97.png)

**Comment by ValentinH** [comment]
OK, and what should happen if I drag the first slider above 33%?

**Comment by bplmp** [comment]
I guess it shouldn't go past it – it "hits a wall."

**Comment by ValentinH** [comment]
OK so something like "Range slider with noSwitching=true" in http://angular-slider.github.io/angularjs-slider/

**Comment by bplmp** [comment]
Exactly!

**Comment by codingsolutions** [comment]
I'm also looking for this feature. My use case is to have 3 inter-dependent sliders (say from 0 to 10 floor/ceiling). Moving Slider #1 to 5 will set the max on Sliders 2 and 3 to 5 (but keeping the same ceiling). Then moving Slider #2 to 3 will set the max on Slider 3 to 2.

It's just an example. The sliders aren't really dependent on one another and could be moved in any order. In the controller, I'm dynamically swapping the maximums based on the remaining unallocated amounts.

My workaround is to switch out the ceiling which works but doesn't looks good visually.

**Comment by ValentinH** [comment]
Yes we could add a minLimit and a maxLimit option . If one of you guys are motivated to do it, you can create a Pull request and I would guide you.

**Comment by ValentinH** [comment]
I've started working on it, it will be released soon because I only need to finish the unit tests... ;)

**Comment by ValentinH** [comment]
Implemented in #332. Will be released with 2.14.0

**Comment by codingsolutions** [comment]
Perfect. I tested this against my interactive slider scenario and it's work just as expected.

Here's how I'm doing it now.
`$scope.$on("slideEnded", function() {
	UpdatePoints();
});

UpdatePoints = function() {
    $scope.UnallocatedPoints = AvailablePoints - $scope.SliderOne.value - $scope.SliderTwo.value - $scope.SliderThree.value;
	$scope.$apply(); //force view to update

	$scope.SliderOne.options.maxLimit = $scope.SliderOne.value + $scope.UnallocatedPoints;
	$scope.SliderTwo.options.maxLimit = $scope.SliderTwo.value + $scope.UnallocatedPoints;
	$scope.SliderThree.options.maxLimit = $scope.SliderThree.value + $scope.UnallocatedPoints;
};
`

**Comment by ValentinH** [comment]
BTW you might want to take a look at the onStart, onChange and onEnd options instead of using the scope message...

**Comment by codingsolutions** [comment]
Thanks, I noticed that while digging through the documentation. I'll try switching that over now.

**Comment by ValentinH** [comment]
Yes it offers more flexibility and I might deprecate to use of the message one day..
