### ISSUE TITLE
New Feature Request

### ISSUE THREAD

**Issue by yogavanan** [angular-slider/angularjs-slider#281]
Currently i have user scenario where range is 1 - 1000, even though i give step as 1 it is difficult to minutely adjust the values.

I propose and add a new attribute, which can add - and + icon in the beginning and end of the slider. 
So that minute adjustment is possible.

I can implement it myself by adding icons and updating the ng-model. It would be great if directive itself can support it.

**Comment by ppseprus** [comment]
This might be useful #238 
Also, I think you can simply wrap it as another, new directive. I chose to do that.

**Comment by ValentinH** [comment]
Indeed I would prefer if it's not directly done inside this directive since I think it's already complicated enough.

**Comment by yogavanan** [comment]
Okay.. thanks you can close the ticket of you think so..!
