### ISSUE TITLE
Custom tick numbers

### ISSUE THREAD

**Issue by bplmp** [angular-slider/angularjs-slider#283]
New feature suggestion. Allow for custom number of ticks.

I've created a fork [here](https://github.com/bplmp/angularjs-slider), in which I tried to implement this (in a very crude way).

There's a bug with my fork when used in conjunction with `showSelectionBar: true`. Have a look at the fiddle http://jsfiddle.net/dojr4L0j/

**Comment by ValentinH** [comment]
There is also a bug when used with `showTicksValues: true`. Moreover, the ticks are not drawn on a fix step which seems weird.

I don't really get what would be the use case for such a feature...

Also there is already something similar being implemented here: #264 but there is still quite a lot of work to be done.

**Comment by bplmp** [comment]
Agreed that https://github.com/angular-slider/angularjs-slider/pull/264 covers what I was trying to to. Thanks for pointing this out.
