### ISSUE TITLE
Click Label to Edit Value

### ISSUE THREAD

**Issue by apitts** [angular-slider/angularjs-slider#284]
Any thoughts on adding this an option? Use case is: give users the ability to enter more precise values (that may fall between steps) via clicking and inputting. So, a user may want to drag most of the time but if they require additional precision could click to enter a precise number.

**Comment by ValentinH** [comment]
In my opinion, this is a very specific feature that should be implemented in an external directive that would wrap this slider.

At the moment, I think that this slider directive already implements a lot a different features, maybe too many. I don't want it to become a white elephant.

**Comment by apitts** [comment]
No problem - thanks! :smile:

**Comment by ValentinH** [comment]
Thanks for you understanding. ;)
