### ISSUE TITLE
Ability to change pointer size

### ISSUE THREAD

**Issue by AviEt** [angular-slider/angularjs-slider#285]
I would like to be able to reduce the circle size of the pointer and I could not find in the documentation any way of doing it.

I tried to change stuff in the css:

Changes:
```
rzslider .rz-pointer {
  top: -7px; /* Changed from -14px */
  z-index: 3;
  width: 16px; /* Change from 32px */
  height: 16px; /* Change from 32px */
  cursor: pointer;
  background-color: #0db9f0;
  -webkit-border-radius: 16px;
     -moz-border-radius: 16px;
          border-radius: 16px;
}

rzslider .rz-pointer:after {
  position: absolute;
  top: 4px; /* Change from 12px */ 
  **left: 4px; /* Change from 12px */ 
  width: 8px;
  height: 8px;
  background: #ffffff;
  -webkit-border-radius: 4px;
     -moz-border-radius: 4px;
          border-radius: 4px;
  content: '';
}
```

I also figured there's a need to change the `left` property for the pointer but this should be done in the js so I added 4px:

      setPosition: function(elem, pos) {
        elem.rzsp = pos;
        var css = {};
        css[this.positionProperty] = pos + 4 + 'px'; // Added 4 pixels here
        elem.css(css);
        return pos;
      },

But this doesn't work for the right most value. Is there a more standard way to do it? Or maybe to add such feature?

**Comment by ValentinH** [comment]
Duplicated of #235

**Comment by AviEt** [comment]
Awesome, thanks :+1:
