### ISSUE TITLE
Center align tick values

### ISSUE THREAD

**Issue by lyurko** [angular-slider/angularjs-slider#286]
I have both showTicks and showTickValues turned to true and I have text values passed in for the tick values - ex: "Customer".  I've looked at the demos, and if you add length to the values, they are not centered over the tick they correspond to.

Is there a way to override the position of the tick values so that they are centered over the ticks? Or is there a way to override the position of the tick values so that they have the same positioning as the ticks themselves?  It looks like rz-bubble is getting passed in different values.

**Comment by ValentinH** [comment]
Could you provide a JSFiddle showing the issue please?

**Comment by lyurko** [comment]
@ValentinH - sure - take a look at the simple slider. <script async src="//jsfiddle.net/lyurko/356c8zoy/1/embed/"></script>

What I'm having trouble with is when the tick values get to the left/right of the slider (and become off-center and instead left/right aligned).

**Comment by ValentinH** [comment]
Please show some code/screenshot/gif or whatever, it would be easier to understand.

**Comment by lyurko** [comment]
<img width="510" alt="screen shot 2016-03-02 at 3 17 15 pm" src="https://cloud.githubusercontent.com/assets/775806/13475682/e617a9ac-e089-11e5-967c-7704f23b8bd4.png">

**Comment by lyurko** [comment]
This is my custom slider I'm trying to center the tick values for:
<img width="179" alt="screen shot 2016-03-02 at 3 17 59 pm" src="https://cloud.githubusercontent.com/assets/775806/13475726/139881b2-e08a-11e5-83a6-47897c16711e.png">

**Comment by ValentinH** [comment]
On the image you show, it's working as expected since all the labels should stay within the slider bounds to avoid off parent/screen problems.

In first message, you were talking about ticks/ticks values, what was the problem with them?

**Comment by lyurko** [comment]
Is there a way to break the labels outside of the bounds so that they are centered around the ticks?

**Comment by ValentinH** [comment]
Nope not currently. But are you talking about ticks or pointer labels?

**Comment by lyurko** [comment]
The tick labels

**Comment by lyurko** [comment]
Thanks for your prompt response. If you come up with a way to alter their position so they appear centered please let me know.

**Comment by ValentinH** [comment]
Ticks and pointer labels are not handled in the same way so that's why I wanted to be sure of what you were talking  about. Indeed, your demo and screenshot don't show any ticks.
