### ISSUE TITLE
onChange event not fired when rz-slider-model is changed

### ISSUE THREAD

**Issue by cyrilepinat** [angular-slider/angularjs-slider#288]
### Steps to reproduce
1. update model by changing value in input field
2. check console log : no log is displayed

Demo: http://jsfiddle.net/cyrilepinat/sn8cfsp2/4/

### Expected behaviour
onChange event should be fired when model is changed too, right ?

### Actual behaviour
onChange event is not fired

**Comment by ValentinH** [comment]
onChange is only fired when the value is changed by the slider. You need to used ng-change on the input to watch it.
