### ISSUE TITLE
Removing rectangular box?

### ISSUE THREAD

**Issue by apitts** [angular-slider/angularjs-slider#290]
Any thoughts on how to remove the box around an active slider on clicking it? Please see image below.

![Image](https://cloud.githubusercontent.com/assets/4076720/13721360/de21d294-e878-11e5-9a42-a46c131a74a7.png)

**Comment by apitts** [comment]
Adding this to the CSS under rzslider did the trick for me:
`:focus {outline:none;}`

**Comment by ValentinH** [comment]
The focus state is here for keyboard support, if you turn it off there won't be outlines.

However, if you want keyboard support but no outline, indeed you need to do it with CSS.
