### ISSUE TITLE
Angular-js-slider and animation

### ISSUE THREAD

**Issue by apitts** [angular-slider/angularjs-slider#291]
So, I have a div that is animated via CSS and shows / hides via an angular ng-if. In that div there is an angularjs-slider. Previously (with the old version) all was fine. I've just upgraded to the current version and I'm experiencing something very strange. The animation is not working (div opening delays by the length of the animation) if I have the new angularjs-slider in that div. I have tried reverting to the old version of the slider and it fixes the issue. I have tried changing the ng-if to an ng-show with no luck. Any thoughts on this?

**Comment by apitts** [comment]
Think I figured it out...the new throttle functionality via interval (which is really nice by the way) seems to be interfering. The 350ms delay kicks in the first time the slider is rendered. Now to figure out how to keep the throttle in there but not initially on rendering....maybe a variable that changes after a short timeout....

**Comment by apitts** [comment]
Nope..setting the interval to zero doesn't solve the issue but removing onChange all together does..

**Comment by ValentinH** [comment]
When you talk about the previous version, are you referring to the 1.1 or the 2.9?

**Comment by apitts** [comment]
Actually...0.1.27. Last commit from you @ValentinH was 25-Aug-2015 (05cbdc8) in the version I was using.

**Comment by ValentinH** [comment]
OK, could you set up a demo showing the issue please?

**Comment by apitts** [comment]
Fair question...going to be tough but let me see what I can do.

**Comment by apitts** [comment]
@ValentinH Afraid I'm still trying to work this all out, i.e. get down to the actual issue...right now I'm trying to figure out the interval. It seems like the throttle is applied on init but not on change. Is that correct? Here is a fiddle where I have added a 5000ms interval that I would have thought would cause a delay in onChange firing (after the first time) but I was clearly mistaken:
https://jsfiddle.net/1q0b9j1c/1/

**Comment by apitts** [comment]
Ahh...I see, the interval is not related to the changing values but rather the rendering of the slider.

**Comment by ValentinH** [comment]
Nope the interval is not used internally by the slider, it is only used when the value is modified externally by something else to ensure that we don't re-render the slider too often.

**Comment by ValentinH** [comment]
Actually I had pretty much the same confusion this week and I ended up setting a throttle on the function I attached on the onChange callback.

**Comment by apitts** [comment]
Thanks...yeah, I have that already using the old version but I was looking forward to getting rid of it but will leave it in there now :)

Still trying to work out exactly what is going on with the delay and such...right now my onChange function seems to be getting called whenever an angular digest is run....i.e. other completely unrelated changes are triggering it once the slider is created. If I comment out the $watch on rzSliderOptions() then my issues disappear. I know you need a jsfiddle...will let you know when I have one. At first I thought it was due to the deep equality in that watch but now I don't think so...I do have variables rather than constants for things like ceil and floor....but I don't think that should matter...

**Comment by ValentinH** [comment]
Maybe if you can post the config object of the slider, I could detect something strange.

**Comment by apitts** [comment]
Thanks! So, I don't have an options object as such in my controller as that proved tricky. I have the below where view.maxNodeSize is attached to $scope.view.maxNodeSize (and same for other view values) and resizeNodes is a function on the controller $scope.resizeNodes which calls a function in a service. Issues disappear if I remove onChange or comment out the $watch on rzSliderOptions() in the directive. I know it's tough to make sense of but thanks for giving it a look. 

```html
<rzslider rz-slider-model="view.maxNodeSize" rz-slider-options="{floor: view.lowerBoundaryNodeSize, ceil: view.upperBoundaryNodeSize, hideLimitLabels: true, step: 0.1, precision: 3, onChange: resizeNodes(), hideCloseLabel: true, interval: explore.sliderInterval, noSwitching: true }" class="reducedSliderPadding"></rzslider>`

**Comment by ValentinH** [comment]
OK I see. First, I would advise not to use the options like this but define them in the controller (even if it's possible to do so).

Then, I can see a problem with the way you pass the `resizeNodes` to the `onChange` callback: you call it instead of passing the reference to the function so that's why it's called at each change of your view and on init. 

Here how it should be done: http://jsfiddle.net/gwbw38hw/

**Comment by apitts** [comment]
Thanks @ValentinH! I have made some progress thanks to that. Animations now work again and the onChange function is called as expected. 

Last remaining issue is that I have a trigger elsewhere that calls a function that contains a scope.$evalAsync. When the slider is open this scope.$evalAsync doesn't seem to work...if you have any ideas I would be grateful, otherwise I'll keep going with the debugging in my morning.  Thanks!

**Comment by apitts** [comment]
Mmm...commenting out $watch on rzSliderOptions() fixes this. My onChange function is ~100 lines of js so I'm thinking maybe this $watch across all the options could be really expensive for me and I should change it to just watch ceil and floor...which I need. Not sure if it's possible to only watch specific options the way it's set up though.

**Comment by ValentinH** [comment]
The content of every callback attached to the options isn't watched so I doubt that this is the source of your problems.

**Comment by apitts** [comment]
Going to close this issue now...not going to proceed with the upgrade for the moment but may come back  to try and solve the performance issues another time.

**Comment by artaommahe** [comment]
Have same issue with my own modals animation and rzslider inside this modal. Tried versions 2.10.0 and 5.4.0.
I dynamically create modal window as body child that contains rzslider in child component. Modal animation css
```scss
.modal
  &.ng-enter
    transition-duration: $modal-transition-duration
    .modal-dialog
      transition: all $modal-transition-duration ease
      transform: scale(0.5, 0.5)
      opacity: 0

  &.ng-enter-active
    .modal-dialog
      transform: scale(1, 1)
      opacity: 1

  &.ng-leave
    transition-duration: $modal-transition-duration
    .modal-dialog
      transition: all $modal-transition-duration ease
      transform: scale(1, 1)
      opacity: 1

  &.ng-leave-active
    .modal-dialog
      transform: scale(0.5, 0.5)
      opacity: 0
```
Cant repoduce this with ui-bootstrap modal animation at jsfiddle.

I realized that wrapping this calls in rzslider init() method with setTimeout() solves my problem
```js
setTimeout(function() {
  this.calcViewDimensions();
  this.updateCeilLab();
  this.updateFloorLab();
  this.initHandles();
}.bind(this));
```

**Comment by ValentinH** [comment]
What would be really great is that you provide a demo so that I can try to give a solution.

You issue is probably because when the slider is instantiated, we compute the size of its parent which is modified by the scale transform. When the slider is in a div with a fix scale (different than one), you can tell it by setting the scale option. However, in your case, the scale is animated so it's not relevant.

You can at least fix the rendering at the end of the animation  by broadcasting the  `'reCalcViewDimensions'` event on your scope.
