### ISSUE TITLE
dragging slider does not honor floor

### ISSUE THREAD

**Issue by carueda** [angular-slider/angularjs-slider#293]
### Steps to reproduce
1. set a range slider, `low`==2000 and `high`==2500 in the demo below 
2. set a `floor` < `low` (`floor`==1000 in the demo)
3. at this point the widget looks like this
![image](https://cloud.githubusercontent.com/assets/556505/13802317/dbfff564-eaf7-11e5-9007-9fd56cf50b24.png)
4. use mouse to drag the slider back to the origin, that is, where `low` should get the value of `floor`

Demo: http://jsfiddle.net/carueda/cwhgLcjv/55/

### Expected behaviour
- `low` consistently gets the expected `floor` value (1000) whenever I drag the slider all the way to the left

### Actual behaviour
- `low` gets zero   (not always at the first try, but it takes no more than a couple of tries dragging to the left to get zero)
![image](https://cloud.githubusercontent.com/assets/556505/13802353/15bfdc38-eaf8-11e5-9e02-87e74b9598e5.png)
    BTW, `high` gets the expected 1500 value in this case

- additionally, a subsequent small drag to the right (or simply a click down) has the effect of adding `floor` (1000) to `high` 
![image](https://cloud.githubusercontent.com/assets/556505/13802382/5d3a1326-eaf8-11e5-853d-e834b7c5a90b.png)
    In this example, with a a small drag of 16, while `low` seems to get back to a reasonable value (1000 + 16), `high` becomes 2516 instead of 1516.

Hope the issue description is clear enough.  Thanks for the great tool btw.

**Comment by ValentinH** [comment]
Well spotted. I can see that this bug appeared with the 2.10 release. While I'm fixing it, you might want to use the 2.9.0 one. ;)

**Comment by ValentinH** [comment]
Fix released in 2.10.4 ;)

**Comment by carueda** [comment]
Thanks!!
