### ISSUE TITLE
rzslider.min.css SyntaxError

### ISSUE THREAD

**Issue by lbpierre** [angular-slider/angularjs-slider#294]
Hi,
It looks like there is an error in rzslider.min.css of the lastest release. When I use this link:
`https://rawgit.com/rzajac/angularjs-slider/master/dist/rzslider.min.css"`

I get this result:

> SyntaxError: missing ; before statement

**Comment by ValentinH** [comment]
Could you provide a demo that reproduces the error please?

Here I have tried to use the css file you mentionned, but I don't see any error: http://jsfiddle.net/mqn4f82a.

What browser are you using?
