### ISSUE TITLE
How to show the range of dates on this slider?

### ISSUE THREAD

**Issue by webservconsultant** [angular-slider/angularjs-slider#297]
### Steps to reproduce
1. How to show the dates as ranges on the slider
2. How to display date format label
3. 

Demo: http://jsfiddle.net/webservconsultant/u5gsjqtp/55/
### Expected behaviour
Should display dates as labels
Range should be dates (between 2 dates)

### Actual behaviour
Nothing happens.

**Comment by ValentinH** [comment]
Did you modify the fiddle since the creation of the issue? I don't see any problem on your example...

**Comment by webservconsultant** [comment]
Yes, I did, But slight problem though. I would like the labels to display like 'Aug. 13th 2011' (something of different format). Doesn't look like it is recognizing my translate method.

**Comment by ValentinH** [comment]
Well, this is because `stepsArray` is a helper method that enables you to directly provide the values you want to be displayed.

You should use `translate` directly, and the correct model, high, floor, ceil and step options.

**Comment by webservconsultant** [comment]
would you mind putting some quick sample for the dates please-thanks

**Comment by ValentinH** [comment]
You have this http://jsfiddle.net/2umvx8dm/ from #237

**Comment by webservconsultant** [comment]
awesome - thanks for the link
