### ISSUE TITLE
Precision period being cut off.

### ISSUE THREAD

**Issue by sgarbesi** [angular-slider/angularjs-slider#298]
### Steps to reproduce
1. Try to append to `.99` to the text input.
2. You'll see it immediately gets cut off so that the user cannot enter say `0.99` without having to try multiple times and get **lucky**.

Demo: http://jsfiddle.net/5g7ungrx/2/

### Expected behavior
The input field should allow for a '.' without truncating it automatically.

### Actual behavior
The `.` is being truncated.

**Comment by ValentinH** [comment]
Indeed, this is not really expected.

You can set the `enforceStep` option to false as a workaround: http://jsfiddle.net/pwsh5jh3/

**Comment by sgarbesi** [comment]
@ValentinH PS the canned instructions for opening a new issue spelled `behavior` incorrectly. Figured it was worth mentioning.

**Comment by ValentinH** [comment]
It just a difference of spelling between US and UK! :laughing:

**Comment by ValentinH** [comment]
I have added a block about this issue in the ReadMe: https://github.com/angular-slider/angularjs-slider#decimal-value-cant-be-typed-in-an-input-field-linked-to-the-slider.
