### ISSUE TITLE
Sluggishness on Firefox

### ISSUE THREAD

**Issue by BenWoodford** [angular-slider/angularjs-slider#301]
I'd fill in the template but I'm not entirely sure how I'd reproduce this. Been working on a site for a client (http://csgodiamonds.com if you have a Steam account and want to see the laggy slider in action) and no matter how much I try I cannot get the slider to not feel very sluggish in Firefox.

I've tried outright removing the onChange event to see if it was related, and while it sped it up slightly, it was nowhere near enough. A lot of the time spent seems to be on recalculation of styles and updating the DOM to move the handle which in turn recalculates styles.

Quick shot below of the profiling in Firefox 43.0.4, just from me sliding it back and forth a bit. As you can see lots of purple (recalculating styles) and most of the orange is down to moving the handle and other setTimeout/DOM Events relating to that.

![image](https://cloud.githubusercontent.com/assets/503263/14017570/44ead0f2-f1c0-11e5-8712-722342c72917.png)

I don't know if this is some obscure bug in the library or my fault, but either way I'd love a pointer on how I can resolve it.

**Comment by ValentinH** [comment]
I know that they are a lot of style recalculations and that this is not really cool but I had never noticed a really different behavior in Firefox compared to other browsers.

I should try to focus on optimisations like using `transform` properties instead of `left/top`...

Could you paste your slider config so I can tell you if I see something weird?

**Comment by BenWoodford** [comment]
````
	this.slider_opts = {
		chance: {
			hideLimitLabels: true,
			floor: 0.01,
			ceil: sliderCeil,
			step: 0.25,
			showSelectionBar: true,
			precision: 2,
			onChange: ctrlr.onSliderChange,
		},
		speed: {
			hideLimitLabels: true,
			floor: 0,
			ceil: 100,
			step: 1,
			showSelectionBar: true,
		}
	}
````

Both are slow, but the first one especially.

**Comment by ValentinH** [comment]
Sorry for the delay, I forgot about this thread. Your options don't seem weird so I can't really give you more feedback. Generally, the slider is not directly responsible for lags but can feel laggy if another part of the code is slow.

**Comment by ValentinH** [comment]
Closing it as no update for more than a month.
