### ISSUE TITLE
Setting a dynamic floor and ceil.

### ISSUE THREAD

**Issue by JEpifanio90** [angular-slider/angularjs-slider#302]
I'm trying to set the slider limits after a api call 
and when I set the values the slider stops working 
and on console shows this 

(this.minValue + b).toFixed is not a function angularjs

This is my slider variable with the options

vm.slider={
			minValue: 400,
			maxValue: 600,
			options: {
				floor: 100,
				ceil: 1000,
				step: 1,
				translate: function(value, sliderId, label){
					switch (label) {
						case 'model':
							return '<b>Min:</b> $' + value;
						case 'high':
							return '<b>Max:</b> $' + value;
						default:
						return '$' + value
					}
				}
			}
		};

And this is how I'm setting them after the api call
vm.slider.options.floor=response.min;
vm.slider.options.ceil=response.max;

**Comment by ValentinH** [comment]
What is the content of response.min and max?

**Comment by JEpifanio90** [comment]
Thanks for answering so fast. :+1: 

Both are integers

**Comment by JEpifanio90** [comment]
¡ValentinH, don't worry! I've al ready fixed the issue :+1:

**Comment by ValentinH** [comment]
Great! What was the issue?

**Comment by JEpifanio90** [comment]
I was pretty sure that the values were numbers when in fact were strings and I had to parse them; sorry for that :sweat_smile:

**Comment by phuyem** [comment]
But it seems **toFixed() function** does actually not exist  !!??

  I am having this issue, I guess maybe string-int stuff .. thanks guys
