### ISSUE TITLE
rzModelValue does not accept non-numerics

### ISSUE THREAD

**Issue by iysrini** [angular-slider/angularjs-slider#304]
### Steps to reproduce
1. open demo site and look at simple slider demo
2. clear input field
3. model is automatically updated to 0
4. enter '.'

Demo: http://angular-slider.github.io/angularjs-slider/index.html

### Expected behaviour
empty string, null, undefined should be valid values. this is valid case as input field should start in blank state. 

user should be able to key in decimal. when valid float is detected, model should be updated.

### Actual behaviour
1. empty inputs are converted to 0 in setMinMax function
2. '.' characters are stripped and input is entered..

**Comment by ValentinH** [comment]
I disagree, null is not an acceptable value for a slider since there is a specified min and Max.

**Comment by iysrini** [comment]
I understand your point, however in cases when 0 does not fall within min/max range, this gives false impression of where slider lands. for example min = -10 and max = -1. In this case I forsee 2 possible solution when users clears text input value. we set slider model to undefined which will default position to min. The other idea to is default to mid point of min & max. This supports your point of ensuring model has numeric value.

What are your thoughts on second issue regarding '.' character?

**Comment by ValentinH** [comment]
Actually, for your 2 problems, you can set  ̀enforceStep: false`.
http://jsfiddle.net/pwsh5jh3/

**Comment by tjrosario** [comment]
@iysrini using the same fiddle, if using `stepsArray`, the slider model value outputs the index of the stepArray instead of the value.

**Comment by ValentinH** [comment]
Nope: http://jsfiddle.net/fem7xoka/

**Comment by ValentinH** [comment]
I have added a block about this issue in the ReadMe: https://github.com/angular-slider/angularjs-slider#decimal-value-cant-be-typed-in-an-input-field-linked-to-the-slider.
