### ISSUE TITLE
Long labels wrongly positioned for vertical sliders

### ISSUE THREAD

**Issue by ValentinH** [angular-slider/angularjs-slider#305]
### Steps to reproduce
1. Use quite long labels
2. Set orientation to vertical

Demo: http://jsfiddle.net/nqnwt57n/

### Expected behaviour
Labels should be correctly positioned at the left of the slider

### Actual behaviour
Labels starts from the right and are over the slider

### Fix
Use left position value instead of right.

**Comment by dbartholomae** [comment]
Just created a PR for this: #306
