### ISSUE TITLE
Wider pointer not placed precisely above all tics

### ISSUE THREAD

**Issue by jacolaisen** [angular-slider/angularjs-slider#309]
### Steps to reproduce
1. Restyle pointer with higher width than default
2. Observe pointer is correctly placed in the middle of the bar
2. Drag pointer towards floor or ceil
3. Pointer is not placed precisely above tics
Demo: http://jsfiddle.net/jacolaisen/n7zw9j7f/1/

### Expected behaviour
The middle of pointer should placed directly above tic

### Actual behaviour
Towards ceil: The middle of pointer is to the left of tic
Towards floor: The middle of pointer is to the right of tic

**Comment by ValentinH** [comment]
You need to update the .rz-ticks padding which is originally defined [here](https://github.com/angular-slider/angularjs-slider/blob/master/src/rzslider.less#L126).

Demo: http://jsfiddle.net/xx8neL89/

**Comment by jacolaisen** [comment]
Thanks!
