### ISSUE TITLE
Possible issue

### ISSUE THREAD

**Issue by ppseprus** [angular-slider/angularjs-slider#310]
### Steps to reproduce
1. Manually update the width of the `rzslider`

Demo: http://jsfiddle.net/eybb6nu7/

### Expected behaviour
I'd expect everything to be immediately recalculated.

### Actual behaviour
Only parts of the html is recalculated, however, the first time I touch the slider, it reacts to the new width.

### Possible wrong usage(?)
It is possible, however, that I'm using it the wrong way.
I have two other DOM elements, that have fixed widts and the slider should fill up the rest of the space.

**Comment by ValentinH** [comment]
Indeed, you need to force the slider to recompute its size: 
```js
$scope.$broadcast('reCalcViewDimensions');
```

Demo: http://jsfiddle.net/3bnaaq7t/

**Comment by ppseprus** [comment]
You're right! Sorry! My mistake! : )
