### ISSUE TITLE
Show tooltip while dragging handle

### ISSUE THREAD

**Issue by keithpickering** [angular-slider/angularjs-slider#312]
The plugin currently offers "tick" tooltips, but I need pretty much the opposite: can I display a zoomed tooltip above the handle that is currently being dragged?

**Comment by ValentinH** [comment]
Nope there is no way to do that currently.

**Comment by keithpickering** [comment]
How can I access the currently-active handle object during the `onChange` event?

**Comment by keithpickering** [comment]
Hi, could you answer my last question if you get the chance?

**Comment by keithpickering** [comment]
In case anyone in the future wants to get this working:

1. In your css, create a definition for `.rz-bubble-zoom`. This will be the class applied to the text labels when a corresponding handle is being dragged. For starters, try `transform:scale(2)`.

2. In the `updateCmbLabel` function in `rzslider.js`, add this after line 1070:
    `this.cmbLab.addClass('rz-bubble-zoom');`
And this after line 1076:
    if (this.tracking == 'rzSliderModel') {
            this.minLab.addClass('rz-bubble-zoom');
            this.maxLab.removeClass('rz-bubble-zoom');
          } else if (this.tracking == 'rzSliderHigh') {
            this.maxLab.addClass('rz-bubble-zoom');
            this.minLab.removeClass('rz-bubble-zoom');
          }

3. Add the following to the `onEnd` and `onStart` functions to reset the class when necessary:
    this.minLab.removeClass('rz-bubble-zoom');
    this.maxLab.removeClass('rz-bubble-zoom');
    this.cmbLab.removeClass('rz-bubble-zoom');
