### ISSUE TITLE
IE8 Support

### ISSUE THREAD

**Issue by tomchiverton** [angular-slider/angularjs-slider#313]
### Steps to reproduce
1. open http://angular-slider.github.io/angularjs-slider/index.html in IE8

### Expected behaviour
Works

### Actual behaviour
Fails to fill in the template values or draw slider.
Logs "Node is undefined" in angular.min.js line 183

**Comment by tomchiverton** [comment]
Under older Angular's (v1.2) IE8 logs "Error: Unexpected call to method or property access" and does not draw the control, though the rest of the page is OK.

**Comment by tomchiverton** [comment]
This appears to be because the directive requires 'replace:true', but this upsets the template (which needs wrapping in a div) which then means updating the CSS (replace the rzslider element with a class set on the template's DIV node.
FireFox at least is happy after those changes, but IE still now just dies silently and doesn't draw anything.

**Comment by ValentinH** [comment]
I don't understand what you say, currently the directive doesn't use `replace: true`.

**Comment by tomchiverton** [comment]
@ValentinH I thought it needed it. It doesn't. Incoming pull request.
