### ISSUE TITLE
Ability to use `data-` tags.

### ISSUE THREAD

**Issue by sgarbesi** [angular-slider/angularjs-slider#315]
### Steps to reproduce
```html
<div data-rz-slider-options="xyz">
```

### Expected behaviour
Should work. Useful for legacy browsers.

### Actual behaviour
Doesn't work.

**Comment by ValentinH** [comment]
How can it work? Is there a special Angular option for.it?

**Comment by sgarbesi** [comment]
@ValentinH I believe it's built in natively to Angular but for some reason it doesn't seem to work for me with the library?

**Comment by sgarbesi** [comment]
@ValentinH Looks like the directive is restricting to an element only.

https://github.com/angular-slider/angularjs-slider/blob/master/src/rzslider.js#L1827

Switching the value to 'AE' I think should do it.

https://docs.angularjs.org/guide/directive

**Comment by ValentinH** [comment]
Ah ok, I thought you were only talking about options attributes. There is already a PR about this, you might want to take a look at it ;)

**Comment by ValentinH** [comment]
This is now possible thanks to #314
