### ISSUE TITLE
Hiding the label on top of the slider ball

### ISSUE THREAD

**Issue by RishuK** [angular-slider/angularjs-slider#317]
Are there any options available to hide the number that keeping on changing as the slider moves forward - the number label on top of the slider ball or the bubble that is?

I tried using rz-bubble class to set css - opacity: 0, but that does not seem to work.

**Comment by ValentinH** [comment]
Yes: `hidePointerLabels: true`

**Comment by RishuK** [comment]
I tried that but my slider stopped moving at all. And the bubble label kept on changing with the slider staying at position 0

**Comment by ValentinH** [comment]
Does this demo work for you: http://jsfiddle.net/e75n4jf7/ ?

**Comment by RishuK** [comment]
Yes, it does. 

These are my options - $scope.slider = {
        options: {
          floor: 0,
          ceil: null,
          hideLimitLabels: false,
          hidePointerLabels: true
        }
      };

**Comment by RishuK** [comment]
Its weird it does not work in my set up

**Comment by ValentinH** [comment]
What version are you using?

**Comment by RishuK** [comment]
2.1.0

**Comment by RishuK** [comment]
I guess I should be using 2.11.0?

**Comment by ValentinH** [comment]
Yes indeed :)

**Comment by RishuK** [comment]
Thanks!!

**Comment by ValentinH** [comment]
everything's fixed?

**Comment by RishuK** [comment]
Yes!

**Comment by nomanbiniqbal** [comment]
can we have hideLimitLabels for cell and floor saparatly
