### ISSUE TITLE
slideEnded Event not sent when using arrow keys

### ISSUE THREAD

**Issue by goldenram** [angular-slider/angularjs-slider#319]
When you click and drag the slider with the mouse, at the end, when you release the slider, you get a slideEnded event.  However when adjusting the slider with the arrow keys, no event is sent.  I would expect on keyUp, like on mouseup, a slideEnded event would be sent.  For each key click there would be an event or if the user held down an arrow key, then when they release the key, a single event is sent.

**Comment by ValentinH** [comment]
Indeed, it should be added with `onEnd` as well.

**Comment by cniemann88** [comment]
+1
