### ISSUE TITLE
stepsArray question

### ISSUE THREAD

**Issue by Mencls** [angular-slider/angularjs-slider#320]
Hi, I'm trying to use stepsArray as I don't want linear steps but I was surprised to see that the slider-model will be the index of the array, and not the value.

So if I have [1, 2, 3, 50, 100], model's value will be [0, 1, 2, 3, 4] right?

But if I want the model to be equal to those steps, how could I do that?

Eg, if I move the cursor to 50, I want the model value to be 50 and not 3.

**Comment by ValentinH** [comment]
There is no way for the model to equal the actual value because it's used internally to compute everything.

However, you simply need to write  function that make the translation between the slider value and the value in the array. Basically just take the Nth element of the array.

**Comment by Mencls** [comment]
Hi, yes of course but I just wanted to make sure there wasn't a native solution :)
Thanks!

**Comment by Mencls** [comment]
Hmmm I think there is an issue with stepsArray. I got "undefined" as a ceil value per default, and then when I move the cursor, the correct value appears.

`$scope.sliderOptions = {
    	stepsArray: [10, 20, 50, 100]
    };`

![screen shot 2016-05-02 at 5 04 18 pm](https://cloud.githubusercontent.com/assets/690350/14948851/088d6fa2-1088-11e6-90b1-2fec00bb5a2d.png)

![screen shot 2016-05-02 at 5 06 36 pm](https://cloud.githubusercontent.com/assets/690350/14948874/4388f090-1088-11e6-8e7f-7cd0b1a81b02.png)

PS: I'm using the slider in a directive, and I feel like there are some weird behaviours sometimes. Like I can't set the options object in the directive's link function. I have to set it up in the controller and pass it as a parameter in my directive. Otherwise it doesn't work.

**Comment by ValentinH** [comment]
I'm pretty sure this is link to the first common issue read in the read me, especially if used inside directive.  You might want to try the solution listed there.
