### ISSUE TITLE
Tooltip is displaced

### ISSUE THREAD

**Issue by timolemow** [angular-slider/angularjs-slider#321]
First of all, thanks for this great directive! I really like it.

Now here's my problem: I have a couple of sliders that should show a different tooltip for the min and max values. I created a function that returns an initialization object for the sliders. I have two issues:

1.) The tooltip on the max value is displaced to the left. It will show when the cursor is a little but under the value and when I move the tooltip sometimes is displayed correctly on top of it but most of the time it is left to it. Here's a gif to illustrate the problem:
![tooltip_displaced](http://g.recordit.co/THAzixUDnq.gif)

2.) Every slider should get a different tooltip text. I create the slider options with this function:

```
createSliderObject(sliderName) {
    return {
      options: {
        floor: 1,
        ceil: 5,
        stepsArray: '1   5'.split(''),
        showTicksValues: true,
        ticksValuesTooltip: (val) => {
          if (val === 0) return this.sliderLabels[sliderName];
          else if (val === 4) return this.sliderLabels[sliderName];
        }
      },
      value: 2
    } 
  }
```
`sliderLabels` is an array that contains different tooltips for every slider.
...and create the sliders here:
```
this.sliderNames = [
  'slider1',
  'slider2'
  ...
]
for (let f of this.sliderNames) {
      this.sliders[f] = this.createSliderObject(f);
}
```

But every slider somehow has the same tooltip text for the max value. Any hint in the right direction greatly appreciated!

**Comment by ValentinH** [comment]
First of all, you are not using the stepsArray option correctly, in your example you don't really seem to need it, just set floor=1, ceil=5 and step=1. Then for the wrong position of the tooltip, this is weird, I would need a demo to see what's going on.

**Comment by timolemow** [comment]
The thing is, I just want to display the first and the last value. I don't want 1,2,3,4,5 to be displayed, just 1 and 5 and have a different tooltip for both. I couldn't figure out a way to do it with the given options.

**Comment by ValentinH** [comment]
OK so put stepsArray: ['1', '','','','5']

**Comment by timolemow** [comment]
Could you please take a look at this? http://jsfiddle.net/ko9vk9jL/6/

**Comment by ValentinH** [comment]
I am sorry but I am on holiday for 10 days and I'm only on mobile phone so I cant debug anything.

**Comment by ValentinH** [comment]
You forgot to load angular-bootstrap... Here's a working version: http://jsfiddle.net/3ts4w58y/
