### ISSUE TITLE
maxRange option?

### ISSUE THREAD

**Issue by envision** [angular-slider/angularjs-slider#322]
It seems you have not implemented maxRange option...is there a way to achieve this by hooking into some event or so?

**Comment by ValentinH** [comment]
Indeed this isn't implemented but could be added quite easily, just need to mimic to minRange behaviour. If you want you can submit a PR and I can guide you if needed.

**Comment by envision** [comment]
@ValentinH I tried to create a fork for this but I haven't ever written tests for front-end code so this is too complex project for me to hop in out of the blue...

**Comment by ValentinH** [comment]
I think there are only a few tests to be added. Just search for 'minRange' in the specs folder, copy/paste those tests and adapt them ;) You can already create a Pull request and I can guide you there.

**Comment by envision** [comment]
How can I test my changes with a browser without building dist files in each turn?

**Comment by ValentinH** [comment]
Sorry, I've missed your last answer. I just finished implementing the option...

While developing, you should run grunt watch and everything will be generated automatically.

**Comment by ValentinH** [comment]
Implemented in #333 and released under 2.14.0
