### ISSUE TITLE
Nothing selected on start

### ISSUE THREAD

**Issue by swrocket** [angular-slider/angularjs-slider#324]
First, let me say this directive is awesome!

I am using rzSlider as a rating scale where the user can select a value from 1 to 5 and using the stepsArray.
Everything works well, but I would like the slider to have nothing selected until the user clicks on one of the steps. Currently, the first step(1) is selected by default. 
Here is my controller code"

`
$scope.priceSlider1 = {
      value: -1,
      options: {
        step: 1,
        precision: 1,
        minRange: 0,
        floor:-1,
        stepsArray: [{value:1,legend:"Not Helpful"}, {value:2,legend:"Somewhat Helpful"},{value:3,legend:"Helpful"},{value:4,legend:"Very Helpful"},{value:5,legend:"Extremely Helpful"}],
        draggableRange: true,
        draggableRangeOnly: false,
        showSelectionBar: true,
        showSelectionBarEnd: false,
        showSelectionBarFromValue: false,
        hidePointerLabels: false,
        hideLimitLabels: false,
        interval: 1,
        showTicks: true,
        showTicksValues: true,
        getSelectionBarColor: function(value){
          if(value < 2){
            return "#FFA039";
          }
          else if(value < 3){
            return "#4EA9CC";
          }
          else {
            return "#5cb85c";
          }
        },
        getPointerColor: null,
        scale: 1,
        enforceStep: false,
      }
    };
`

TIA

Andrew

**Comment by ValentinH** [comment]
This is not possible because the slider always needs a value to be rendered. A workaround could be to add an "undefined" value in your stepsArray.

**Comment by swrocket** [comment]
Thanks Valentin. That's what I just ended up doing. I added an item with value "N/A"

**Comment by cperezortiz** [comment]
Hi, I got the same issue, nontheless I'm not able to reproduce the workaround, I added an object to my stepsArray with a undefined value, but it doesn't work ```
vm.stepsArray.push({
                'value': undefined
            });
```
Here's my SliderOptions:

```
vm.sliderOptions = {
                showTicksValues: true,
                stepsArray: vm.ChoicesAsArray,
                onChange: vm.updateEmojiAndSaveAnswerSelected
            };
```

**Comment by ValentinH** [comment]
What does "doesn't work" mean?

**Comment by cperezortiz** [comment]
This (as mentioned by @swrocket): "... I would like the slider to have nothing selected until the user clicks on one of the steps."

**Comment by ValentinH** [comment]
Please provide a demo showing your issue (see the ReadMe)
