### ISSUE TITLE
Ability to disable Keyboard support for slider

### ISSUE THREAD

**Issue by sabin-iliescu** [angular-slider/angularjs-slider#327]
Hi,
Given the fact that the [slideEnded Event is not sent when using arrow keys](https://github.com/angular-slider/angularjs-slider/issues/319) I am wondering if there is any way to disable the keyboard support. 

I want to limit the user interaction with the slider in a way that he cannot adjust the slider with the arrow keys but only with with the mouse.

Thank you.

**Comment by ValentinH** [comment]
Yes just set keyboardSupport to false in the options.

**Comment by ValentinH** [comment]
I still need to add the event for the keyboard but I don't get enough times to do it.

**Comment by sabin-iliescu** [comment]
Thank you very much for the answer.
