### ISSUE TITLE
translate function help requested

### ISSUE THREAD

**Issue by YeeP79** [angular-slider/angularjs-slider#329]
I am trying to rename the ceiling and floor labels using the methods show under 'Slider with custom template to use HTML formatting for ticks' here: http://angular-slider.github.io/angularjs-slider/

I must be sending the parameters in incorrectly because I do not get any expected responses. As you can see I have tried multiple methods of sending in the data but am having no luck. Any suggestions on how to get the labels out of the function would be much appreciated.

js:
```js
$scope.slider = {
  value: minArrayIndex,
  options: {
    id: 'slider-id',
    floor: 0,
    ceil: maxArrayIndex,
    step: 1,
    translate: function (ceil) {
      return label;
    },
    translate: function (floor, id, floor) {
      return value;
    },
    onEnd: function (id) {
      var newMinIndex = $scope.slider.value;
      var chart = $('#chart2').highcharts();
      chart.xAxis[0].setExtremes(newMinIndex, maxArrayIndex);
      //console.log('on end ' + newMinIndex); // logs 'on end slider-id'
    }
  }
};
```

index.html:
```html
<div>
  <rzslider rz-slider-model="slider.value" 
     rz-slider-options="slider.options"
     rz-slider-tpl-url="rz-slider.html"></rzslider>
</div>
```

rz-slider.html:
```html
<span class="rz-bar-wrapper"><span class="rz-bar"></span></span> <!-- // 0 The slider bar -->
<span class="rz-bar-wrapper">
  <span class="rz-bar rz-selection" ng-style="barStyle"></span>
</span> <!-- // 1 Highlight between two handles -->
<span class="rz-pointer rz-pointer-min" ng-style=minPointerStyle></span> <!-- // 2 Left slider handle -->
<span class="rz-pointer rz-pointer-max" ng-style=maxPointerStyle></span> <!-- // 3 Right slider handle -->
<span class="rz-bubble rz-limit">8 hours previous</span> <!-- // 4 Floor label -->
<span class="rz-bubble rz-limit">Latest</span> <!-- // 5 Ceiling label -->
<span class="rz-bubble"></span> <!-- // 6 Label above left slider handle -->
<span class="rz-bubble"></span> <!-- // 7 Label above right slider handle -->
<span class="rz-bubble"></span> <!-- // 8 Range label when the slider handles are close ex. 15 - 17 -->
<ul ng-show="showTicks" class="rz-ticks"> <!-- // 9 The ticks -->
  <li ng-repeat="t in ticks track by $index" class="rz-tick"
    ng-class="{'rz-selected': t.selected}" ng-style="t.style"
    ng-attr-uib-tooltip="{{ t.tooltip }}" ng-attr-tooltip-placement="{{t.tooltipPlacement}}"
    ng-attr-tooltip-append-to-body="{{ t.tooltip ? true : undefined}}">
    <span ng-if="t.value != null" class="rz-tick-value"
      ng-attr-uib-tooltip="{{ t.valueTooltip }}"
    ng-attr-tooltip-placement="{{t.valueTooltipPlacement}}" ng-bind-html="t.value"></span>
  </li>
</ul>
```

![capture](https://cloud.githubusercontent.com/assets/8461870/15398173/eb2e4e34-1d9f-11e6-9a77-2eb6edb0f2c0.PNG)

### Expected behaviour
labels should change on the slider 

### Actual behaviour
error caused by me

**Comment by ValentinH** [comment]
Your `translate` function are returning undefined values. You need to return a valid string like this one for instance:
```js
translate: function(value) {
  return '<b>Price:</b> $' + value;
}
``

**Comment by YeeP79** [comment]
I have seen that example in the other documentation, but I do not see how that can apply to the new label for the slider. I understand that the "value" is what slider uses, but I do not want to show the value, I want to use the custom html label I have created. This example tells me I can use the label, but I don't understand how that works.

------
translate - Function(value, sliderId, label): Custom translate function. Use this if you want to translate values displayed on the slider. sliderId can be used to determine the slider for which we are translating the value. label is a string that can take the following values:

'model': the model label
'high': the high label
'floor': the floor label
'ceil': the ceil label
'tick-value': the ticks labels

**Comment by ValentinH** [comment]
the `label` is the third parameter passed to the translate function, it's used to know where the translated value will be displayed.
