### ISSUE TITLE
How create a time slider 

### ISSUE THREAD

**Issue by R-iskey** [angular-slider/angularjs-slider#330]
Hi, how can I create a Time picker slider with your module , do you have a options for that?

**Comment by ValentinH** [comment]
Nope there is no option to do it natively but you can do it by using the translate function. You might want to check the closed issues because I remember some about this use case.

**Comment by ValentinH** [comment]
This example might help you: http://jsfiddle.net/2umvx8dm/

**Comment by R-iskey** [comment]
Thank you so much !
