### ISSUE TITLE
value of slider changes to String only went at ceiling value

### ISSUE THREAD

**Issue by codingsolutions** [angular-slider/angularjs-slider#334]
### Steps to reproduce
1. create a slider with a floor/ceiling range of 0/1,000
2. use the following translate function to add commas to the slide label
		translate: function(value) {
			return value.toLocaleString();
		}
3. run the code

Demo: sorry don't know how to make fiddles yet

### Expected behaviour
Tell us what should happen
It should display the number and include the comma
0 ----------------------------------- 1,000

### Actual behaviour
Tell us what happens instead
The comma is only displayed on the slider label that you move.
NOTE: If I use $ prefix, that correctly applies to floor/celing and slider labels.

Screenshot
![image](https://cloud.githubusercontent.com/assets/13525707/15490404/370d8190-212d-11e6-950b-e6aa5c7e05ce.png)

EDIT: After playing with this, I see the commas work for the floor value.
Also, if I wrap the value in parseInt before the translate then the commas work.
`		translate: function(value) {
			return parseInt(value).toLocaleString();
		}
`

I figured this out because my slider.value was being added to a $scope variable. Only went it got to the ceiling value it switched to concatenation instead of integer math. So that how I figured out the typeOf value of the slider is string, but only when set to its ceiling.

Anyway, I have a workaround by using parseInt, so **this is super low priority** or perhaps as designed. It just caught me by surprise that **every value is integer except the ceiling value.**

**Comment by codingsolutions** [comment]
Please close this issue. The issue was 100% on my side. I was assigning the ceiling from a variable and it accidentally got a string type instead of an integer type.

I still don't understand why it's doing it, but it is a JavaScript thing. My workaround is to create the variable like this.
var AvailablePoints = parseInt(x);
Even though typeOf x outputs Integer, for some reason, I have to remind JavaScript that it is an Integer.

Anyway, problem solved and sorry for all the chatter on account of me learning JavaScript.

**Comment by ValentinH** [comment]
Good you found a solution! ;)
