### ISSUE TITLE
Is it possible to have a step of 1, and show ticks every ten steps?

### ISSUE THREAD

**Issue by cleon26** [angular-slider/angularjs-slider#336]
I am attempting to show slider allowing users to select a percent complete.  Values are in the range 0 - 100.  I'd like them to be able to select any integer value (1,2, 3, ..., 98, 99, 100).  But only show ticks at major intervals for example (10, 20, 30, 40, 50, 60, 70, 80, 90, 100).

I have tried these options, but which allows me to select an integer value, but display all 100 tick marks.  Am I misunderstanding the documentation?  Or is this not possible?

    sliderOptions: {
        floor : 0,
        ceil : 100,
        step: 1,
        showTicks: 10
    };

**Comment by ValentinH** [comment]
There you go: http://jsfiddle.net/uqmpc5k0/ .

Your options are correct but you are probably using an old version, this feature has been added in 2.12: https://github.com/angular-slider/angularjs-slider/blob/master/CHANGELOG.md#2120-2016-04-22
