### ISSUE TITLE
Callback for currently selected handle?

### ISSUE THREAD

**Issue by synthecypher** [angular-slider/angularjs-slider#339]
I'm looking for a callback that triggered upon selecting a handle?

I need to know when and which handle was last selected.

**Comment by ValentinH** [comment]
Currently, there are `onStart`, `onChange` and `onEnd` callbacks but they don't provide the information about which handle is selected. We could add a `pointerType` value to the passed args like for the `getPointerColor` option.

**Comment by ValentinH** [comment]
This is quite easy to do, so if you feel confident about it, you could provide a PR for this feature and I would be happy to help if needed. ;)

**Comment by ValentinH** [comment]
Now the 4th args passed to the onStart, onChange and onEnd callbacks is either 'min' or 'max' to indicate which handle was used.

**Comment by ValentinH** [comment]
Released with 4.0.1 version

**Comment by synthecypher** [comment]
@ValentinH Thanks sorry for the late reply.
