### ISSUE TITLE
Step and max value bug

### ISSUE THREAD

**Issue by JustinaAtMP** [angular-slider/angularjs-slider#340]
### Steps to reproduce
1. Create slider with step 50
2. set max value at 80, min at 0
3. drag slider to the very end

Demo: http://jsfiddle.net/9hc8ypk4/1/

### Expected behaviour
Value should go like so: 0 -> 50 -> 80.

### Actual behaviour
Current value goes like so: 0 -> 50 -> 100 -> 80.

**Comment by ValentinH** [comment]
This is not a big, your ceil is not coherent with the step, that's why...

**Comment by JustinaAtMP** [comment]
It is a bug when you're dealing with mobile data transfer where max is dynamic, step is static and when max should NEVER go over the bounds. Expecting for step to be coordinated with max is simply unreasonable.

**Comment by ValentinH** [comment]
I see, then you should set enforceRange to true.

**Comment by JustinaAtMP** [comment]
That doesn't seem to do anything for me. It still stops at 100 before 80.

**Comment by ValentinH** [comment]
Indeed. The issue is that you can also argue that the value should ALWAYS match the step...

**Comment by JustinaAtMP** [comment]
So do you have a workaround or a fix for this? Because in my app it's a bug.

**Comment by ValentinH** [comment]
You could use a virtual limit by using the new `maxLimit` option: http://jsfiddle.net/0vc6axxc/

Thus you set the ceil, the the actual maximum (that should match the step) and you can set any maxLimit  you want.

**Comment by JustinaAtMP** [comment]
That worked. Thank you.
