### ISSUE TITLE
support ng-model and ng-model-options="{ getterSetter: true }"

### ISSUE THREAD

**Issue by DmitryGalyuk** [angular-slider/angularjs-slider#342]
### Steps to reproduce
1. use the property as model:
`$scope.appTime = {
				_time: timeZonesService.utcNow(),
				time: function(newTime) {
					if (arguments.length) {
						$scope.appTime._time = newTime;
						$scope.appTime.hours(newTime.hours());
					} else {
						return $scope.appTime._time;
					}
				},`

2. add custom directive to rzSlider with formatter and parser over ng-model

### Expected behaviour
Slider should use the model from ng-model directive. So that it would be possible to use a) properties b) model formatter/parser

### Actual behaviour
Slider's specific attribute for model is used

**Comment by ValentinH** [comment]
The issue is that we don't only have `rz-slider-model` but also `rz-slider-high` for range slider. If you need ng-model, I would suggest to create your own wrapper directive around this one.

**Comment by DmitryGalyuk** [comment]
Thank you!
