### ISSUE TITLE
Sytax Error in rzslider.min.js .. ?

### ISSUE THREAD

**Issue by YeeP79** [angular-slider/angularjs-slider#343]
### Steps to reproduce
1. Load page with slider
2. Open console to see error

I have the slider working great, and I do not have any issues with it as far as function. However, I do see a syntax error in the console, I just thought I would bring it here in case you were interested.
`rzslider.min.js:564 Uncaught SyntaxError: missing ) after argument list`

Here are lines 563 and 564...
`return b.run(["$templateCache", function(a) {`

 `                       a.put("rzSliderTpl.html", '<span class=rz-bar-wrapper><span class=rz-bar></span></span> <span class=rz-bar-wrapper><span class="rz-bar rz-selection" ng-style=barStyle></span></span> <span class="rz-pointer rz-pointer-min" ng-style=minPointerStyle></span> <span class="rz-pointer rz-pointer-max" ng-style=maxPointerStyle></span> <span class="rz-bubble rz-limit"></span> <span class="rz-bubble rz-limit"></span> <span class=rz-bubble></span> <span class=rz-bubble></span> <span class=rz-bubble></span><ul ng-show=showTicks class=rz-ticks><li ng-repeat="t in ticks track by $index" class=rz-tick ng-class="{\'rz-selected\': t.selected}" ng-style=t.style ng-attr-uib-tooltip="{{ t.tooltip }}" ng-attr-tooltip-placement={{t.tooltipPlacement}} ng-attr-tooltip-append-to-body="{{ t.tooltip ? true : undefined}}"><span ng-if="t.value != null" class=rz-tick-value ng-attr-uib-tooltip="{{ t.valueTooltip }}" ng-attr-tooltip-placement={{t.valueTooltipPlacement}}>{{ t.value }}</span> <span ng-if="t.legend != null" class=rz-tick-legend>{{ t.legend }}</span></li></ul>'`

It looks like the closed parenthesis is just not at the end of the file?

**Comment by ValentinH** [comment]
What version are you using?

**Comment by YeeP79** [comment]
According to rzslider.js:
angularjs-slider - v2.13.0

**Comment by ValentinH** [comment]
What browser are you using? This demo is using 2.13.0 and I don't see any error on Chrome: http://jsfiddle.net/fbok9c6s/
