### ISSUE TITLE
About stepsArray

### ISSUE THREAD

**Issue by monsoul** [angular-slider/angularjs-slider#348]
I want to change some values to words ( Can't list all the values cause I want to slider step:0.01 )

such as '1' to 'very poor' , '3' to 'fair'. balabala
but I still want to set **step: 0.01,precision: 10**
so that I can slider to '1.03', '1.05' and so on.
How should I do?
 
https://jsfiddle.net/170bymjp/2/

**Comment by ValentinH** [comment]
If you want to directly replace the value then use the translate function.Otherwise, if you want to display the text as legend below the slider, then use the getLegend option. 

For the 2 options, you don't need to use stepsArray

**Comment by monsoul** [comment]
One more question. If I want to show the ticks which I change text only. (show you the picture)
Any settings? 

Anyway I can change your code to realize this. thank you very much.
![](http://g.hiphotos.baidu.com/image/pic/item/63d0f703918fa0ec0ee070312e9759ee3d6ddbe2.jpg)

**Comment by ValentinH** [comment]
The showTicks can take an integer value to display ticks at intermediate positions.

**Comment by monsoul** [comment]
yes. it works. I like this slider very much

**Comment by ValentinH** [comment]
:+1:
