### ISSUE TITLE
Not an Issue: Dynamic Step support

### ISSUE THREAD

**Issue by kimwandev** [angular-slider/angularjs-slider#349]
I'm wondering if you are going to support dynamic steps?

for example I have a min: 0 to max: 3,000,000 and I would like to have different steps for 0 - 3000 range, 3000 - 1,000,000 range and 1,000,000 to 3,000,000 range.

1. 0 - 3000 will have 100 steps
2. 3000 - 1000000 will have 1000 steps
3. 1000000 - 3000000 will have 250,000 steps

but they will only use a single slider

let me know if you have answer

Regards,
Kim

**Comment by ValentinH** [comment]
I think that #280 solves an issue similar to yours but it doesn't handle ticks...

**Comment by ValentinH** [comment]
An other option is to update the step value on the onChange event: http://jsfiddle.net/5kaea452/

**Comment by kimwandev** [comment]
do you have sample implementation for Min Max?

**Comment by ValentinH** [comment]
What do you mean?

**Comment by kimwandev** [comment]
I mean you are using single value slider as your example. How about slider with range value? 

http://jsfiddle.net/kimwan/jzbu207b/

**Comment by ValentinH** [comment]
Oh OK, then it won't work.
