### ISSUE TITLE
showTicksValues integer value bug.

### ISSUE THREAD

**Issue by baster33** [angular-slider/angularjs-slider#351]
### Steps to reproduce
1. Set `showTicksValues` to integer value that can not be multiplied to `ceil` value

Demo: http://jsfiddle.net/cf3t3rtu/

### Expected behaviour
Choosen value should match ticks. For example 3 should be shown on tick with value 3.
+ In my opinion there should always be shown first and last tick, even if it does not match `showTicksValues` integer value.

### Actual behaviour
Choosen value are placed in different places than ticks. For example 3 is placed before 3 tick, 10 is placed on 9 tick (in fiddle).

**Comment by ValentinH** [comment]
The issue is that your tick interval is not coherent with your floor-ceil range: you have 11 possible values and 11 is not divisible by 3.

**Comment by ValentinH** [comment]
The documentation might need some improvements about this issue.

**Comment by baster33** [comment]
Ok i get this, but what in situation when i have lets say 0-47 floor-ceil range and slider is to short to show all ticks 1 by 1? The only option is to disable `showTicksValues `?

**Comment by ValentinH** [comment]
Indeed, 47 is a prime number so how do you want to divide it? The only way is to disable the ticks.

**Comment by baster33** [comment]
I just thought it is intended to work for all reasonable values.
I see it like this:
take floor as the extreme left tick, ceil as extreme right tick and middle ticks with `showTicksValues` step.

You can consider adding such feature for not coherent `showTicksValues` with floor-ceil range (but i quess it won't be simple to implement it)

Anyway, thank You for fast reply and thank You for great job with angularjs-slider.

**Comment by ValentinH** [comment]
Thanks for your understanding.

Indeed, this is not trivial to modify this behavior. Currently, the ticks are positioned automatically by Flexbox, which is cool and efficient since we don't need to compute the position of each ticks manually.

In order to have something more flexible, an absolute positioning of each tick would be needed but it will be slower and messy.
