### ISSUE TITLE
Slider value in view gets disappeared

### ISSUE THREAD

**Issue by YuvPrime** [angular-slider/angularjs-slider#353]
### Steps to reproduce
1. `<div ng-controller="TestController as vm">
        <p>Price: {{vm.priceSlider.value}}</p>
        <div class="col-md-12">
        <div class="col-md-3">
        <rzslider rz-slider-model="vm.priceSlider.value" rz-slider-options="vm.priceSlider.options"></rzslider>
        </div>
    </div>
    </div>`

2. `vm.priceSlider = {
        value: 23,
        options: {
            floor: 20,
            ceil: 100
        }
    }`

Demo: http://jsfiddle.net/cwhgLcjv/87/

### Expected behaviour
At point 23 & 93, the slider min and max value in view should not disappeared.

### Actual behaviour
At point 23 & 93, the slider value gets disappeared. At point 23, min value disappears, at point 93, the end i.e max value gets disappera.

**Comment by ValentinH** [comment]
The min or max labels disappears to prevent them for overlapping the value label.

**Comment by trodi** [comment]
If you choose to hide the value labels, the min/max overlapping isn't a concern anymore. Shouldn't they not disappear in this instance?
`hidePointerLabels: true`

**Comment by ValentinH** [comment]
Indeed, you're right. In this case, it's a bug.

**Comment by ValentinH** [comment]
Fix released in 5.4.1. Thansk ;)
