### ISSUE TITLE
"rz-slider-tpl-url" Not working?

### ISSUE THREAD

**Issue by hanying33** [angular-slider/angularjs-slider#354]
I tried to use "rz-slider-tpl-url" attribute to customize my slider, but can't get it work. I looked at the source js file, looks like it's always pointing to the provided template. If this feature is working properly, could anyone please provide a demo example?

I am using the js/css file from dist directory.

Thank you!

**Comment by ValentinH** [comment]
It should work and there is already a demo for it: http://angular-slider.github.io/angularjs-slider/ - "Slider with custom template to use HTML formatting for ticks"

**Comment by hanying33** [comment]
I followed the demo, but it didn't work. Is there anything else I need to keep an eye on?

Maybe by understanding the src code can help me with using this attribute. Could you please provide some explaination of the src code piece?

**Comment by ValentinH** [comment]
There you go: https://github.com/angular-slider/angularjs-slider/blob/master/src/rzslider.js#L2049

If you still cannot fix your issue, please provide a JSFiddle showing what you are trying to do, and I'll help you. ;)

**Comment by hanying33** [comment]
Thanks Valentin. What's the difference between src/rzslider.js and
dist/rzslider.js? I see this extra code in dist/rzslider.js:

module.run(['$templateCache', function($templateCache) {
'use strict';
$templateCache.put('rzSliderTpl.html',
"<div class=rzslider><span class=rz-bar-wrapper><span
class=rz-bar></span></span> <span class=rz-bar-wrapper><span class=\"rz-bar
rz-selection\" ng-style=barStyle></span></span> <span class=\"rz-pointer
rz-pointer-min\" ng-style=minPointerStyle></span> <span class=\"rz-pointer
rz-pointer-max\" ng-style=maxPointerStyle></span> <span class=\"rz-bubble
rz-limit rz-floor\"></span> <span class=\"rz-bubble rz-limit
rz-ceil\"></span> <span class=rz-bubble></span> <span
class=rz-bubble></span> <span class=rz-bubble></span><ul ng-show=showTicks
class=rz-ticks><li ng-repeat=\"t in ticks track by $index\" class=rz-tick
ng-class=\"{'rz-selected': t.selected}\" ng-style=t.style
ng-attr-uib-tooltip=\"{{ t.tooltip }}\"
ng-attr-tooltip-placement={{t.tooltipPlacement}}
ng-attr-tooltip-append-to-body=\"{{ t.tooltip ? true : undefined}}\"><span
ng-if=\"t.value != null\" class=rz-tick-value ng-attr-uib-tooltip=\"{{
t.valueTooltip }}\"
ng-attr-tooltip-placement={{t.valueTooltipPlacement}}>{{ t.value }}</span>
<span ng-if=\"t.legend != null\" class=rz-tick-legend>{{ t.legend
}}</span></li></ul></div>"
);

On Thu, Jun 23, 2016 at 11:54 PM, Valentin Hervieu <notifications@github.com

**Comment by ValentinH** [comment]
The dist file just contains the inline default template.

**Comment by hanying33** [comment]
I put the custom template file on the same level as the html file that uses th rzslider directive (for example, index.html), it's working. 

Now, I have another question: 

How do I pass the variables being defined in my own controller (for example, index.js) to the custom template file?

**Comment by ValentinH** [comment]
I don't think it's possible because there are 2 different scopes.

**Comment by hanying33** [comment]
Well, it could be a nice feature for the next release ;)

**Comment by ValentinH** [comment]
How would you implement such a feature? I don't see how this is possible because this is due to the isolation of scopes in Angular...

**Comment by hanying33** [comment]
One way I can think of is to add a customizable option for user, for example, an option with a key named "myOption", user can pass in an object that contains any thing the user wants as a value, then user can use that object in custom templte.

**Comment by ValentinH** [comment]
OK, I see now. I can add this feature as a `customScope` option.

**Comment by ValentinH** [comment]
Do you have an example of use case for this feature?

**Comment by hanying33** [comment]
Great. I don't have live code for you at the moment. I'll explain here:

Under a partial directory, I have four files:
- mySliderTpl.html
- myPage.html
- myController.js
- myPage.css

I wish to have "customScope" variable being defined in myController.js, for example:
`customScope = {'updating_time': '14:23:07', 'other': 'some value here'}`
The value of 'updating_time' will be updated every second by the js code, which will be reflected in mySliderTpl.html, so that I can show the running time in my browser.

Please let me know if you need more details. Thanks!

**Comment by ValentinH** [comment]
But why does it have to be displayed in the slider template? Cant you just display it outside of it in its own template/directive?

**Comment by hanying33** [comment]
That's by design. Need to have it  on template. A customscope would be very
beneficial.
2016年7月5日 22:09，"Valentin Hervieu" <notifications@github.com>写道：

**Comment by ValentinH** [comment]
The time value is displayed on the slider?

**Comment by hanying33** [comment]
Yep. It's not just the time value, could be something else too. Just need
to imtegrate on the slider template.
2016年7月5日 22:17，"Valentin Hervieu" <notifications@github.com>写道：

**Comment by ValentinH** [comment]
I'm sorry to insist but I have seen so many users that needed a feature for the slider while they could have done it themselves, outside of the library. I don't want the library to implement all the custom features of every users so I want to make sure of that.

Could you please provide a mock-up of what you want to achieve?

**Comment by hanying33** [comment]
I understand that. But I don't think I can implement this myself, I will
share the mockup with you tmr. Thanks!
2016年7月5日 22:29，"Valentin Hervieu" <notifications@github.com>写道：

**Comment by ValentinH** [comment]
:+1:

**Comment by hanying33** [comment]
![screenshot from 2016-07-06 11-14-40](https://cloud.githubusercontent.com/assets/6373830/16629560/095b3be2-436b-11e6-88e6-927dd8078b44.png)

**Comment by ValentinH** [comment]
OK I see, but don't you think that the tooltip should be handled in the chart part?

**Comment by hanying33** [comment]
Well. I wish. But that's by design, so I don't have a choice, I have to
implement it as the mockup. I really appreciate your help, this feature
would be a bonus.

>

**Comment by ValentinH** [comment]
I mean, the tooltip should be handled by the chart, this is not the slider concern

**Comment by hanying33** [comment]
The expected result is to have the tooltip move with the green slider (When
video is playing, the green slider will auto move to the right one step
every second, and also the tooltip). The only way I can think of is to
implement it in the custom template.

**Comment by ValentinH** [comment]
Added this option in 5.2.0:
**customTemplateScope** - _Object (default to null)_: The properties defined in this object will be exposed in the slider template under `custom.X`.

**Comment by hanying33** [comment]
Great! Thank you very much! Can't wait to use this feature ;)
