### ISSUE TITLE
Cannot switch from steps array to regular steps with ticks values

### ISSUE THREAD

**Issue by gaelduplessix** [angular-slider/angularjs-slider#359]
### Steps to reproduce
1. Instantiate a slider with a `stepsArray`
2. Update the slider options to instead use regular steps with `showTicksValues` set to true

Demo: http://jsfiddle.net/3jjye1cL/135/

### Expected behaviour
The slider should update to the new settings

### Actual behaviour
`TypeError: Cannot read property '0' of null`, slider is broken

**Comment by ValentinH** [comment]
Good catch! ;) Do you want to submit a PR for this or can you wait for me to fix it?

Actually, [these lines](https://github.com/angular-slider/angularjs-slider/blob/master/src/rzslider.js#L540-L542):
```js
if (this.options.getLegend) {
   this.getLegend = this.options.getLegend;
}
```
should be replaced by:
```js
this.getLegend = this.options.getLegend;
```

At least, for the current error, I don't know yet if toggling `stepsArray` at runtime can have other impacts.

**Comment by gaelduplessix** [comment]
I'm just prototyping the use of this slider for an app so I won't PR right now. If we decide to use it I'll fix the bug if you didn't do it already :)

**Comment by ValentinH** [comment]
OK, so can you just try the fix I suggested to see if it does the job?

**Comment by gaelduplessix** [comment]
Yep, just did and it fixes the bug for my use case, thanks ! It doesn't break the tests neither
