### ISSUE TITLE
Slider range is hidden but taking up space in css.

### ISSUE THREAD

**Issue by mm-wang** [angular-slider/angularjs-slider#362]
Hello,
I have an issue that for some reason, the range of the slider is hidden but taking up space. I'd like to remove that box since I am using angular x-editable to modify the floor and ceiling values of the range. I am using a collapsible div, but I have done a refresh of the slider during the toggle. Can you help?

### Steps to reproduce
1. Create range slider
2. Put inside of a collapsible div using Bootstrap 3
2. Hide limit labels

![image](https://cloud.githubusercontent.com/assets/1688790/16505138/b2882a94-3ee9-11e6-8baf-3aa6d2768448.png)

![image](https://cloud.githubusercontent.com/assets/1688790/16505231/dedb8ece-3ee9-11e6-9e3f-0ef19e4ac93e.png)

### Expected behaviour
The span that is styled with "opacity: 0; left: -34.618px" should not have any content (it should not say 8-36). The span should be empty. I have other sliders that are not hidden in collapsible divs that have this span as an empty span. 

### Actual behaviour
The span takes up space so that I can no longer click the blue 8. 

I started writing a JSFiddle, but you can't see the problem in the fiddle :/. I have other range sliders not in a collapsible div that are fine.

**Comment by ValentinH** [comment]
When you start moving a slider value, does the incorrectly positioned span is move to its normal position?

**Comment by ValentinH** [comment]
OK I could reproduce your bug in this fiddle: http://jsfiddle.net/ddfkL3ok/ When the slider is small, the hidden label is over the button..

**Comment by ValentinH** [comment]
It should be fixed by 5.0.1 release. ;)

**Comment by mm-wang** [comment]
Thanks!

**Comment by mm-wang** [comment]
Thank you! Such a quick fix!

**Comment by mm-wang** [comment]
For some reason, I can't seem to get access through CDN or npm. Does it just take time for the new release to be registered?

**Comment by ValentinH** [comment]
My bad: I forgot to publish it. Now it should be OK.
