### ISSUE TITLE
Can I contribute typings?

### ISSUE THREAD

**Issue by nihitha25** [angular-slider/angularjs-slider#363]
I am using this library for ts and there are no typings in typings registry.

**Comment by ValentinH** [comment]
I have never used TS so I can't really help you, but any contribution is always welcome! ;)

**Comment by trodi** [comment]
There are two main ways to adding Typescript typings as outlined here: [Contributing Typings](https://github.com/typings/typings/issues/322)

1. Ideally it lives in the actual package
2. Decoupled from the actual package, a typing file can be added to the typings registry

Are you open to the first option? Changes would be made to your package.json in addition to the new typings file [Typings in NPM packages](https://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html).

Either way, I've already made a typings file for the current version and am willing to make the remaining changes to share it.

**Comment by ValentinH** [comment]
If you are willing to provide the ideal solution, I'm totally OK with that! ;)

**Comment by trodi** [comment]
I need to do some more research as it seems there have been some on going [announcements](https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/) regarding Typescript definition file generation. I'll try to find some time to get a solution.

**Comment by kevinkuszyk** [comment]
@trodi did you manage to generate a `d.ts` file?  

It looks like the preferred approach now is to include the typings file in the package.

**Comment by trodi** [comment]
@kevinkuszyk Yes, I've created a `d.ts` file and have been using it locally since my previous comment. It covers most of the library, but there are likely small gaps. I can submit a PR if it would be useful to you (I may need to make a couple of changes to my current version beforehand). Maybe you would be able to review the changes?

The one open question for me is where in the project they should live (under src/)? I've not looked at the project build process, so depending on location, that may need to be updated as well.

**Comment by kevinkuszyk** [comment]
@trodi great, that would be useful for us here.  And, yes, happy to review what you have (although I'm no expert in TypeScript yet).

From looking at some other projects, putting the `d.ts` in the root looks ok.  Just make sure you reference it in the `package.json`.  See [here for more info](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html).

**Comment by trodi** [comment]
@kevinkuszyk I've created a PR with my updated definition file, which works fine linked to my local project. Please review PR and I'll make any changes/answer questions as needed. Thanks.
