### ISSUE TITLE
Deactivate clickable slider area

### ISSUE THREAD

**Issue by Hankman88** [angular-slider/angularjs-slider#364]
Hi there and thank you for this awesome component!

Some users experience a "problem" on mobile devices / smartphones. The want to scroll the page and unintentionally click inside the slider range. 
It would be awesome if one could disable the behavior to react outside the sliders handle.

Kind regards,
Nico

**Comment by ValentinH** [comment]
Hi, thanks for the feedback!

`onlyBindHandles` is probably the option you are looking for. ;)

**Comment by Hankman88** [comment]
found it just in this moment.. anyway - thank you for your quick answer!! =)
