### ISSUE TITLE
angularjs-slider displaying NaN and not working with jQuery 3.0.0

### ISSUE THREAD

**Issue by ozirissp** [angular-slider/angularjs-slider#365]
angularjs-slider is not working on mobile browser (or with chrome desktop in mobile mode: CTRL+SHIFT+I and CTRL+SHIFT+M) ...

Display NaN when trying to slide ...  seems to be a touch event issue, because it's working with keyboard (but there is no JS error) ...

Actual problem is discribe with sample in this stackoverflow : 
http://stackoverflow.com/questions/35758496/angular-js-touch-slider-displaying-nan-error-when-used-with-ionic-framework

Sample : https://jsfiddle.net/oziris_sp/t381ff52/
Updated : It's seems to be an side effect of using jQuery 3.0.0

### Expected behaviour
Working without problem on mobile ...

### Actual behaviour
Not working and display NaN when slided

**Comment by ValentinH** [comment]
All sliders on the demo site work on mobile. Please provide the demo that doesn't work.

**Comment by ozirissp** [comment]
Here a jsfiddle : https://jsfiddle.net/oziris_sp/t381ff52/ , try it in mobile mode !

It's happen only with jQuery 3.0.0 ...

**Comment by ValentinH** [comment]
You are right! Touch events are broken with jQuery 3.0. [This line](https://github.com/angular-slider/angularjs-slider/blob/master/src/rzslider.js#L1408) is the culprit because in jQuery 3.0, they use proxy, so this way of testing `undefined` is incorrect.

I'm fixing it right away.

**Comment by ValentinH** [comment]
Demo of fixed version: https://jsfiddle.net/p9aa2ub3/
