### ISSUE TITLE
Incorrect offset left with a `floor` not equal 0

### ISSUE THREAD

**Issue by a-frolovsky** [angular-slider/angularjs-slider#369]
### Steps to reproduce
1. Create simple slider
2. Set `options.floor` not equal 0

Demo:http://jsfiddle.net/kohwtnoL/ 

Screenshot: http://take.ms/9QQH6

### Expected behaviour
Pointer offset left should work correctly.

### Actual behaviour
Pointer offset left work incorrect.(see on demo)

P.S Sorry for my english 😭

**Comment by ValentinH** [comment]
Actually, in your example, the middle is 290 which is correct:
- As you said, (500-80) / 2 = 210
- but then the middle is 80+210 or 500-210 -> 290 ;)
