### ISSUE TITLE
dynamic generation of slider

### ISSUE THREAD

**Issue by Hossam-Hazem** [angular-slider/angularjs-slider#374]
Slider doesn't work when it is produced after page loading, currently, I wait for a response from the user and when I get this response, I run ng-repeat on this response to generate multiple instances of a directive that contain this slider with static values for options, now the sliders doesn't work and produce NaN everywhere. at the same time, I tried static model for the ng-repeat where the user choice isn't included, the sliders loaded with the page loading and they were working fine 

how it is, with dynamic loading:

![dynamic generation](https://cloud.githubusercontent.com/assets/10817601/17039934/9930bc5a-4fba-11e6-98f2-6017e58410b1.png)

**Comment by ValentinH** [comment]
Could you try to provide a demo of what you are trying to do please? I don't really understand actually..

**Comment by Hossam-Hazem** [comment]
the slider outside ng-repeat works fine but the ones inside ng-repeat are inconsistent 

https://jsfiddle.net/e3m6pfLw/

*press ctrl to choose more than one item*

**Comment by ValentinH** [comment]
You JSFiddle doesn't work at all.

**Comment by Hossam-Hazem** [comment]
I am sorry cant deal with JSFiddle, can you copy the code to local?

**Comment by ValentinH** [comment]
I fixed you fiddle and found out that you should init your slider options in the controller function instead if the link one: http://jsfiddle.net/wqy091kk

**Comment by ValentinH** [comment]
Or in the pre-link function: http://jsfiddle.net/dsk2s5mm/
