### ISSUE TITLE
Ticks - first and last ticks are not aligned with the pointer when pointer size is changed

### ISSUE THREAD

**Issue by mickeyvip** [angular-slider/angularjs-slider#375]
### Steps to reproduce
1. add CSS to reduce the size of the pointer: `.rzslider .rz-pointer { top: -7px; width: 16px; height: 16px; border-radius: 50% } `
2. set `showTicks: true` 

![image](https://cloud.githubusercontent.com/assets/220427/17082967/d1a27fa8-5198-11e6-8950-0b2bef157dba.png)

### Expected behaviour
The pointer should be aligned with the tick

### Actual behaviour
The pointer is not aligned

Thank you

**Comment by ValentinH** [comment]
When you change a CSS rule, the best is too change the [LESS file](https://github.com/angular-slider/angularjs-slider/blob/master/src/rzslider.less) and update the variable. In your case, the `@handleSize` variable in the variables.less file.

If you don't want to use the less file, then you should update all the css rules that use this variable.
