### ISSUE TITLE
Minimum value goes below floor when using maxRange

### ISSUE THREAD

**Issue by RedliwLedah** [angular-slider/angularjs-slider#377]
### Steps to reproduce
1.  Click and drag minimum value handle to the right of the maximum value handle, about the distance in the screenshot (1920x1080 resolution). This distance is greater than (or equal?) to the length of the bar if you were at the maximum range.
![sliderdragdistance](https://cloud.githubusercontent.com/assets/20704942/17215555/e338e4d4-54a2-11e6-86e0-dd0a97137f65.png)
2. Note that the minimum handle value becomes max minus maxRange.

Demo: http://jsfiddle.net/udL8nhce/3/

### Expected behaviour
Minimum value slider should stay at its current value, and not go past provided range.

### Actual behaviour
Minimum value slider goes to unexpected value outside of available ranges.

**Comment by ValentinH** [comment]
Good catch :+1:  I'll look into that when I get some time ;)

**Comment by ValentinH** [comment]
Fixed in 5.4.2
