### ISSUE TITLE
Fix for tick label positions being off in IE

### ISSUE THREAD

**Issue by johnreaume** [angular-slider/angularjs-slider#379]
All, 

Just writing a fix to the above issue as on my site on other browsers you get this
![image](https://cloud.githubusercontent.com/assets/2879770/17257599/abcd7278-5577-11e6-97dc-2dffc7ed3cbc.png)

But in IE you get this (notice the label alignment issue?)
![image](https://cloud.githubusercontent.com/assets/2879770/17257656/fe9122ca-5577-11e6-9d4f-835640e1dd18.png)

The fix is a change in the CSS for .rz-ticks and remove
remove list-style: none and replace it with a 1p x 1px transparent gif shown below
list-style-image:url(data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==);

results in...
![image](https://cloud.githubusercontent.com/assets/2879770/17258535/3afe6156-557c-11e6-8d74-f485cf832019.png)

I hope this fixes an issue for everyone else....
John Reaume

**Comment by ValentinH** [comment]
Thanks for this.

Would you like to submit a pull request so that you appear as as contributor in this project?

**Comment by johnreaume** [comment]
I could, but I changed your less file to scss 
That way the project auto compiles to css from within Visual Studio. 

I liked the look of the smaller size slider
John Reaume

**Comment by richthornton** [comment]
Hi, I was wondering if this issue got fixed? It still seems to be an issue for me

**Comment by ValentinH** [comment]
Nope this is not directly fixed by the library, but for now you can use the code provides by this issue reporter. ;)

**Comment by johnreaume** [comment]
No I never pushed these changes to main trunk.
As ValentinH stated just change per the comment above

**Comment by richthornton** [comment]
OK great, I tried out out and it works perfectly. Thanks
