### ISSUE TITLE
Default values for range slider with stepsArray

### ISSUE THREAD

**Issue by PedroF20** [angular-slider/angularjs-slider#380]
See my range slider here?
![image](https://cloud.githubusercontent.com/assets/9113750/17368306/482c2d64-598b-11e6-8edc-b01f9ce8725f.png)

I'm using a stepsArray that contains dates, and each step is a single day:

```
		$scope.slider = {
		    minValue: 0,  
		    maxValue: 1, 
		    options: {
		        stepsArray: getAllDays(), 
		        noSwitching: true,
		        translate: function(value, sliderId, label) {
			      switch (label) {
			        case 'model':
			         	return '<b>Start date:</b> ' + value;
			        case 'high':
			         	return '<b>End date:</b> ' + value;
			        case 'floor':
			         	return '<b>Min date:</b> ' + value;
			        case 'ceil':
			        	return '<b>Max date:</b> ' + value;
			      }
			    }
		    }
		};
```

I wish to start the slider on default with the max range, but it starts with both handles on the first date. Is there any way to pass the first and last dates to the `minValue` and `maxValue`?

**Comment by ValentinH** [comment]
Yes you just need to set these values in your `$scope.slider` object... If your getAllDays() returns an array, extract it before the slider config in a var and set minValue to var[0] and maxValue to var[var.length -1].

**Comment by PedroF20** [comment]
It works. I'll close it. Thanks.
