### ISSUE TITLE
Cursor handle of slider do not move when edited in a Modal

### ISSUE THREAD

**Issue by soldiertt** [angular-slider/angularjs-slider#381]
### Steps to reproduce
1. Put a slider in a Angular-Ui-bootstrap modal
2. Try to change the value of the slider in the controller

Demo: http://jsfiddle.net/soldiertt/0611yj27/

### Expected behaviour
The slider handle should move to the second tick.

### Actual behaviour
The slider handle do not move (or just the small circle of the tick is colored)

Thanx for a fix

**Comment by ValentinH** [comment]
Please read the documentation before asking for a fix.
There is actually a demo of Angular UI Modal on our demo site...

I extracted it for you: https://jsfiddle.net/7n6m2xxu/

**Comment by ValentinH** [comment]
Since I'm a nice guy, here's you fixed demo: http://jsfiddle.net/m872prur/
