### ISSUE TITLE
Provide tooltip timing customization

### ISSUE THREAD

**Issue by dereklin** [angular-slider/angularjs-slider#387]
Here is my plunker: https://plnkr.co/edit/63CT3SHxP0AbYKDB0AVX?p=preview

There are at least two issues with the tooltips:
1. When drag and move the range, the tooltip shows up in the middle of the range
2. As I hover over and move along the ticks, the tooltip is blocking my current min and max value.

For #1, is there a setting to turn off tooltips when dragging the range?
For #2, is there a way to show a tooltip only during x (like 3 to 5) seconds when hover happens?  The tooltip should disappear when the mouse is stationary after x seconds.

**Comment by ValentinH** [comment]
Same as #388
