### ISSUE TITLE
Provide option to disable clicking inside of a range

### ISSUE THREAD

**Issue by dereklin** [angular-slider/angularjs-slider#388]
Here is my plunker: https://plnkr.co/edit/63CT3SHxP0AbYKDB0AVX?p=preview

2014 is within the range, when you click on it, it changes the range.  Is there a option to disable that behavior.  Instead, when you click inside of range, I want to activate the dragging/sliding.

The issue is sometime when I have to drag the range, I would accidentally click and change the range instead.  In order to change to range, one has to either click outside of the range or use to left and right handle to adjust the range.

**Comment by ValentinH** [comment]
Clicking is disable when clicking in the middle of a range while using `draggableRange: true` : http://jsfiddle.net/pnnef5jo/ . The behaviour in your demo is due to the usage of opacity to hide the ticks as I wrote in #382
