### ISSUE TITLE
Selected/Active Tick style is wrong when dragged very fast

### ISSUE THREAD

**Issue by dereklin** [angular-slider/angularjs-slider#390]
Here is my plunker: https://plnkr.co/edit/2S9dbMGA7BAvc5IGgCo6?p=preview

When drag and range and move it very fast left and right, sometimes a tick outside of the range will have a selected/active tick style.  Please see screenshot.

![angular-slider-selected-tick-style](https://cloud.githubusercontent.com/assets/2231799/17462925/8c4a64e2-5c70-11e6-8fbd-6bac74df7c2a.PNG)

**Comment by ValentinH** [comment]
I can't reproduce this on my computer. However, I understand that it can happen when there are many ticks. Actually, in your example, there are a lot of ticks, do you need to have that much ticks?

**Comment by dereklin** [comment]
@ValentinH 
Just want to make sure, you are using my plunker right?  Just drag it and move it very fast left and right a few times very fast, and stop at the very right.

I can produce it pretty easily.

Regarding the number of ticks.  Part of it is data driven.  The other part is that in order to have an accurate tick gaps and range, I need to use:
```
        showTicks: 1,
        showTicksValues: 1,
```

I had tried using
```
        showTicks: 8,
        showTicksValues: 8,
```
and setting my custom ticks array accordingly, but it didn't come out right.
