### ISSUE TITLE
Wrong tick positions in Safari (Slider with dynamic tick color feature)

### ISSUE THREAD

**Issue by TDmeteor** [angular-slider/angularjs-slider#391]
First of all thanks for such nice and rich in features angular.js directive.
It works perfect in Chrome,Firefox and MS Edge, but in Safari 5.1.4 the Ticks are stacked vertically on the left edge of the selection bar.

Demo: http://angular-slider.github.io/angularjs-slider/
![color-ticks](https://cloud.githubusercontent.com/assets/20906731/17481944/2a5d2f44-5d88-11e6-98c2-b3ed85848bef.png)

**Comment by ValentinH** [comment]
Ticks are displayed with flexbox and Safari 5.1 only supports the old syntax of it. Could you try updating the CSS file to add a rule for this old syntax ?
