### ISSUE TITLE
Legend and tick value labels overlap

### ISSUE THREAD

**Issue by KendallSpackman** [angular-slider/angularjs-slider#392]
### Steps to reproduce
1. Use a stepsArray with some labels and use an interval for displaying tick values.

Demo: http://jsfiddle.net/y5ju0ht5/1/

### Expected behaviour
The labels shouldn't overlap.

### Actual behaviour
The legend text and tick value labels overlap.

If you don't use an interval for displaying tick values, the values show above the slider. But when you use an interval, they drop below. Is there a way to control where they display? Or push the legend down further?

**Comment by ValentinH** [comment]
This use case is not supported, but I don't see the reason why you need to display the ticks values though. 

If you really need them, then you can update the CSS rule for the vertical position of the legend.

**Comment by KendallSpackman** [comment]
What I'm looking for is ticks at an interval with occasional legend text. (The range will be something more like 0 to 100 probably.) Here's the updated fiddle with a better example: http://jsfiddle.net/y5ju0ht5/3/
But I was able to modify the CSS rule just fine to push the legend text down. Thank you!
