### ISSUE TITLE
Disabled flag is not disabling range

### ISSUE THREAD

**Issue by dereklin** [angular-slider/angularjs-slider#394]
Here is my plunker: https://plnkr.co/edit/I60kNaLDEdXCcrPKISrb?p=preview

The slider is set to disabled via the flag.  But when I hover my mouse over the range, I still see the move icon.  Ideally, everything should be disabled.  The range selection bar should also be grayed out.

It might good to disabled the tooltips as well.

**Comment by ValentinH** [comment]
Indeed, this looks weird. Also the color of the range might change so it looks better...

**Comment by ValentinH** [comment]
What do you mean by not working?

**Comment by umair-khanzada** [comment]
doesn't disabled range slider.

**Comment by ValentinH** [comment]
Can you modify it? I don't think so as we can see in @dereklin plunker.

**Comment by ValentinH** [comment]
Fixed and released in 5.8.0

**Comment by lchikkala** [comment]
Below is the code which solved for me.

Html: 
<div  range-slider="" disabled="form.disabled">
Js file : 
scope.form = { disabled: false };

scope.click = function()
{
scope.form.disabled = true;
}
