### ISSUE TITLE
slier options

### ISSUE THREAD

**Issue by monsoul** [angular-slider/angularjs-slider#397]
### Steps to reproduce
For some reason, I need to change the slider frequently，
So I use a public slider  , and use angular.copy to set the slider value and options;
but there is a problem . values change but the slider options is not change.
 

simple Demo: https://jsfiddle.net/954eve2L/787/
there are product A and product B
productA's options  is not the same with B
but when I change A -->B and B-->A , the options are the same.

How to fix this?

**Comment by ValentinH** [comment]
The issue is that the options object is watched for changes but when only changing a function content, then $watch doesn't find any changes.

A quick fix is to force the options to be changed by setting a unique value to each option objects like the test one here: https://jsfiddle.net/5ddnsa25/
