### ISSUE TITLE
Is it possible to set decimal value in steps?

### ISSUE THREAD

**Issue by anilkumarsoni** [angular-slider/angularjs-slider#398]
Hello,

I need to show the decimal value on range so is it possible to use that value.
Any type of help will be appreciated.

Thanks in advance.

**Comment by ValentinH** [comment]
Yes, just set a decimal step.

**Comment by ValentinH** [comment]
Oh and the precision option..

**Comment by anilkumarsoni** [comment]
like...??

**Comment by anilkumarsoni** [comment]
thank you. :-)

**Comment by ValentinH** [comment]
There is an example of floating values in the demo page.
