### ISSUE TITLE
The min and max range value disappears when reached at a certain point.

### ISSUE THREAD

**Issue by dassaptorshi** [angular-slider/angularjs-slider#399]
### Steps to reproduce
1. Say the ciel value is 100 
2. When we start sliding towards it around 90 or 91 the label disappears.
3. Both for min and max

### Expected behaviour
There should be a config which can be done to keep the label even when it reaches the limit.

### Actual behaviour
It hides the label.We have an option  'hideLimitLabels' however it hides the limit label completely.
We have a function 'updateHighHandle' which calls this.shFloorCeil() which I believe add the visibility hidden to the CSS. If this can be configured it will be nice.not to call the function.

**Comment by ValentinH** [comment]
So you want this kind of result?
![image](https://cloud.githubusercontent.com/assets/2678610/17732159/c5a8011a-6470-11e6-8ac1-26c9009c4e88.png)

**Comment by dassaptorshi** [comment]
![slider](https://cloud.githubusercontent.com/assets/19878084/17732272/3c0dee8c-6471-11e6-91f7-9c3a437af073.jpg)
 When we drag it around say 80 the label disappears.same goes for the min side label too.Hope this helps

**Comment by ValentinH** [comment]
I don't understand what you need

**Comment by dassaptorshi** [comment]
say i want to drag the slider towards the max value which is 100 , at a certain point, the label max $100 disappears (say at $80) however I would like the label to stay even if I have reached the limit.

**Comment by ValentinH** [comment]
So like on my screenshot?

**Comment by dassaptorshi** [comment]
Yes.
![slidernew](https://cloud.githubusercontent.com/assets/19878084/17733691/279d35a0-6478-11e6-9272-e449c5e68e1f.jpg)

**Comment by dassaptorshi** [comment]
i the directive we have a function updateHighHandle' which calls this.shFloorCeil() which I believe add the visibility hidden to the CSS. So if there is a way we can configure it.

**Comment by dassaptorshi** [comment]
https://jsfiddle.net/saptorshiDas/87ydqyww/

When I drag the slider above say 95 the label disappers. Please kindly check.

**Comment by ValentinH** [comment]
What I'm asking is that if the result I shown in my first screenshot is what you expect?

**Comment by dassaptorshi** [comment]
Yes!

**Comment by ValentinH** [comment]
OK! Then I'll add an option to disable this auto hiding behavior. But are you sure of it, because in my opinion, it looks weird to have overlapped labels

**Comment by dassaptorshi** [comment]
yup that should help. If i need any more help i will get back to you. Thanks a ton!!

**Comment by dassaptorshi** [comment]
Valentin, When can I expect the option to be there in the component?

**Comment by ValentinH** [comment]
If it's urgent, you should do it yourself and contribute a pull request! ;)

**Comment by ValentinH** [comment]
Implemented in #405
