### ISSUE TITLE
Disable min and max values 

### ISSUE THREAD

**Issue by tom1990** [angular-slider/angularjs-slider#400]
### Steps to reproduce

Create a new range slider

### Expected behaviour

Is there a way to show the current minimum value selected and current maximum value selected at the left and right instead of showing them above the bubbles, and showing nothing above to the bubbles ?

**Comment by ValentinH** [comment]
Yes just use custom CSS.

**Comment by tom1990** [comment]
Ok thanks, there is no way like passing a parameter to the directive telling that I don't want those values ?

**Comment by ValentinH** [comment]
Oh sorry I didn't see you were asking for that, yes there is one option for this in the documentation.

**Comment by tom1990** [comment]
Hello,

Sorry to reopen the issue, what I need exactly is this : A slider without values above the bubbles like in this image :
![slider montants 1](https://cloud.githubusercontent.com/assets/3584311/17962885/39432850-6ab3-11e6-905e-92f4e95181bd.PNG)

And when I move the right bubble, the right number updates on the right like in this image :
![slider montants 2](https://cloud.githubusercontent.com/assets/3584311/17962916/5b518e46-6ab3-11e6-8900-86ee44646be3.PNG)

Thanks

**Comment by ValentinH** [comment]
You can trick this by implementing your custom logic in the translate function.
