### ISSUE TITLE
rzslider with angular js 2 not working...

### ISSUE THREAD

**Issue by Overseas634** [angular-slider/angularjs-slider#403]
### Steps to reproduce

I have installed rzslider using npm install and imported in angularjs 2(version)
It is being imported with no issue and when i see frontend(html) the view is not properly rendered.
it only show min and max value as 10-150. where it supposed to show actual price range slider. 
not able to figure out what could be issue.
i am making use of angular fullstack app generator.

**Comment by ValentinH** [comment]
Angular JS 2 is not supported. For now, I'm not planning to port it to Angular 2 since I'm not using. You'll have to wait for somebody to rewrite it or do it yourself if you feel motivated: ;)

**Comment by ValentinH** [comment]
@Overseas634  we now have a angular version: https://github.com/angular-slider/ng5-slider/tree/master 🎉
