### ISSUE TITLE
rz-module-on-change not working with angular2

### ISSUE THREAD

**Issue by Overseas634** [angular-slider/angularjs-slider#404]
<div>
                      <rzslider
                        rz-slider-model="$ctrl.slider.min"
                        rz-slider-high="$ctrl.slider.max"
                        rz-slider-options="$ctrl.slider.options" rz-slider-change="$ctrl.filterOn()"></rzslider>
                   </div>

**Comment by ValentinH** [comment]
Angular JS 2 is not supported. For now, I'm not planning to port it to Angular 2 since I'm not using. You'll have to wait for somebody to rewrite it or do it yourself if you feel motivated: ;)

**Comment by Overseas634** [comment]
need to change 

  .directive('rzslider', function(RzSlider) {
    'use strict';

    return {
      restrict: 'AE',
      replace: true,
      scope: {
        rzSliderModel: '=?',
        rzSliderHigh: '=?',
        rzSliderOptions: '&?',
        rzSliderTplUrl: '@',
        rzSliderChange:'=?' //this line need to add in js
      },

      /**
       * Return template URL
       *
       * @param {jqLite} elem
       * @param {Object} attrs
       * @return {string}
       */
      templateUrl: function(elem, attrs) {
        //noinspection JSUnresolvedVariable
        return attrs.rzSliderTplUrl || 'rzSliderTpl.html';
      },

      link: function(scope, elem) {
        scope.slider = new RzSlider(scope, elem); //attach on scope so we can test it
      }
    };
  });


IN CONTROLLER ADD FUNCTION OF filterOn as i mentioned in rz-slider-change everything in working now.

**Comment by ValentinH** [comment]
` rz-slider-change` is not even part of the library, please read the doc.
