### ISSUE TITLE
Feature Request: Make it work with date ranges

### ISSUE THREAD

**Issue by jongunter** [angular-slider/angularjs-slider#406]
It would be really cool if this directive could work with dates (or date ranges). Bind a variable of type "Date" to the `ng-model`. Thoughts?

**Comment by ValentinH** [comment]
You can achieve such a behavior by using the translate function.

**Comment by jongunter** [comment]
That's what I'm currently doing.  However, the ability to pass in native JS Dates via `ng-model` would be awesome native functionality.  For my current implementation, I just made a wrapper directive that converted dates to numbers, then passed them to the `<rzslider>`

**Comment by ValentinH** [comment]
Indeed it could be a good feature. If you are motivated for it, you can submit a pull request. The behavior of the step option is still to be defined for this feature though.

**Comment by ValentinH** [comment]
From 5.8.0 release, you can use Dates in stepsArray ;)
