### ISSUE TITLE
Problem with browserify

### ISSUE THREAD

**Issue by bampnet** [angular-slider/angularjs-slider#407]
Uncaught TypeError: angular.module is not a function

rzslider.js/line 26 var module = angular.module('rzModule', [])

### Steps to reproduce
1. Install browserify
2. require angular and the plugin:
require('angular');
require('angularjs-slider');
3. launch browserify

I'm browserifiing with gulp.. 

Demo: You can try it on RequireBin:

Package File:
-----------
{
  "name": "requirebin-sketch",
  "version": "1.0.0",
  "devDependencies": {
    "browserify": "^13.1.0",
    "angular": "^1.5.5",
    "angularjs-slider": "^5.4.3"
  },
  "dependencies": {
    "angular": "1.5.8"
  }
}

Code File:
-----------
require('angular');
require('angularjs-slider');

### Expected behavior
Not giving this error

### Actual behavior
Give the error: Uncaught TypeError: angular.module is not a function

**Comment by trumbitta** [comment]
Same thing with webpack. Any hints?

sad 🐼

**Comment by ValentinH** [comment]
I'm not using Browserify nor Webpack so I can't really help... But I know some users managed to use it (see in the closed issues)...

However, the error seems to show the angular is not present in the page when the slider is loaded....

**Comment by ValentinH** [comment]
See this one for instance: #326

**Comment by ValentinH** [comment]
Closing as there was no answers for 10 days.

**Comment by LeonLegion** [comment]
fix for it
replace 
22:     module.exports = factory(require('angular'));
with
    var a = require('angular');
    if (!a.module && typeof angular != 'undefined') {
      a = angular;
    }
    module.exports = factory(a);
