### ISSUE TITLE
Why we have to supply highest value in model?

### ISSUE THREAD

**Issue by hamxabaig** [angular-slider/angularjs-slider#408]
Hi, Thanks for this awesome library.
I want to ask why we have to supply it highest value in the model for it to render?
For example, i want to render the slider from 0 to 100max. But for it to render I have to set my model to 100 which isn't expected as my model always has default value of 0. Is there any option to set highest value without setting model value?
What it currently works with is:
```
$scope.someHighVal = 100 // now renders 0 to 100 but my model is now set to 100 by default
<rzslider rz-slider-model="someHighVal" rz-slider-options="{}" ></rzslider>
```
What I want to do is:
```
$scope.someHighVal = 0 // now it should render 0 to 100max and my model should be at 0 default
<rzslider rz-slider-model="someHighVal" rz-slider-options="{highVal: 100}" ></rzslider>
```

Please help! as I really want to use this cool library. :) 
Many Thanks
Hamza

**Comment by ValentinH** [comment]
You have to set the ceil option to 100 then. It corresponds to the highVal option you set in yojr second example.

**Comment by hamxabaig** [comment]
hey cool, thanks
Worked like charm!
