### ISSUE TITLE
Slider with the input directive not working

### ISSUE THREAD

**Issue by NM-Manasa** [angular-slider/angularjs-slider#412]
Hello, 

I am new to angularjs and also to the rz slide, have implemented rzslider for one of the project with the input value. 
https://jsfiddle.net/manasanmurthy/L3zjhros/

Slider have no issues, however the min value of slider is 1000 and even if i enter 100 in the input model slider accepts it. How do i restrict the input to only accept the values in range?

**Comment by ValentinH** [comment]
You might want to try setting the `enforceRange` to true.

However, your demo isn't working so I can't really help more...

**Comment by NM-Manasa** [comment]
Sorry, here is the demo: http://jsfiddle.net/manasanmurthy/277t4jLv/

**Comment by ValentinH** [comment]
It's not working:
![image](https://cloud.githubusercontent.com/assets/2678610/18544220/e5351520-7b33-11e6-8157-75bb6a0c2586.png)

**Comment by NM-Manasa** [comment]
please use this http://jsfiddle.net/manasanmurthy/huf0zg8b/

**Comment by ValentinH** [comment]
As I said, use `enforceRange`: http://jsfiddle.net/xn1rvh57/

**Comment by NM-Manasa** [comment]
Awesome. Thanks

**Comment by NM-Manasa** [comment]
This doesn't allow me to enter manual values which is in range also, like 3000.

**Comment by ValentinH** [comment]
Yes this is the issue with enforceRange if you start typing 3000, then you will get 3, 30, 300 which are not in the range and so get truncated.

What you can do is to wrap your input in a directive that only change the model value after a timeout.

**Comment by NM-Manasa** [comment]
Thanks. 
Can you give me one simple example of what you are suggesting?

**Comment by ValentinH** [comment]
Basically, you watch the change event of your input, and set the model value after a timeout... So let's say this is the listener attached to your input:

```js
vm.onChange = function() {
    $timeout(function() {
       vm.modelValue = vm.inputValue
    }, 1000) // will fire after one second
}
```

But it's probably better to simply update the model value on the blur event....

**Comment by NM-Manasa** [comment]
This ng-model-options="{ updateOn: 'blur' }" ?

Do we have any options to update on "enter" as well?

**Comment by ValentinH** [comment]
yes this option is probably OK for ng-model... ;) 

I don't know for enter, I never really used the ng-model-options
