### ISSUE TITLE
Slider with the input directive not working - reopen

### ISSUE THREAD

**Issue by NM-Manasa** [angular-slider/angularjs-slider#413]
Hello, 

I am new to angularjs and also to the rz slide, have implemented rzslider for one of the project with the input value. 
https://jsfiddle.net/manasanmurthy/L3zjhros/

Slider have no issues, however the min value of slider is 1000 and even if i enter 100 in the input model slider accepts it. How do i restrict the input to only accept the values in range?

--Solution was provided to use enforceRange: http://jsfiddle.net/xn1rvh57/

however i cannot enter the value which is in range also in input field manually. eg 3000. Please help

**Comment by ValentinH** [comment]
Issue handled in the first opened issue
