### ISSUE TITLE
Ticks on slider are not stretch properly

### ISSUE THREAD

**Issue by girniakolenka** [angular-slider/angularjs-slider#414]
### Steps to reproduce
1.  I have created simple slider with range by using `stepsArray` property
2.  `$scope.minRangeSlider = {
        minValue: 10,
        maxValue: 100,
        options: {
            floor: 0,
            ceil: 100,
            showTicksValues: true,
            stepsArray: [10, 17, 71, 86, 100]
        }
    };`

Demo: https://jsfiddle.net/8yt262cg/ (fork this example and update the link)
I have edited your examples (example with   "Range slider")

### Expected behaviour
Ticks on slider should stretch depends on values which they have
![exp](https://cloud.githubusercontent.com/assets/3527156/18749006/8dc1dde6-80dd-11e6-89af-0dbbad8b7c65.png)

### Actual behaviour
Ticks on slider are not stretch properly
![act](https://cloud.githubusercontent.com/assets/3527156/18748997/84a99244-80dd-11e6-8c71-58a98341da5a.png)

**Comment by ValentinH** [comment]
Unfortunately, this is not possible with the current version. This limitation is due to the way the ticks are rendered: flexbox is used and so the ticks are automatically spread on the slider.

At the moment, I don't have any solution to provide...

**Comment by girniakolenka** [comment]
Is there any possibility that it will be fixed in next versions?

**Comment by girniakolenka** [comment]
Ok, thank you for your response

**Comment by ValentinH** [comment]
@girniakolenka  I have work on a ticks refactoring that enables to position ticks at specific position: #426. Do you think it would match your needs?

**Comment by ValentinH** [comment]
#426 has been merged so `ticksArray` is available from 5.6.0. Now you can have a slider that look likes what you wanted, but it will still have intermediate positions... With the current implementation of the slider, this is not possible.

**Comment by ValentinH** [comment]
If you only want these values: [10, 17, 71, 86, 100] and if they need to be positioned like in the example you gave, you can implement your own custom scale by using the `customValueToPosition` and `customPositionToValue` options.

**Comment by girniakolenka** [comment]
Thank you very much!
