### ISSUE TITLE
Show current value in the pointer(ball)

### ISSUE THREAD

**Issue by bsssp** [angular-slider/angularjs-slider#416]
Like this: 

![image](https://cloud.githubusercontent.com/assets/13966807/18829107/10fbbc5e-83db-11e6-9895-9d34fa6a2a9b.png)

**Comment by ValentinH** [comment]
This is a quick demo: http://jsfiddle.net/8xwph3wp/

But the click doesn't work on the text so this is annoying... I need to think more about it.
