### ISSUE TITLE
Slider value is crossing the ceil

### ISSUE THREAD

**Issue by sushantt2099** [angular-slider/angularjs-slider#417]
### Steps to reproduce
1. Use the following option to initialise the slider
```
vm.priceSlider = {
        value: 200,
        options: {
            floor: 1,
            ceil: 700,
            showTicksValues: 70,
            // translate: (value) => {
            //     if(value > 1) return value - 1;
            //
            //     return value;
            // },
            showSelectionBar: true
        }
    }

```
Demo: http://jsfiddle.net/gfk1hzLp/ (fork this example and update the link)

### Expected behaviour
The upper limit should not cross the ceil. The tick value label should also not cross the ceil

### Actual behaviour
The upper limit is crossing the ceil, the tick value label is also crossing the ceil

**Comment by ValentinH** [comment]
Yes this is a known issue with showTicks values that don't fit perfectly in the range. However, the upper limit isn't crossing the ceil as you said.

This option should be used with a correct value that matches the range:
 `(ceil - floor) % showTicks  == 0`.

**Comment by sushantt2099** [comment]
Hi, the upper limit does cross the ceil if you click on the last tick point(not sliding the slider). 
![screen shot 2016-09-24 at 5 11 43 pm](https://cloud.githubusercontent.com/assets/2559815/18831195/081f379c-8402-11e6-8c95-e9e982fde7be.png)

**Comment by ValentinH** [comment]
Still, your range doesn't match the ticks value you specified.

**Comment by ValentinH** [comment]
@sushantt2099  I have work on a ticks refactoring that enables to position ticks at specific position: #426. Do you think it would match your needs?
