### ISSUE TITLE
Broadcasting rzSliderForceRender in Angular 1.5 components

### ISSUE THREAD

**Issue by TimMcCauley** [angular-slider/angularjs-slider#418]
I'm using this beautiful library in an Angular 1.5 app with components. Thank you very much for your efforts. I need to `rzSliderForceRender` certain sliders after `ng-show.` The broadcast functionality isn't available by default on the components in ng 1.5 which makes [this example ](http://jsfiddle.net/3jjye1cL/) not too easy to copy. Any ideas how to proceed easily? Cheers and thanks!

**Comment by ValentinH** [comment]
With components, you can still inject the $scope object:
```js
function ExampleController($scope, $timeout) {
	var ctrl = this;

	ctrl.refreshSlider = function () {
		$timeout(function () {
			$scope.$broadcast('rzSliderForceRender');
		});
	}
}

angular.module('test').component('testComponent', {
  templateUrl: 'testComponent.html',
  controller: ExampleController
});
```

**Comment by TimMcCauley** [comment]
@ValentinH : superb, thank you very much for your help. Cheers!
