### ISSUE TITLE
Ability to scroll / extend the range using a scrollbar ?

### ISSUE THREAD

**Issue by ashevade1** [angular-slider/angularjs-slider#419]
This is more a question than an issue. I am not sure if there is a seperate forum for posting this. So posting it here. Please to excuse me if this is not the correct place for it

  Right now we specify  the two end limits for a range slider. Is there a way to add a scroll bar kind of functionality , where clicking the scrollbar would extend the upper and lower limits ?
  Not sure if there is an option for this.

Any help is appreciated

Thanks
Ani
### Steps to reproduce
1. 
2. 
3. 

Demo: http://jsfiddle.net/cwhgLcjv/ (fork this example and update the link)

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by ValentinH** [comment]
It is totally OK to post a question here! Unfortunately I don't understand what you want... Could you detail a bit further process please?

**Comment by ashevade1** [comment]
HI
 So I am using this slider for a date-time selection.  Initially I do set the Two end limits of the slider: Teh start and end date, and the user selects a range between those.
 IS there a way so that the start and end points/ limits ( or floor and ceil ) can be changed, by using a scroll bar kind of functionality. 
 So for e.g say I set the Start date as Sept 1, and end Date as Oct 30. So thats all is visible and selectable in the slider. If the user now wants to chose a date ealier or Later,  can I have a scroll bar ( or some otehr way ) to allow him to to that. So here scrolling left would change the  low limit to below Sept 1, and scroll right extends the upper limit
Hope I make sense
I will try to attach a pic if I can

**Comment by ValentinH** [comment]
This might be possible but not directly done by the library. You can implement this custom logic as a wrapper logic but you will need to design the scrollbar part. From the library point of view, you can change the floor and ceil at runtime.

**Comment by ashevade1** [comment]
Thanks , Appreciate your prompt response
