### ISSUE TITLE
[Question] Displaying  Long tick values

### ISSUE THREAD

**Issue by ashevade1** [angular-slider/angularjs-slider#420]
Hi
  This is a question and not an issue.
If the Tick value to be displayed is too long , what are some of the possible options ?
  In this case I am trying to display Date and time. , as the tick value, and its pretty large.

Can we just show tick values for some of the intermediate ticks and not all  ( to save space )
Any other pointers are appreciated

The way I tried to do this by displaying the Date as the tick value, and the Time part as the Hint. 
But I think there got to be a  more elegant solution

Thanks for any help.

Best Regards
Ani

**Comment by ValentinH** [comment]
You can set a number value for the ticks to display a tick at specific positions. You can also use the legend option... There are a demo for each option on the website.

**Comment by ValentinH** [comment]
Closing as there was no answers for 15 days.
