### ISSUE TITLE
How to call getPointerColor in sode the onEnd OR after  onEnd funcation.

### ISSUE THREAD

**Issue by anilking** [angular-slider/angularjs-slider#422]
### Steps to reproduce
1. I have condition in onEnd function to set the pointer color.  
2. but getPointerColor  is executing before the onEnd function. 
3. 

Demo: http://jsfiddle.net/cwhgLcjv/ (fork this example and update the link)

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by ValentinH** [comment]
You condition should be in `getPointerColor` because it's the one responsible for defining the color...
