### ISSUE TITLE
onEnd never triggered on iOS

### ISSUE THREAD

**Issue by apatzer** [angular-slider/angularjs-slider#423]
I have a site with multiple sliders, and all works well on the desktop.

On mobile (iOS 10) the slider is never deselected on a 'touchend' and continues to perceive all touch motions, such as dragging the page even outside the slider as slider inputs. Very frustrating.

I have tried 'onlyBindHandles: true' but this did not seem to help.

I have traced the problem down to `onEnd` never being called. I don't know if this is related but on line 1648 of rzslider.js:onStart I think `$document.one` should be `$document.on`

```
        $document.on(eventNames.moveEvent, ehMove);
        $document.one(eventNames.endEvent, ehEnd);
```

**Comment by apatzer** [comment]
There's still a typo / error on 1648, but the issue happened to be another Angular module (ngImgCrop) that was binding to 'touchend' and calling stopPropagation() before RZ slider had a chance to view the event.

**Comment by ValentinH** [comment]
Thanks for reporting but  line 1648 is not a typo. We are binding the end event only once because it's not supposed to happen more than once for a given start event...
