### ISSUE TITLE
How to pass a value from view to model using angularjs-slider ?

### ISSUE THREAD

**Issue by ZebMustafa** [angular-slider/angularjs-slider#427]
Hi there,
How can I pass some value from view to model i-e $index value or any other some special value.
Any help would be appreciated.

**Comment by ValentinH** [comment]
What view/model are you talking about?

**Comment by ZebMustafa** [comment]
Thanks for the response.
Actually I have place slide bar in ng-repeat. So I want to pass some values, when slide bar value change. For this I need to call a function and pass some values from the html view . For-example 
I want to put the below line with **rzslider**  tag. So that I can have some meaningful information on changing bar.
ng-change="changeDevicesStatus(device.deviceId,devEpInfo.state)"
 I hope now it's clear to you.

**Comment by ValentinH** [comment]
You want to use the `onChange` option.

**Comment by ZebMustafa** [comment]
Yes , I want to to call some on onChange.
Actually I want to pass **deviceID**  from my view when slider value changes. Just as we can do for-example <input ng-change="invokeMethod(deviceID)">. I want the same thing with **rzSlider**. Can I do this ?

**Comment by ValentinH** [comment]
just use the `onChange` option
