### ISSUE TITLE
When slide is create as a hidden element, the slide max value doesn't move to the end of the slide

### ISSUE THREAD

**Issue by LTroya** [angular-slider/angularjs-slider#428]
Hi,

I am having this issue with the slide, I work perfects if the slider is visible at the document ready. But if it is hidden, when it is displayed, it looks like the image below

![screen shot 2016-10-10 at 7 07 47 pm](https://cloud.githubusercontent.com/assets/6491259/19253971/f1b83d66-8f1c-11e6-92bc-9ca6306bf2d7.png)

When it is visible at first looks perfect. Is there a way to solve this?

    $scope[slideName] = {
     minValue: model.lowestValue,
     maxValue: model.highestValue,
     options: {
          floor: model.lowestValue,
          ceil: model.highestValue,
          step: 50,
          hidePointerLabels: true,
          hideLimitLabels: true
     }
    };

**Comment by ValentinH** [comment]
This issue is documented in the README.
