### ISSUE TITLE
Slide Text Color

### ISSUE THREAD

**Issue by missakation** [angular-slider/angularjs-slider#429]
Hello, I am just wondering if I can change the text color of the slider(the one above the circle). It is always dark grey/black.
I want to change it to white or yellow.

**Comment by ValentinH** [comment]
Yes you just need to overwrite the CSS rule.

**Comment by ValentinH** [comment]
Here is a too-much example showing what could be done.

**Comment by missakation** [comment]
yh thanks found it .
it was the color of .rzslider .rz-bubble
