### ISSUE TITLE
Problem in popup

### ISSUE THREAD

**Issue by Chklang** [angular-slider/angularjs-slider#431]
Hi

I've tried to use this slider in a popup and i've a bug : Slider isn't initialized to correct position. I've created a plunker for it :

https://plnkr.co/edit/yUVQij6kAfwMJqimdIOW?p=preview

Can you help me?

Thanks in advance.

**Comment by ValentinH** [comment]
This issue is documented in the ReadMe and there is a demo for uibModal on the demo site.

**Comment by Chklang** [comment]
Ho...

hum...
RTFM ><

Thanks!

**Comment by ValentinH** [comment]
I managed not to answer this! :D
