### ISSUE TITLE
Conserve linear position of values on Steps Array

### ISSUE THREAD

**Issue by emilgoldfarb** [angular-slider/angularjs-slider#433]
Allow for the option of preserving the linear positioning of values specified StepsArray.

Exaple: 
stepsArray: [0, 10, 25, 50, 100],
preserveLinearity: bool  (when true, will place the items linearly on the slider as opposed to evenly spaced)
Enforce that only these values are selectable.
The example above would render a slider like this, slider would only stop at the X values.

x......x..............x......................x.............................................x

Thanks for your support.
Emil

**Comment by ValentinH** [comment]
This is not easy to do. Internally, `stepsArray` is handled with [0,1,2,3,4] values that are translated for the display.
Currently, you can achieve what you want by using the `customValueToPosition` and     `customPositionToValue` options. The goal is to define your scale the specify the relation between your values and how they are rendered.

**Comment by ValentinH** [comment]
Closing as there was no answers for 14 days.

**Comment by emilgoldfarb** [comment]
I have already made a modification to the code to make this work. Would you
like me to share it with you?

**Comment by ValentinH** [comment]
Yes let Lee see it ;

**Comment by emilgoldfarb** [comment]
Added this function:

closest:function(num,arr) {
        var mid;
        var lo = 0;
        var hi = arr.length - 1;
        while (hi - lo > 1) {
            mid = Math.floor((lo + hi) / 2);
            if (arr[mid] < num) {
                lo = mid;
            } else {
                hi = mid;
            }
        }
        if (num - arr[lo] <= arr[hi] - num) {
            return arr[lo];
        }
        return arr[hi];
      }


And modified this function:

      onMove: function(pointer, event, fromTick) {
        var newPos = this.getEventPosition(event),
          newValue,
          ceilValue = this.options.rightToLeft ? this.minValue :
this.maxValue,
          flrValue = this.options.rightToLeft ? this.maxValue :
this.minValue;

        if (newPos <= 0) {
          newValue = flrValue;
        } else if (newPos >= this.maxPos) {
          newValue = ceilValue;
        } else {
          newValue = this.positionToValue(newPos);
          if (this.options.ticksArray) {
             newValue=this.closest(newValue,this.options.ticksArray);
          } else if (fromTick && angular.isNumber(this.options.showTicks))
            newValue = this.roundStep(newValue, this.options.showTicks);
          else
            newValue = this.roundStep(newValue);
        }

        this.positionTrackingHandle(newValue);
      },


It' not a complete implementation, but it works when dragging with the
mouse. It does not work with the keyboard yet.

**Comment by ValentinH** [comment]
Could you provide a demo of it?

**Comment by czery** [comment]
Hi there,

just stumbled upon this and created a solution with the customPositionToValue functionality. You can find the demo here: https://jsfiddle.net/czery/mwy45dxt/ - maybe it will help anybody.

Cheers
czery

**Comment by emilgoldfarb** [comment]
Hi thanks for writing and for the example. It's similar to my
implementation but mine was done internally as opposed to having the
requirement for the user to implement a custom method. My implementation
used the existing "ticksArray" and forced stops and the specified ticks. It
does not require any additional implementation by the user. In any case, I
am unable to provide a full example because many iterations ago we moved
away from using the slider in that particular case and implemented (for
other reasons) a SVG based interface. We still use the slider in other
areas but we don't make use of that particular feature.

Here is my onMove function:

      onMove: function(pointer, event, fromTick) {
        var newPos = this.getEventPosition(event),
          newValue,
          ceilValue = this.options.rightToLeft ? this.minValue :
this.maxValue,
          flrValue = this.options.rightToLeft ? this.maxValue :
this.minValue;

        if (newPos <= 0) {
          newValue = flrValue;
        } else if (newPos >= this.maxPos) {
          newValue = ceilValue;
        } else {
          newValue = this.positionToValue(newPos);
          if (this.options.ticksArray && !this.options.step) {
             newValue=this.closest(newValue,this.options.ticksArray);
          } else if (fromTick && angular.isNumber(this.options.showTicks))
            newValue = this.roundStep(newValue, this.options.showTicks);
          else
            newValue = this.roundStep(newValue);
        }

        this.positionTrackingHandle(newValue);
      }


Thanks for your support.

Emil
