### ISSUE TITLE
Slider RTL with min on the left and max on the right

### ISSUE THREAD

**Issue by mebibou** [angular-slider/angularjs-slider#434]
### Steps to reproduce
1. Visit the demo and try it out

Demo: http://jsfiddle.net/ewfb0vgs/1/

### Expected behaviour
Basically I want to have a slider that show the selection on the right, but have the min on the left and the max on the right. I know that `floor` should be the min, and `ceil` the max, but if using `rightToLeft` then it automatically inverts the poles, which is not what I want.
Ideally, I would like to be able to specify that I want `rightToLeft: true` only on the selection bar

### Actual behaviour
It is actually impossible to use the slider this way.

**Comment by mebibou** [comment]
Sorry my bad I checked the doc but didn't see the `showSelectionBarEnd` option

**Comment by ValentinH** [comment]
Indeed,  `rightToLeft` target users from country where the read from right to left.
