### ISSUE TITLE
Translate Value Changes from first index to last Index

### ISSUE THREAD

**Issue by gongalt** [angular-slider/angularjs-slider#435]
### Steps to reproduce
1.  The current value of the slider pointer changes from the first index to the last index on pointer click.

### Expected behaviour
Value should not change unless the pointer is moved or translated.
on pointer click, value should not change.
on pointer click + dragged, value should change

### Actual behaviour
Value changes fron index 0 to 5
I. E. [1,2,3,4,5]
current value = 1
on pointer click translate value changes from 0 to 5 even the slider pointer is not dragged.

I'd like some help with it thanks.

**Comment by ValentinH** [comment]
Could you please provide a JSFiddle showing the issue and a list of steps to reproduce it?

**Comment by gongalt** [comment]
I have this.

```

myCtrl.slider = {
            value: 1,
            options: {
                floor: lodash.head([1,2,3,4,5]),
                stepsArray: [1,2,3,4,5],
                ceil:lodash.last([1,2,3,4,5]),
                translate: function(value) {
                    console.log('Data: ' + value);
                    return  value;
                },
                showSelectionBar: true,
                getSelectionBarColor: function(value) {
                    return '#7F7F7F';
                },
                getPointerColor: function(value) {
                    return '#ffffff';
                },
                hidePointerLabels: false,
                hideLimitLabels: true,
            }
        };

<rzslider 
                    rz-slider-model="myCtrl.slider.value"
                    rz-slider-options="myCtrl.slider.options"></rzslider>
```

so what is expected is when I click on the pointer, it should not move the value for some milliseconds to the last index of the steps array i.e

[1,2,3,4,5]
current value = 1
clicking the pointer changes the value from 1 to 5 and reverts back to 1.

expected output,
when clicking the pointer should do nothing, dragging the pointer should change the value according to the steps array.


Let me know if this helps verify my problem.

**Comment by ValentinH** [comment]
When using `stepsArray`, you don't need to set floor/ceil. Moreover, for a slider from 1 to 5, you don't need to use stepsArray, just set floor=1 and ceil=5.

Moreover, you should not change the colors of the sliders with functions if it doesn't change at runtime, it's better to do it via CSS.

**Comment by ValentinH** [comment]
Also your translate function is useless here... I feel like this is not the real code you are using in your app because this one should work... If my comment didn't fix your issue, you should really take the Fiddle from the README (in the reproducing issue part), modify it, fork it and share it here. Otherwise, I can't help more.

**Comment by gongalt** [comment]
Thanks for clarifying, I removed the translate and just used the onEnd option so the value only changes on end. Will close this thread now. Thank you for a good support! :)

**Comment by ValentinH** [comment]
`translate` and `onEnd` don't serve the same purpose at all! I strongly feel like you don't use the library properly... What are you trying to achieve?

**Comment by gongalt** [comment]
Hello,

the approach i have with the translate and onend seems to work,

what I wanted to achieve is this,

I have a dynamic array which is used as a stepsarray

now when I click on the point + drag it to each steps, it should show the value of that steps ( which I got working )

now I only have the on pointer click issue with the translate since when I click on the pointer, the value changes from the current value to the last of the steps array. This is what I have working.



```
singleProductCtrl.slider = {
            value: $sessionStorage.currentProductVersionWatts,
            max: lodash.last($sessionStorage.productWatts),
            options: {
                stepsArray: $sessionStorage.productWatts,        
                translate: function(value) {
                    var data = ((!lodash.isUndefined(lodash.find($sessionStorage.wattsLumens, {"Watts": value})) ? lodash.find($sessionStorage.wattsLumens, {"Watts": value}) : 0));
                    singleProductCtrl.valueWatts = $sessionStorage.currentProductVersionWatts = value;
                    singleProductCtrl.valueLumens = $sessionStorage.currentProductVersionLumens = data.Lumens;
                    return  value;
                },
                showSelectionBar: true,
                getSelectionBarColor: function(value) {
                    return '#7F7F7F';
                },
                getPointerColor: function(value) {
                    return '#ffffff';
                },
                hidePointerLabels: false,
                hideLimitLabels: true,
                onEnd: function(id, value, high) {
                    var data = ((!lodash.isUndefined(lodash.find($sessionStorage.wattsLumens, {"Watts": value})) ? lodash.find($sessionStorage.wattsLumens, {"Watts": value}) : 0));
                    singleProductCtrl.valueWatts = $sessionStorage.currentProductVersionWatts = value;
                    singleProductCtrl.valueLumens = $sessionStorage.currentProductVersionLumens = data.Lumens;
                }
            }
        };


```

not sure if I had it correctly but it seems to be what I needed. :)
