### ISSUE TITLE
Custom Tick values for range slider

### ISSUE THREAD

**Issue by aakashrathore** [angular-slider/angularjs-slider#442]
How do I add custom ticks for a range slider
I used ticksArray[] and it is not displaying anything. Is it used only for a non range slider?
Thanks

**Comment by ValentinH** [comment]
What do you want to display? Can you share a demo?

**Comment by aakashrathore** [comment]
So basically I am adding stuff to a timeline and using the slider to display the dates where the events have been added .
eg: say i've created a slider from 0 to 1million. So if i add an event to the timeline at 5000, a tick on the slider should be created at the index 5000.
I did this by adding 5000 to the stepsArray, yet nothing's displayed. Please correct me if this is the wrong implementation of stepsArray.

**Comment by ValentinH** [comment]
stepsArray should contain all the possible values of the slider, so in your example, at least: [0, 5000, 1000000]. Then if you want many values but just one tick, then you want to use the `ticksArray` option.

**Comment by aakashrathore** [comment]
Hey, Thanks for the response. I tries ticksArray for random tick positions. But the ticks are not getting displayed.
In the screenshot, you can see that I have added bigbang in the timeline. So this should display a tick at that position. 
![screen shot 2016-11-03 at 11 01 53 pm](https://cloud.githubusercontent.com/assets/11655317/19995997/8a010940-a219-11e6-87fc-a3941ec26f87.png)

**Comment by ValentinH** [comment]
Please provide a demo showing exactly what you try to do so I can at least what is your slider configuration.

**Comment by ValentinH** [comment]
Closing as there was no answers for 18 days.
