### ISSUE TITLE
ngRepeat

### ISSUE THREAD

**Issue by ihabadly** [angular-slider/angularjs-slider#444]
Is it possible to use ng-repeat to define an array of sliders all together using ngRepeat?

http://jsfiddle.net/eb548nyw/

**Comment by ValentinH** [comment]
Yes

**Comment by ihabadly** [comment]
Thanks for your kind reply, would you please show me with example or kindly update this:

http://jsfiddle.net/eb548nyw/

**Comment by ValentinH** [comment]
Sorry for not being funny but your slider doesn't show much and is bit even valid JavaScript I think (I'm on the phone right now so can't look at the console...) 

Then using in ng-repeat is definitely possible but depends on what you are trying to achieve. If you want dynamic model values or options or both...

**Comment by ihabadly** [comment]
Sorry for ambiguity, and thanks for your help, kindly find an updated version:
http://jsfiddle.net/eb548nyw/4/

I would like to have both values and options changing dynamically.

**Comment by ValentinH** [comment]
The way you instantiate your sliders is correct but your data structure isn't. You should start by simply du

**Comment by ihabadly** [comment]
The simple ones are working fine with me, only the ones with ngRepeat that have the problem.

**Comment by ValentinH** [comment]
Yes but from what I can see , you are not using ng-repeat correctly: in your dictionary, you have twice the same key. 

You rather use an array like:
```js
[
{value:50, options: {floor: 0, ceil:100}},
{value:100, options: {floor: 0, ceil:200}}
]
```

**Comment by ihabadly** [comment]
Sorry for that, kindly review this:
http://jsfiddle.net/eb548nyw/8/

**Comment by ihabadly** [comment]
Got it to work, thanks:

http://jsfiddle.net/eb548nyw/9/
