### ISSUE TITLE
Ceil bubble shifts to the middle of the slider

### ISSUE THREAD

**Issue by DanielFurmanov** [angular-slider/angularjs-slider#445]
Unfortunately I have no idea what causes it and couldn`t get any consistent set of actions to repeat the issue.

What I was doing before encountering this:
Opening http://angular-slider.github.io/angularjs-slider/index.html scrolling somewhere, 
reading and moving some sliders,
move to some other tabs and apps
return back and saw this 
![bug_report_angular_slider](https://cloud.githubusercontent.com/assets/8160816/19932097/d34484d8-a11f-11e6-9be4-93e9c149f147.jpg)

I have encounter this several times past few days.

**Comment by ValentinH** [comment]
That's interesting, it looks like the issue referenced in https://github.com/angular-slider/angularjs-slider#my-slider-is-not-rendered-correctly-on-load

>## My slider is not rendered correctly on load

>If the slider's parent element is not visible during slider initialization, the slider can't know when its parent becomes visible. For instance, when displaying a slider inside an element which visibility is toggled using ng-show, you need to send an event to force it to redraw when you set your ng-show to true.


It might be due to some optimisation by the browser that would unrender the content and rerender it when the tab becomes active. However, I don't know if there is a way to detect this and force the rerendering of the slider.

**Comment by DanielFurmanov** [comment]
Yeah, its definitely looks like browser fault, because all those days I am working with the slider on my project and did not encounter this issue. Plus I had similar issues with some other sites that stay too long unactive (as a current tab in browser).

I will try to play around with the slider on weekend, for now I believe this issue can be closed, I will reopen it if necessary (if I have some new and important feedback)

**Comment by ValentinH** [comment]
Thanks for you feedback! If you find a way to reproduce it or to solve it, feel free to share ;)
