### ISSUE TITLE
Floor and Ceiling labels not shown as expected with high precision sliders

### ISSUE THREAD

**Issue by jlynde** [angular-slider/angularjs-slider#446]
### Steps to reproduce
1. Set precision to 3 
2. Set step to 0.001
3. Set rightToLeft to true
4. Notice how the number of digits displayed affects whether or not the floor and ceiling labels are visible.  

Demo: http://jsfiddle.net/jlyndesensus/ruwfq48t/7/

### Expected behaviour
I would expect that once there is enough room to display the label it should be displayed.  From that point on, moving the value selector further away should not cause it to be hidden again. 

### Actual behaviour
Notice how the floor label is NOT shown until we move all the way to -1 and then is hidden again when we move to -1.001 even though there is plenty of room to display it.

A similar thing happens on the ceiling side.

**Comment by ValentinH** [comment]
Indeed, I have also noticed this behavior in other examples. I'll take a look when I get some time.

**Comment by ValentinH** [comment]
Also reminder to myself: Remove the `right: 0` on `rz-ceil` added in d19a4dd1d93

**Comment by jlynde** [comment]
Thanks ValentinH!  It probably does not matter now, but I will mention that I tried this with version 5.5.1 and 5.8.1 and found the same behavior with each.  I appreciate the quick response!

**Comment by ValentinH** [comment]
@jlynde this is fixed ;)
