### ISSUE TITLE
Ticks at the left and right ends 

### ISSUE THREAD

**Issue by dongbohu** [angular-slider/angularjs-slider#447]
Is it possible to put the two ticks at the left and right ends at EXACTLY the two ends of the bar? By default the tick at the left end has some offset to the right side, and the tick on the right has some offset to the left side. I customized the CSS by:
```
.rzslider .rz-ticks .rz-tick {
  margin-left: 0px;
}
```
It removes the offset of the tick on left side, but the line of 
```margin-right: 0px;``` 
doesn't seem to affect the tick at the right end.

Thanks.

**Comment by ValentinH** [comment]
The offset reason is because of the slider handle size. If you want the slider handle to be align with ticks, you need this offset currently. Also this is because currently, the handle is left aligned to the slider extremity, but it could be a solution to center it instead.

**Comment by ValentinH** [comment]
This could be a new option to configure the behavior.

**Comment by dongbohu** [comment]
Thank you for your prompt reply. I look forward to the new option.

**Comment by ValentinH** [comment]
Would you like to implement it?

**Comment by dongbohu** [comment]
I prefer not, because I am very busy recently.

**Comment by ValentinH** [comment]
Me too so don't expect it to done soon ;)

**Comment by DeusEx-Machina** [comment]
I would happily add this if you still are wanting this feature implemented.

**Comment by ValentinH** [comment]
Sure! Contributions are always welcome! ;)

**Comment by mtlehtin** [comment]
You can easily achieve this with CSS by reducing the bar width. And then adding left margin accordingly to that change. Needed width change depends on the handle size.

```
.rz-bar {
    width: calc(100% - 2 * 15px);
    margin-left: 15px;
 }
```

**Comment by ValentinH** [comment]
Great answer @mtlehtin .

Just to be sure that the new style is applied after the default ones:
```css
.rzslider .rz-bar {
    width: calc(100% - 2 * 15px);
    margin-left: 15px;
 }
```
