### ISSUE TITLE
Right limit label position error

### ISSUE THREAD

**Issue by kityan** [angular-slider/angularjs-slider#448]
### Steps to reproduce
1. Display slider with visible limits
2. Resize browser window to larger area (larger width)

### Expected behaviour
Right limit label should be always rendererd at the right end of the slider.

### Actual behaviour
If you resize browser window to larger area (larger width) right limit label is not renered at the right end of 
the slider.

**Comment by ValentinH** [comment]
Thanks for reporting. I'm gonna fix it right now! Sorry for the inconvenience.

**Comment by ValentinH** [comment]
Fix released under 5.8.2
