### ISSUE TITLE
Control two sliders with 2 fingers (Android Ionic)

### ISSUE THREAD

**Issue by TurBoss** [angular-slider/angularjs-slider#452]
### Steps to reproduce
1.  run on android device with ionic (native app)
2.  hold and move one slider
3.  hold and move the second slider

Demo: http://codepen.io/TurBoss/pen/bBdVQg

### Expected behaviour
I want to move the two controls simultaneous with 2 fingers

### Actual behaviour
the you hold the first slider it moves nicely but when you hold the second slider with the second finger it moves only the first slider the second never moves

is this even possible?

Thanks!

**Comment by ValentinH** [comment]
I understand what you want to achieve but this is unfortunately not possible with this library.

It would require handing multi touch gestures but I don't even know if it's doable with web technologies.

**Comment by TurBoss** [comment]
thanks for the quick reply
I will search for a joystick or something

**Comment by ValentinH** [comment]
You might want to look into this : http://interactjs.io
