### ISSUE TITLE
maxRange option not applied with pushRange

### ISSUE THREAD

**Issue by GuilloOme** [angular-slider/angularjs-slider#453]
Demo: http://jsfiddle.net/sh49nvLs/

### Steps to reproduce
move the right slider to the right: in one case, it's "blocked" in the other case, nothing append.

### Expected behaviour
We would expect the other handle to follow the first one.

**Comment by ValentinH** [comment]
Well spotted, this is a bug...

**Comment by GuilloOme** [comment]
It looks like it's missing some `this.options.maxRange` logic in [`applyPushRange()`](https://github.com/angular-slider/angularjs-slider/blob/master/src/rzslider.js#L2146)

**Comment by ValentinH** [comment]
Actually, I think that `applyMinMaxRange` should be called after [this line](https://github.com/angular-slider/angularjs-slider/blob/master/src/rzslider.js#L2062).

**Comment by ValentinH** [comment]
Fixed in 5.8.6
