### ISSUE TITLE
Mapping string to integer

### ISSUE THREAD

**Issue by mjknight50** [angular-slider/angularjs-slider#455]
Valentin,
What is the best way to map a string to an integer for a slider?
For example, if I have a bedroom count slider:

```js
 vm.bedroomSlider = {
      value: 1,
        options: {
            ceil: 10,
            floor: 1,
            id: 'bedroomSlider',
            onEnd: vm.bedroomChangeListener,
        }
    };
```

And I want to include "studio" apartments that a value of 'studio' and not an integer.  Is there a way to take advantage of the **translate** function to make this work?  Or perhaps I somehow use **onEnd** to include studio apartments in the results?

**Comment by ValentinH** [comment]
Hi Matthew,

I'm not sure to understand what you want to achieve... If you want to display a slider with discrete values like studioA, studioB, ... you can just use the `stepsArray` option like this:
```js
vm.bedroomSlider = {
  value: 1,
  options: {
    stepsArray: ['studioA', 'studioB', 'studioC'],
    id: 'bedroomSlider',
    onEnd: vm.bedroomChangeListener,
  }
};
```

`stepsArray` is just a shortcut for `translate` so if you want more complex logic, then you can use `translate`.

**Comment by mjknight50** [comment]
Hi Valentin,
I want to have a slider (see attached) that is used for searching for housing.  Right now it allows for a user to select 1-10 bedrooms, but some places are studio apartments.

So, the data set is:
'studio', 1, 2, 3, 4, 5, 6, 7, 8, 9, 10

It works great for the integers, but the 'studio' is what I need to deal with.  
![slider](https://cloud.githubusercontent.com/assets/3513353/20123176/4268baee-a5eb-11e6-8af6-7d258f2eb2d8.png)

**Comment by ValentinH** [comment]
Yes,  `stepsArray` then: http://jsfiddle.net/764vdhL8

**Comment by mjknight50** [comment]
Excellent.  Thanks for your time and help!
