### ISSUE TITLE
Slider extends max-width.

### ISSUE THREAD

**Issue by arkvaale** [angular-slider/angularjs-slider#459]
Hi,

I have set max-width to 50% and added two buttons that increase and decrease the slider value. 
When clicking the increase button the slider sometimes extends the max-width. See image below. The max-width is between the buttons. Slider gets normal when dragging it.
Happens on all screen sizes.

![slider](https://cloud.githubusercontent.com/assets/14953197/20297940/6b9f75ba-ab13-11e6-8b45-f50d28afb48e.PNG)

**Comment by ValentinH** [comment]
Please provide a demo of it because I dont understand what you are doing at the moment...

**Comment by ValentinH** [comment]
Closing as there was no answers for a month.
