### ISSUE TITLE
AngularFullstack Don't show the slider

### ISSUE THREAD

**Issue by HectorRPL** [angular-slider/angularjs-slider#460]
### Steps to reproduce
1. Am using Angular 1.5 [AngularFullstack](http://angular-fullstack.github.io/generator-angular-fullstack/)
2. Am import `$ npm i angularjs-slider`

My component
```
import angularjssslider from 'angularjs-slider';

export class cotizadorComponent {
  constructor($scope) {
    'ngInject';
    $scope.slider = {
      value: 10
    };
}
export default angular.module('ahorrandoMasApp.cotizador', [
  ngMessages,
  angularjssslider
])
```
My html
`<rzslider rz-slider-model="slider.value"></rzslider>`

The slider don't show, only show the value `10`

some ideas?

**Comment by ValentinH** [comment]
Have you included the css file?

**Comment by HectorRPL** [comment]
@ValentinH 
> Have you included the css file?

Wow man, you right!. 
I thought that 'YO generator' doit all for me.
Thanks so much, only I import the css. Thanks again
