### ISSUE TITLE
Custom display of current slider value

### ISSUE THREAD

**Issue by Turv** [angular-slider/angularjs-slider#461]
This isn't an issue, but a query for an Ionic app I am building.

I do not want the current slider value floating to the right of the handle, instead I want it at the top of the slider. You can see an example of what I am trying to achieve on the demo below.

Demo: http://jsfiddle.net/2txyzo3n/2/

I have tried doing a custom template but I seem to be limited to what I can do as I can't change the root element and then everything goes a bit wild if I try and introduce new divs.

I also tried forcing it with position absolute to the top but then I can't centralise it (I.e. simple text-align: center) so as the value increases / decreases it becomes off-centre.

I also noticed that the slider cannot be contained in a div that is text-align center as the handle goes off, I can fix it by changing by adding the below but it's a bit of a hack, any suggestions on how to position the slider centrally within a container div?

```    
.rzslider.rz-vertical .rz-bar-wrapper {
        left: -7px;
    }
```

Any help is appreciated
Thanks

**Comment by ValentinH** [comment]
For your first question, the best would be to completely hide the label and
display the value with a div outside the slider. There is an option to hide
it, I can't access Github right now so you need to look in the
documentation.

For the centering part, I'm not sure to understand how you do it. If you
don't use it already, you should try flexbox which is great for these
positioning issues.

**Comment by ValentinH** [comment]
Closing as there was no answers for months.
