### ISSUE TITLE
Grunt issue when build task is called

### ISSUE THREAD

**Issue by TimmyParkwayd** [angular-slider/angularjs-slider#462]
Hello guys, 
I got an issue this morning, I changed the variables.less file and made a 
    `npm run build`
which went fine, then I made another change and got this on my output console: 

    mbp:angularjs-slider$ npm run build

    > angularjs-slider@5.8.7 build /Users/ibmuser/GitHub/rzSlider/angularjs-slider
    > grunt

    Running "recess:slider" (recess) task
    Fatal error: Operation on an invalid type

Does anybody knows what happened there? Why would it work on the first time then fail?

Thanks in advance !

**Comment by ValentinH** [comment]
Did you change the Gruntfile?

**Comment by TimmyParkwayd** [comment]
I didn't even add a whitespace

**Comment by ValentinH** [comment]
Could you share your changes please?

**Comment by TimmyParkwayd** [comment]
Nevermind, find out. My grunt-cli was outdated, just did a bower update and all good !
Sorry for bothering, and thanks for the fast answer !

Bonne journée :)
