### ISSUE TITLE
When using a function to create the options and setting the slider values in it, the values do not get updated properly all the time

### ISSUE THREAD

**Issue by reckter** [angular-slider/angularjs-slider#463]
### Steps to reproduce
1. Click "click me!"
2. Change the position of the sliders
3. Click "click me!" again. 
4. Nothing changed (This is the bug)
5. If you now click on one of the sliders again, it updates

Demo: http://jsfiddle.net/cwhgLcjv/135/

### Expected behaviour
The slider should watch it's option value and should change accordingly

### Actual behaviour
Only the first time the slider changes correctly, consecutive times, it does not update correctly

**Comment by ValentinH** [comment]
Using a function to return the options is not really a clean way to do it. You should try by using an object that you modify when needed.

**Comment by reckter** [comment]
I found it cleaner because I have fewer fields in my controller, that are just there to transport options around. 
Using a function does make it clearer where the data is coming from opposed to a field, which could be modified by all functions or even come from a different directive. I fixed it with using a field for it though

**Comment by ValentinH** [comment]
It might be cleaner but it's less efficient because angular calls you `getOptions` at each digest cycle which is not really efficient. I can't really tell why it din't work in your case though.
