### ISSUE TITLE
Disabling part of the slider [Feature Request]

### ISSUE THREAD

**Issue by shyamsdmx** [angular-slider/angularjs-slider#465]
Hi,

Can we disable the slider partly , such that based on some condition only part of it is disabled.

Thank you

**Comment by ValentinH** [comment]
Do you mean something like #206?

**Comment by shyamsdmx** [comment]
Yes.

**Comment by ValentinH** [comment]
Then unfortunately not, it is quite complex to implement it but should be feasible. Pull requests are welcome if you are interested.

**Comment by ValentinH** [comment]
Closing it as it is the same than #206

**Comment by shyamsdmx** [comment]
Thanks man, i figured that using minLimit is sufficient for my requirement. :)
