### ISSUE TITLE
Hidden rz-bubble may be a problem in some cases!

### ISSUE THREAD

**Issue by kityan** [angular-slider/angularjs-slider#467]
### Steps to reproduce
1.  Use **hidePointerLabels: true** in options
2.  Use value wich gives **"long strings"** for label. For example, I'have value = **10000000**. 
3.  Use layout where you expect pointer label to be hidden, but it will break layout in some cases. **See demo.**

Demo: http://jsfiddle.net/kityan/ou4417dh/

### Expected behaviour
Size of hidden pointer/limit label should not affect layout!

### Actual behaviour
Size of hidden pointer/limit labels can break layout in some cases. 

---

**Should we use display:none instead of visibility:hidden?** 
Of course, I'll fix it in my project by CSS rules for .rz-bubble, but...

P.S. By the way, thanks for the great module!

**Comment by kityan** [comment]
I can make a pull request if the idea is not bad. But may be there are any reasons to use visibility instead of display, and I can't see them in the case? Sometimes it's true.

**Comment by ValentinH** [comment]
Indeed, using `visibility` is required because when the label is automatically shown/hidden, we need to be able to compute its size (which is not available when using `display: none`.

I understand that in your case this is not what you expect. You can simply add the following rule to your css:
```css
.rzslider .rz-bubble {
  display: none;
}
```
Demo: http://jsfiddle.net/tojtmkbg/

**Comment by kityan** [comment]
Yes, I've already using this CSS fix. But, imho, it's not clear solution :)

**Comment by ValentinH** [comment]
I'm closing this issue since we don't have other solution for this at the moment. And the workaround I've provided is quite easy to use.
