### ISSUE TITLE
Styling the slider

### ISSUE THREAD

**Issue by mikeover** [angular-slider/angularjs-slider#468]
I noticed that all of the examples use the same style for the positions on the slider, those gigantic circles. Is there a way to make them smaller so they look closer to the bootstrap sliders? The handles look absurd on a website with a lot of data and smaller fonts.

**Comment by ValentinH** [comment]
Indeed, I should have examples with different style. The idea is just to update the variables.less file and regenerate the CSS as explain in #235.

**Comment by ValentinH** [comment]
Done.
