### ISSUE TITLE
Decimal Steps

### ISSUE THREAD

**Issue by jamescrowley321** [angular-slider/angularjs-slider#470]
### Steps to reproduce
1.  Assign tick values with a range of decimals
2.  Click on a value
3.  Slider steps to whole number amount step amount despite decimal

Demo: http://jsfiddle.net/ptheczg2/1/

### Expected behaviour
Slider steps to decimal tick

### Actual behaviour
Slider only steps a full integer

Is there any way to override this default behavior?

**Comment by jamescrowley321** [comment]
Please disregard, I missed the step parameter of options!

**Comment by ValentinH** [comment]
`ticksArray` is to display ticks at specific positions that don't necessarily match your values. Then, there is  `stepsArray` that can be used to specify a set a discrete values without having ti deal with floor, ceil or step. 

If I understand correctly your goal, you don't need either of these options, just use ceil, floor, step and precision: http://jsfiddle.net/an7d8kmh/
