### ISSUE TITLE
Fix tick placement for some legacy browsers

### ISSUE THREAD

**Issue by evanmcallaway** [angular-slider/angularjs-slider#472]
Some legacy browsers do not position tick labels correctly because they require the prefixed version of the transform rule but otherwise work fine.  My primary target is Chrome 34 because some folks still use it for NPAPI support.  I propose adding a mixin that automatically adds all the prefixed transform rules for us.

I've forked, made the change, and tested.  Good to open a PR?

**Comment by ValentinH** [comment]
Yes why not. I have also used a PostCSS plugin to prefix all the stuff that can be integrated in the Grunt pipeline. It might be easier to maintain don't you think?

**Comment by evanmcallaway** [comment]
Automatic prefixing sounds like a win to me.

In either case we also need to modify the transform style that we're adding in updateTicksScale() to include prefixes.

**Comment by ValentinH** [comment]
Indeed, I forgot the `updateTicksScale` part... It will be more complicated to handle all the prefix for it.

**Comment by ValentinH** [comment]
Fix released via 5.8.9

**Comment by ValentinH** [comment]
Tell me if it fixes your issue. I wasn't able to add prefix to the `updateTicksScale` function because it seems that `ng-style` automatically drops the prefix.

**Comment by evanmcallaway** [comment]
Hmm...unfortunately `updateTicksScale` was the one that was really killing us.  It's a bit verbose, but we are currently fixing it by doing the following:

```
         this.scope.ticks = ticksArray.map(function(value) {
           var position = self.valueToPosition(value);
 
            if (self.options.vertical)
              position = self.maxPos - position;
  
 +          var translation = translate + '(' + Math.round(position) + 'px)';
            var tick = {
              selected: self.isTickSelected(value),
              style: {
 -              transform: translate + '(' + Math.round(position) + 'px)'
 +                '-webkit-transform': translation,
 +	              '-moz-transform': translation,
 +	              '-o-transform': translation,
 +	              '-ms-transform': translation,
 +	              'transform': translation
              }
            };
```

Which seems to do the job.

**Comment by ValentinH** [comment]
That's weird because when I tried that, ng-style was simply adding the 'transform' property without the prefixed version? Does this mean that it depends on the browser where it gets executed?
