### ISSUE TITLE
Import errors when there both rzslider.css and rzslider.scss in dist folder

### ISSUE THREAD

**Issue by orochies** [angular-slider/angularjs-slider#477]
I recently cloned my project to a system with macOsx all fine until I ran the command:

>sudo npm install

And I see a bug related to sass:

Message:
    src/scss/index.scss
Error: It's not clear which file to import for '@import "node_modules/angularjs-slider/dist/rzslider"'.
       Candidates:
         node_modules/angularjs-slider/dist/rzslider.scss
         node_modules/angularjs-slider/dist/rzslider.css
       Please delete or rename all but one of these files.
        on line 26 of src/scss/index.scss
>@import "node_modules/angularjs-slider/dist/rzslider"; // explicit extension o

In my src/scss/index.scss:
>@import "node_modules/angularjs-slider/dist/rzslider";

related info: https://github.com/sass/node-sass/issues/1222

I see that it is related to its wonderful module and I come to check version changes and I find a change that says:

>5.8.3 (2016-11-03)
>Improvement
>Generate a SCSS file (simple copy of the css file) in the dist folder so it can be imported (# 449)

-When clone and install angularjs-slider update to v5.8.7 
-in the main project (Windows 8) have angularjs-slider v5.5.0

ok v5.8.3 is my problem, solution install v5.8.2 but i lost the last improvements.

Can you move rzslider.scss to src folder?

Thanks.

**Comment by ValentinH** [comment]
Actually, I didn't really want to add a .scss version of the .less file... Having it in the src file isn't find either. I think that I will simply remove it, would it fix your issue?

**Comment by orochies** [comment]
Yes that will solve my problem, I can update to v5.8.2 without incident.

Look this: https://github.com/sass/libsass/pull/754

**Comment by ValentinH** [comment]
I have contacted the person who did the change to see if your solution could match hee needs.

**Comment by ronnyrin** [comment]
You can easily resolve this issue by specify the extension:
`@import "node_modules/angularjs-slider/dist/rzslider.scss`

**Comment by orochies** [comment]
Okay, I upgraded to 5.9.0 and I've explicitly added the .scss extension on the import line of my index.scss file and now it works on win8 and mac.

In http://sass-lang.com/guide section import say:

> When you import a file you don't need to include the file extension .scss. Sass is smart and will figure it out for you. When you generate the CSS you'll get.

I think in these cases if you have to be explicit.

Thanks.

**Comment by varunwinni** [comment]
Hi All, I am implementing Rzslider for time range But I am facing some issues. And I already ask in stackoverflow Please look at this. https://stackoverflow.com/questions/45429746/dont-lose-previous-position-of-rzslider-after-select-the-date-in-angular-js?noredirect=1#comment77835931_45429746

**Comment by ValentinH** [comment]
Please don't pollute all the previous issues thread.
