### ISSUE TITLE
should not allow range slider pointer on same tick value

### ISSUE THREAD

**Issue by upender15** [angular-slider/angularjs-slider#478]
### Steps to reproduce
1. Take a range slider with ticks and drag pointer and drop on another pointer.
2. 
3. 

Demo: http://jsfiddle.net/upender15/j1ww66ep/3/ 

### Expected behaviour
Range slider should not allow pointers on same tick value.

### Actual behaviour
Range slider is both pointers can be placed on same tick value.

**Comment by ValentinH** [comment]
You can use the minRange version for this.

**Comment by upender15** [comment]
Thanks that worked.
