### ISSUE TITLE
Allow negative number and fractional step

### ISSUE THREAD

**Issue by priscilacng** [angular-slider/angularjs-slider#480]
I have a situation that I need a negative min value and a fraction step (0.25), are you guys thinking about it?

Thanks

**Comment by ValentinH** [comment]
Like this: http://jsfiddle.net/w9nt8d4e/ ?

**Comment by priscilacng** [comment]
Yes! For some reason with the latest version of the slider, it always started at 0.
Also I didn't find an example in the documentation, I thought it wasn't possible.
Anyway, thanks!

**Comment by ValentinH** [comment]
What do you mean by the latest version?

**Comment by priscilacng** [comment]
I installed with bower.. and every try that I've made it always started at 0 :(

**Comment by ValentinH** [comment]
You are still having everything starting from 0?

**Comment by priscilacng** [comment]
Nope, I've copied your example and now it's working! 😳  thank you
One last question, I needed a step of 0.25, but it seems it rounds the number, is it correct?

**Comment by ValentinH** [comment]
You need to increase the precision option.

**Comment by priscilacng** [comment]
Thank you so much 😊
