### ISSUE TITLE
Demo site not up to date

### ISSUE THREAD

**Issue by Masadow** [angular-slider/angularjs-slider#481]
Hi Valentin,

I saw that my PR has been accepted, but the demo site http://angular-slider.github.io/angularjs-slider/ has not been updated accordingly. (I've added some examples)

My collaborator could see it live :)

**Comment by ValentinH** [comment]
Indeed, I didn't get the time to do it yet. If you want, you can do it by editing the gh-pages branch and submit another PR. ;)

**Comment by ValentinH** [comment]
Demo site updated ;)
