### ISSUE TITLE
TicksArray and StepsArray in conjunction doesn't display ticks or values

### ISSUE THREAD

**Issue by slarson62** [angular-slider/angularjs-slider#482]
### Steps to reproduce
In live code examples setting ticksArray and stepsArray fails to display ticks or values:

//Slider with ticks and values
    $scope.slider_ticks_values = {
        value: 25,
        options: {
            ceil: 100,
            floor: 0,
   	    ticksArray: [0, 10, 25, 50, 100],
            stepsArray: [0, 10, 25, 50, 100],
            showTicksValues: true
        }
    };

### Expected behaviour
Ticks and values should display

### Actual behaviour
Ticks and values are not displayed

**Comment by ValentinH** [comment]
You should not use ticksArray in that case..

**Comment by slarson62** [comment]
Thanks for the quick reply. That solves it.
