### ISSUE TITLE
The ends of the slider are not populated properly

### ISSUE THREAD

**Issue by rishabhmhjn** [angular-slider/angularjs-slider#484]
When we load the page sometimes, the 2 way slider is not drawn properly

### Steps to reproduce
1. Add a 2 way slider and redraw the block with slider using change in `ng-if`

### Expected behaviour
![screenshot 2017-01-04 16 58 25](https://cloud.githubusercontent.com/assets/1336602/21641050/38b151a6-d29f-11e6-94ce-dbdb757e7ae5.png)

### Actual behaviour
![screenshot 2017-01-04 16 55 36](https://cloud.githubusercontent.com/assets/1336602/21640997/e8778886-d29e-11e6-98cd-f9f390fcef64.png)

**Comment by ValentinH** [comment]
Probably this: https://github.com/angular-slider/angularjs-slider#my-slider-is-not-rendered-correctly-on-load

**Comment by rishabhmhjn** [comment]
I fixed this issue with that code.
Thank you @ValentinH 

Now I have another problem with sliders.
Will submit a new issue.

Closing this one.
