### ISSUE TITLE
$scope.$broadcast('rzSliderForceRender') is very slow in Firefox & IE

### ISSUE THREAD

**Issue by rishabhmhjn** [angular-slider/angularjs-slider#485]
In continuation with #484, the initial as well as force rendering of sliders on Firefox and IE is very slow. (works great on Chrome, Opera and Safari)

When it takes just some milliseconds to render a few sliders together in Chrome, it takes nearly 10 times more time to render in Firefox and IE.

Related Firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=983465

**Comment by ValentinH** [comment]
Do you still have the issue?
