### ISSUE TITLE
rzModule is not descriptive of what this thing does

### ISSUE THREAD

**Issue by johnculviner** [angular-slider/angularjs-slider#486]
Generally I'd expect to see a module name like 'rzSlider' or 'ngSlider' but 'rzModule' likely throws most of your users for a loop as to what the dependency does (especially since the filename is rzslider.js even) that is being imported (other than the person that added it perhaps...)

You could could make a new module called 'rzSlider' or something wrapping the other one to change the name if you wanted without breaking anything for people.

My 2 cents feel free to close the issue if you don't think it matters. Thanks for making this, quite nice!

**Comment by ValentinH** [comment]
Actually I totally agree! It was also weird to me when I started maintaining this library and I got used to it.  I think that rzSlider is a good candidate for it even if there is also a service named like that in the library.

**Comment by johnculviner** [comment]
Cool! i think doing 

```angular.module('rzSlider', ['rzModule'])```

Could be a nonbreaking fix for it (and updating the docs). Maybe next time you make a change or something? Thanks!
