### ISSUE TITLE
Feature request - Date Range Slider

### ISSUE THREAD

**Issue by jlynde** [angular-slider/angularjs-slider#488]
### Feature Request
Could you add a Date Slider that allows the user to choose a range of Dates?  For example: From Jan 1, 2015 to Jun 30, 2015.  Now that you have support for Date Slider, this seems like a logical next step and we already have a use for such a thing in our project.

Thanks,
John Lynde

**Comment by ValentinH** [comment]
It's already possible with the current options. The is even a demo for it I think.

**Comment by jlynde** [comment]
Yes, you are correct.  I did not see a demo with a date range, but it does, in fact, work.  Thanks!
