### ISSUE TITLE
Feature request - Render html in tooltip box

### ISSUE THREAD

**Issue by maxkuzmin** [angular-slider/angularjs-slider#489]
Hello.

It seems like currently it is not possible to render html via ticksTooltip. However, it would be very useful in some cases (In my case I need to render image). I can make PR with this feature if you consider this appropriate.

Thanks.

**Comment by ValentinH** [comment]
Hi.

Does bootstrap support ticks with HTML?

**Comment by maxkuzmin** [comment]
https://angular-ui.github.io/bootstrap/#/tooltip

> - `uib-popover-html` $ - Takes an expression that evaluates to an HTML string. Note that this HTML is not compiled. If compilation is required, please use the `uib-popover-template` attribute option instead. _The user is responsible for ensuring the content is safe to put into the DOM!_
> - `uib-popover-template` $ - A URL representing the location of a template to use for the popover body. Note that the contents of this template need to be wrapped in a tag, e.g., `<div></div>`.

**Comment by ValentinH** [comment]
Indeed, you are right. If you want, you can submit a pull request :) On my side, I'm not active anymore on this project but I can advise you if you want...

**Comment by trodi** [comment]
@maxkuzmin I had to add this functionality on the ticksValuesTooltip recently to my wrapper of this slider. Although it would be ideal if it was built into the slider itself, here's how I got it working without any code changes necessary.

* Use `rz-slider-tpl-url` to specify your own template
* The `customTemplateScope` option allows you to add to the scope inside the template. Therefore you can specify the templateUrl for your fancy tooltip (I called mine `ticksValuesTooltipTemplate`).
* Modify your copy of the template
  * add the `uib-tooltip-template` attribute.

```html
<span ng-if="t.value != null" class="rz-tick-value"
          ng-attr-uib-tooltip-template="custom.ticksValuesTooltipTemplate || undefined"
          ng-attr-tooltip-append-to-body="true"
          ng-attr-tooltip-placement="{{t.valueTooltipPlacement}}">{{ t.value }}</span>
<span ng-if="t.legend != null" class="rz-tick-legend">{{ t.legend }}</span>
```

**Comment by ValentinH** [comment]
Closing as there was no answers for more than a month.

Also @trodi provided a nice workaround. :smile:
