### ISSUE TITLE
rzslider would update UI when rz-slider-model updated from controller

### ISSUE THREAD

**Issue by jackey** [angular-slider/angularjs-slider#494]
At first time page loaded, i set default model value to rz-slider, like
$scope.formdata = {
  maxAge = 30 // init 
};

// html: <rz-slider rz-slider-model="formdata.maxAge" /> 
the UI and function works well. But when update $scope.formdata.maxAge with ajax returnd data, the rz-slider UI still keep default value (30) not the really value from server side. 

Do you guys meet this problem too ? how to fix it ??

**Comment by jackey** [comment]
for now, i try to fix it with update 
```
resetSlider: function () {
 // add it at top of fucntion 
this.applyOptions();
//...
};
```
it works well now

**Comment by ValentinH** [comment]
You don't need to patch the library for this, what you do looks pretty common. What is the html part of your slider (where you set `rz-slider-model`)?

**Comment by jackey** [comment]
@ValentinH 
At begin of page init, the rz-slider-model was set as default value (like i posted in issue ). as soon as page loading was finished , i call server to set new rz-slider-model value.  something like that: 
```
getMaxAge().then(function (res) {
  $scope.formdata.maxAge = res.data.max_age;
  $scope.$broadcast('rzSliderForceRender'); // force to re-render slider because we have new value.
});
```

i checked rz-slider source code and it listens on rzSliderForceRender event to force rz-slider re-render. 
the problem is coming,  the setMinAndMax() function still using old options.ceil value to calculate min and max value. So that options.ceil should be re-caculated when rzSliderForceRender() event happened.

**Comment by ValentinH** [comment]
But what is the value of the options object?

**Comment by jackey** [comment]
@ValentinH 

[here](https://github.com/angular-slider/angularjs-slider/blob/master/src/rzslider.js#L556)

**Comment by ValentinH** [comment]
I mean: what values do you provide to it?

**Comment by ValentinH** [comment]
There: `rz-slider-options="slider.options"`

**Comment by jackey** [comment]
the value is : 
```
$scope.slider = {
  options: {
       precision: 1,
       step: 0.1
  }
};
```

**Comment by ValentinH** [comment]
You need to set floor and ceil! ;) Floor defaults to 0 so it's probably OK but ceil defaults to the first value of the slider so that's why it didn't change after...

**Comment by jackey** [comment]
Great,   it's working ! Amazing , thank you :+1:

**Comment by ValentinH** [comment]
Great, have fun ;)
