### ISSUE TITLE
How do I pass an array of objects to stepsArray and manipulate it?

### ISSUE THREAD

**Issue by GeorgeChackungal** [angular-slider/angularjs-slider#495]
I had an requirement of sendingan rray of custom objects and show the labels and selection based on it. Anyway I can do it? when I send the objects everything is coming undefined.

**Comment by ValentinH** [comment]
Please provide a JSFiddle showing what yo uare trying to do. Also, `stepsArray` has examples on the demo site.

**Comment by GeorgeChackungal** [comment]
Hi,

To reiterate,

I am passing an array of objects to the stepsArray where the value is time. This works fine and I get the date as modelvalue. what I would like to get is the entire object itself on the onchange event.

thanks,
George

**Comment by ValentinH** [comment]
This is not possible, the onChange only receives the value item of the object.
