### ISSUE TITLE
Handle Detachment

### ISSUE THREAD

**Issue by CatLHR** [angular-slider/angularjs-slider#496]
Can you make the handle of the rzslider detachable in any way?

**Comment by CatLHR** [comment]
Okay, I guess I need to give more context - I'm trying to have a draggable handle so that the user can drag the handle onto the slider, snap into place (a default value with persuade the user in some way, so if they can start the value themselves in a cool way, that's the goal), hence draggable.

I'm trying to remove the handle so that I can have a different element drag and then once dropped in the zone, the handle appears close to where the user dragged to.

Is there any way to detach the handle and possibly make that move rather than having to go through all of this??

**Comment by ValentinH** [comment]
What you are trying to achieve is really specific and can't be handle via this library. There is no reason to be able to remove a handle from a standard slider, thus, what you want is not a standard one.

You will need to wrap this library in a custom directive that would do what you want pretty "manually"; hiding the handle at the beginning, detecting a drop on top of  the slider, etc...

**Comment by CatLHR** [comment]
Okay so I figured it all out - I just need to refresh the slider but 
$timeout(function () {
            $scope.$broadcast('rzSliderForceRender');
        });
refreshes it to the value set in the javascript, whereas I would like it refreshed to the place the handle shows up initially after, just with the value instead of having to click three times on the same spot...possible?

**Comment by ValentinH** [comment]
The concept of Angular is to link data to the DOM. Thus, if you want the slider to display its handle at a specific position, you need to set the data to the value corresponding to that position.

**Comment by CatLHR** [comment]
How would you correspond position to value? Other than having a very intricate array or ifelse statement

**Comment by CatLHR** [comment]
I figured I'll simulate a mouse click instead, that's far easier and less work. But thanks for letting me bounce ideas off of you - truly helps :D

**Comment by CatLHR** [comment]
Is there any way to translate in pixels?

**Comment by ValentinH** [comment]
You need to compute the pixels position yourself for this purpose. You can get some clues my reading the library methods that set value from pixels or pixels from values ;)

**Comment by ValentinH** [comment]
They are called `valueToPosition` and `positionToValue`. ;)

**Comment by CatLHR** [comment]
Hey Sorry to bug you, one last thing - do you have a simple example of using ng-change? I have an ng-repeat with ng-model, but teh function i want to call with ng-change is not working even to console log a simple item. Thx
