### ISSUE TITLE
Formatting of values

### ISSUE THREAD

**Issue by myGitHubForum** [angular-slider/angularjs-slider#497]
### Steps to reproduce

Attached is the screenshot.

![filters](https://cloud.githubusercontent.com/assets/8227363/22752715/304cfca6-edff-11e6-924e-44f43045d452.png)

### Expected behaviour
I have requirement to reduce the circle size and also the fonts (reduce) of the scroll bar. I am able to modify the fonts using external css but the Floor and Ceil values are not able to modify as it uses the position - getDimension() which I am not able to call/use from my application. 

The Ceil Value is going out of the sceen. I need to position left

How can I get the handle or object of rzslider object to do some custom edits to the slider?

### Actual behaviour
The fonts are too large for my requirement and also the size of circle is too big.

**Comment by ValentinH** [comment]
You don't have to call `getDimension`. There is an example on the website showing how to create a custom style: this is what you need.

**Comment by ValentinH** [comment]
Closing as there was no answers for 25 days.

**Comment by myGitHubForum** [comment]
Can you direct me to the example? Thanks.

**Comment by ValentinH** [comment]
![image](https://cloud.githubusercontent.com/assets/2678610/23861955/f92242be-080b-11e7-8c0d-4c56d0af87d0.png)

**Comment by ValentinH** [comment]
http://angular-slider.github.io/angularjs-slider/

**Comment by myGitHubForum** [comment]
Can you provide me the code sample?

**Comment by ValentinH** [comment]
![2017-03-23t17 39 27 678z](https://cloud.githubusercontent.com/assets/2678610/24261713/290bbf5c-0ff8-11e7-8e8a-0142a4dfb784.gif)
