### ISSUE TITLE
NPM build fails: require is not defined

### ISSUE THREAD

**Issue by returnvoid** [angular-slider/angularjs-slider#503]
### Steps to reproduce
1. Install with NPM
2. include js
3. register module

The previous version was working perfect but stopped working after new release

Error: [$injector:modulerr] Failed to instantiate module rzModule due to:
Error: [$injector:nomod] Module 'rzModule' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

thanks

**Comment by ValentinH** [comment]
What was the last working version?

**Comment by returnvoid** [comment]
6.0.0

**Comment by ValentinH** [comment]
Do you still have the issue with 6.1.0?

**Comment by returnvoid** [comment]
Hi There, I haven't tried it again

**Comment by ValentinH** [comment]
OK, I'm closing it for now then. If you encounter the issue again, please re-open it :)
