### ISSUE TITLE
Slider with step is rounded over the ceil

### ISSUE THREAD

**Issue by OldrichKruchna** [angular-slider/angularjs-slider#506]
### Steps to reproduce
1. Set slider step to 10 and ceil to 106 (for 104 it works)
2. Drag pointer to the max value of the slider
3. Actual value is randomly rounded to 106 or 110

Demo: https://jsfiddle.net/escapedcat/22sjbdkz/1/

### Expected behaviour
Expected behaviour is that the last two steps of the slider are 100, 106.

### Actual behaviour
Actual behaviour is that the last two steps of the slider are 100, 106 or 110 (probably model value is rounded based on the step without respecting the ceil value).

**Comment by miguelrincon** [comment]
I can reproduce this issue. 110 is visible in the fiddle.

**Comment by ValentinH** [comment]
Indeed, this behavior is weird. However, your `floor` and `ceil` values should match de `step` which is not the case in your example.
