### ISSUE TITLE
my range sliders  circle position work correctly only after launching browser inspect element or after first click on the  blue circle

### ISSUE THREAD

**Issue by abomusab** [angular-slider/angularjs-slider#507]
I have problem when angularjs-slider is appear for the first time 

my range sliders only work after launching browser console or first click on the  blue circle

the position is not correct it start from 0 even if the value is 0 or 5 or 10 

after i click on it it will go to the correct position or if i open the inspect element to check the problem it will work too 

any idea ? ? 

my code : 

      $scope.Lang = {
         Reading: 10,
        Writing: 10,
        Speaking: 10,
        options: {
            showSelectionBar: true,
            getSelectionBarColor: function (value) {
                if (value <= 2)
                    return 'red';
                if (value <= 4)
                    return 'orange';
                if (value <= 7)
                    return 'yellow';
                return '#2AE02A';
            }
        }
      };
and the html code 

         <rzslider rz-slider-model="Lang.Writing"
                                              rz-slider-options="Lang.options"></rzslider>

image  of the problem : 
https://image.ibb.co/nfCwov/Capture.png

what i expect is 

https://image.ibb.co/n3V5gF/Capture.png

**Comment by ValentinH** [comment]
https://github.com/angular-slider/angularjs-slider#my-slider-is-not-rendered-correctly-on-load
