### ISSUE TITLE
NG-Model & NG-Change

### ISSUE THREAD

**Issue by CatLHR** [angular-slider/angularjs-slider#508]
Is there any way to have the rz-slider use an ng-change & ng-model?

I'm using an ng-repeat and need a function called when the value of the slider is being changed with the index of the object passed through to the function. 
rz-slider-on-change does not work for my purposes either.
Since I can't bind a div with the value dynamically,  I am in need of your assistance.

**Comment by ValentinH** [comment]
No there is no way to do that.

However, the best way to achieve what you want is to create a directive that wrap the slider library and exposes 2 bindings: `model` and `on-change`.

**Comment by ValentinH** [comment]
Demo of what I mean: http://jsfiddle.net/prhtbpqx/ :wink:

**Comment by CatLHR** [comment]
Is there anyway to have it dynamic for each slider - like have the output for one slider tied to just that slider and not be updated for all? 

I know how to do the change all values one, but I'd like it individual for each slider.

Thanks for the example though, super cute.

**Comment by CatLHR** [comment]
Kidding got it lol thanks tho :D Super helpful

**Comment by ValentinH** [comment]
So everything's fine? Can I close the issue?

**Comment by CatLHR** [comment]
Wait no - how do i change a value of a string linked to the value of the slider? but only show up per slider

**Comment by CatLHR** [comment]
You can close it - i figured it out. 
Why aren't we allowed to use ng-change and ng-model? This is such a roundabout

**Comment by ValentinH** [comment]
This is because this is not a default Angular directive. We could have use ng-model  but since the slider can be a range one (with 2 handles), we would need to ng-model attrs.
