### ISSUE TITLE
Different colors for selection bar within ticks

### ISSUE THREAD

**Issue by AnurudhaNagarajan** [angular-slider/angularjs-slider#509]
We are using this component for our development and trying to show different colors for selection bar within ticks 

eg
![selectionbarexample](https://cloud.githubusercontent.com/assets/18552273/23886284/c8eab178-089f-11e7-9de4-c0366d1e434e.PNG)

Is there any ways to do this in the existing component or could this be added to the component

**Comment by ValentinH** [comment]
If the color doesn't need to change at finding, you can override the color version by setting a CSS file with the !important modifier. Otherwise, this is not possible.
