### ISSUE TITLE
using rz-slider with mongoose fails

### ISSUE THREAD

**Issue by robertlight** [angular-slider/angularjs-slider#510]
We are trying to use rz-slider with mongoose objects as the values for rz-slider-model & rz-slider-high

Our rz-slider works fine when we have

TRY#1  (works)
<rzslider id="attenuationSlider" class="attenuatorSlider"
                             rz-slider-model="myLowV"
                             rz-slider-high="myHighV"
                             rz-slider-options="attenuatorRangeSliderOptions" ></rzslider>

but when I do it this way:
TRY#2  (fails)
<rzslider id="attenuationSlider" class="attenuatorSlider"
                             rz-slider-model="**_config.distance.start_**"
                             rz-slider-high=**_"config.distance.stop_**"
                             rz-slider-options="attenuatorRangeSliderOptions" ></rzslider>

where **_$scope.config_** is a mongoose document object... then my entire page gets screwed up.
If I revert it to TRY#1 and define $scope.myLowV=10;  $scope.myHighV=30
... the entire page displays properly.

It seems like the TRY#2 is causing angular to stop processing properly on the page.

**Comment by ValentinH** [comment]
I think you forgot some information in your issue. I don't see TRY#1.

**Comment by robertlight** [comment]
good point..... it stripped out my "&lt;" and "&gt;" tag stuff:
TRY#1
`
<rzslider  rz-slider-model="config.distance.start"  rz-slider-high="config.distance.stop"  rz-slider-options="attenuatorRangeSliderOptions" ></rzslider>
`

**# SOLUTION**:
We did find the problem and the solution and it does seem to be somewhat of a problem with rzslider and it's initialization mechanisms.

I had to use the following html to get things to work properly:
`
<rzslider    ng-if="configReady"  
                                         rz-slider-model="config.distance.start"
                                         rz-slider-high="config.distance.stop"
                                         rz-slider-options="attenuatorRangeSliderOptions" ></rzslider>
`

where I set $scope.configReady=true after the config object has been loaded and fully initialized.  Otherwise, the existence of the rzslider accessing somewhat uninitialized or partially initialized data causes angular layout to croak on the entire page.
`
<rzslider ng-if="configReady"  
                                         rz-slider-model="config.distance.start"
                                         rz-slider-high="config.distance.stop"
                                         rz-slider-options="attenuatorRangeSliderOptions" ></rzslider>
`

If I just use:
`
<rzslider ng-if="config && config.distance"
                                         rz-slider-model="config.distance.start"
                                         rz-slider-high="config.distance.stop"
                                         rz-slider-options="attenuatorRangeSliderOptions" ></rzslider>
`
The initial layout of the slider has both slider ends set at "0" and only after the user clicks on one of them do the sliders jump to the current values of config.distance.start/stop.

**Comment by ValentinH** [comment]
Indeed, if one value of the slider is undefined or null on load, then the initialization is not done properly. You could also try to force the refresh when your config is ready, by broadcasting the `rzSliderForceRender` event on the scope.

**Comment by robertlight** [comment]
The only real way I was able to solve this was with the ng-if="configReady" construct.   If the rzSlider is built/initialized with bad, uninitialized data - it screws up angular to the point where the rest of the page mysteriously does not render properly.

I would still put this in the category of a "bug" since it has such broad effect outside of the control itself.  

I would recommend that you put a try-catch around the evaluation of rz-slider-model and rz-slider-high and if you get an exception - you then default the thumb controls to the min/max of the control and put out an error message informing the programmer that he's feeding unitinialized data to your control.   This would obviate the need for the "ng-if" use above and would result in much more localized and stable behavior.  The broadcasting of rzSliderForceRender could then be done when the data became available to safely access rz-slider-model and rz-slider-high.

**Comment by ValentinH** [comment]
What exception is fired?

**Comment by robertlight** [comment]
I don't think there was any exception that I saw... angular probably caught it and that's where the trouble began as angular then proceeded to not render the rest of my page.

I wouldn't claim that it was a bug in your code except that it occurred when we first inserted our first instance of rzslider and the bug was very mysterious (and silent !!).   If I had a page with lots of controls, including rzsliders and then for whatever reason the fact that my model wasn't completely defined and all of a sudden angular started misbehaving... I would have no clue that the problem resided with rzslider - that is why I think if you surround the elements of your code which access the model values and just peg the thumbs to the min/max and put out an error message...that's about as good as you can get.  You've given the programmer a hint at what went wrong and at the same time, you didn't participate in angular's demise in laying out the whole page.
