### ISSUE TITLE
Slider does not respond on android devices

### ISSUE THREAD

**Issue by netzaffin** [angular-slider/angularjs-slider#512]
### Steps to reproduce
1. [Demo](https://app.tomvote.com/answer-demo/92d20eeae89c8d31fd199fdfaa60522f)
2. Open with Google Chrome (56.0.2924.87) @ Android (6.0.1)

### Expected behaviour
Slider responds while dragging the bubble and sliding on the bar

### Actual behaviour
Slider does not respond.

The slider works with Firefox on Android, Safari on iOS, Desktop, ... - only some Chrome versions have trouble. I've made a [video](https://www.dropbox.com/s/85r9atp1tnxah9v/125514903691808951968916819.mp4?dl=0).

This is related to [an old issue](https://github.com/angular-slider/angularjs-slider/issues/10). When I change jQuery and angular JS, it seems to work. But it results in many errors, since we expect to jQuery load first. It might be an option to change, but will result in many changes and debugging.

**Comment by ValentinH** [comment]
Could you please set up a minimal example reproducing the issue on JSFIddle so I can be sure that nothing else is the source of the issue?

**Comment by netzaffin** [comment]
I've found the problem while working on it: The use of [perfect-scrollbar](https://github.com/noraesae/perfect-scrollbar) made the slider unresponsive. Changing jQuery and AngularJs load order caused the perfekt-scrollbar to be not perfect anymore.

So this is not your specific problem and I will lookup how I can solve it.

Thanks for this plugin, it's really a good thing.
