### ISSUE TITLE
Vendor prefix for transform

### ISSUE THREAD

**Issue by bod1ka** [angular-slider/angularjs-slider#516]
### Steps to reproduce
1. Use some browser that requires vendor prefix for transform property  
2. Use vertical slider with ticks

Demo: http://jsfiddle.net/yra7skru/1/

### Expected behaviour
All ticks being aligned correctly

### Actual behaviour
Ticks being squashed

**Comment by ValentinH** [comment]
What browser has an issue? Because we have prefix for old browsers but maybe not that old: https://github.com/angular-slider/angularjs-slider/blob/master/dist/rzslider.css#L242

**Comment by bod1ka** [comment]
Safari 600.1.4 on iPad
Not sure how this line in css could help with the issue.
There is a line 993 in dist/rzslider.js where the transform property is set dynamically.
So I suppose prefixes should also be added there.

**Comment by bod1ka** [comment]
You could even open this page with examples on this browser and see the issues with vertical ticks
http://angular-slider.github.io/angularjs-slider/index.html

**Comment by ValentinH** [comment]
Sorry I forgot this part of the code. I thought a PR already submitted a fix for this, I don't remember why it wasn't merged...

**Comment by ValentinH** [comment]
OK that was the issue: https://github.com/angular-slider/angularjs-slider/issues/472

I have tried to fix that but noticed that this was handled directly by `ng-style` so  I couldn't manually add the prefixes...

**Comment by bod1ka** [comment]
I have read ng-style source code.
It doesn't handle prefixes it just calls jqlite css method
https://github.com/kiltjs/jqlite/blob/master/jqlite.js#L1166
Which doesn't strip anything either.
So that fix in #472 will work.

The reason why prefixed props doesn't appear is browser itself.
If you do something like:
`
var element = document.querySelector('random-id');
element.style['-webkit-transform'] = 'translateX(50px)';
`
the style property will show only transform

**Comment by bod1ka** [comment]
I have checked the source code for ng-style.
It doesn't do anything with prefixes , it just calls jqlite css method.
Which doesn't remove them either.
To simplify all it does is:
- Convert name to camelCase ('-webkit-transform' becomes 'webkitTransform')
- Set style for element
So the suggested fix in #472 will work

**Comment by ValentinH** [comment]
Could you provide a pull request for this?

**Comment by ValentinH** [comment]
Fixed in 6.1.1
