### ISSUE TITLE
I want to give only one tick in the middle of slider that can show legend in text form not in numeric, my slider has two pointers in it and i want to use that with moment js

### ISSUE THREAD

**Issue by saini0011** [angular-slider/angularjs-slider#517]
### Steps to reproduce
1. 
2. 
3. 

Demo: http://jsfiddle.net/cwhgLcjv/ (fork this example and update the link)

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by ValentinH** [comment]
The purpose of an issue template is to be a template, not the content. Please provide more details. :smile:
