### ISSUE TITLE
How to let the rzslider talk with other directives?

### ISSUE THREAD

**Issue by anuragkalia** [angular-slider/angularjs-slider#519]
I am writing a generalized directive which disables input fields (checkbox, text field,rzslider etc.) depending on some condition. Now, ng-disabled or ng-model does not work on rzslider. It works through the options object of rzslider.

Had rzslider's controller existed and options object were available on said controller, it would have been trivial to change the disabled attribute. I could have simply 'require'd rzslider inside my general directive and change the disabled property from there.

So is it feasible to provide options through controller rather than directly attaching it to scope?

**Comment by ValentinH** [comment]
The thing is the library doesn't use a controller but directly the link function of the directive. I'm not the one who initiated this directive and I have to admit that it looked weird to me at the beginning. Now, I don't know how to handle what you mean with the controller part...
