### ISSUE TITLE
Slider behaving unexpected with disable option

### ISSUE THREAD

**Issue by jerry9249** [angular-slider/angularjs-slider#520]
Step to Reproduce 👍 
https://share.viewedit.com/udNMeTbi9GJVHMUHPMFkGy

### Expected behaviour

it gives range instead of one value

### Actual behaviour

Client need one value only and disable option gives range

**Comment by ValentinH** [comment]
I only see this issue when opening the devtools while dragging. Thus, it is the same issue as the one in #476.
