### ISSUE TITLE
Slider freezes on touch in mobile browsers when jQuery version is bigger than 2.2.1

### ISSUE THREAD

**Issue by AlexandrSargsyan** [angular-slider/angularjs-slider#521]
### Steps to reproduce
1. Update jQuery from 2.2.1 to higher
2. touch on slider in mobile browsers 

### Expected behaviour
Must get true value according slider position

### Actual behaviour
Slider gets to right , value gets undefined and freezes no more actions to take

**Comment by ValentinH** [comment]
Could you please provide a demo of the issue? 

Here are 2 demos with jQuery higher than 2.2.1 and there is no issue on Chrome on Android:
- jQuery 3.2.1: http://jsfiddle.net/yhcLmk9d/
- jQuery 2.2.4: http://jsfiddle.net/b3o2Lb4k/

**Comment by AlexandrSargsyan** [comment]
In my case nothing is so simple. May be there is a some option caused this problem?

**Comment by ValentinH** [comment]
I can also be due to another library included in your project. As long as you can't provide me with a demo, I'm closing this issue.
