### ISSUE TITLE
Question - angular version

### ISSUE THREAD

**Issue by DavidDecraene** [angular-slider/angularjs-slider#522]
First of all very nice library

I almost don't dare to ask, but I assume no one has started an angular 2 version?

**Comment by ValentinH** [comment]
As far as I know, nope! :)

**Comment by ValentinH** [comment]
It would not be a really hard thing to port it I guess because most of the logic is not really linked to AngularJS but handles the DOM directly...

**Comment by ValentinH** [comment]
This one seems pretty similar though: http://bogdan1975.github.io/slider/

Indeed, the website is inspired by this project one and there is even the elegance-2 style that is the exact same as the default style of this library.
