### ISSUE TITLE
Possible to change line color above/below range?

### ISSUE THREAD

**Issue by atdiff** [angular-slider/angularjs-slider#523]
Is it possible to change the color of the rz-bar (or some other way) so that the top of it above the marker is one color, and the bottom of the bar is another color below the other marker?  So in the image here, the red circled area of the bar could be styled red, and the highlighted yellow part could be styled yellow.  Is this possible?  I know the getSelectionBarColor option does the selection bar but doesn't handle the "outer" bar.
![image](https://cloud.githubusercontent.com/assets/16138266/24924655/2442f950-1ebb-11e7-8cfc-4f86aae4c2d0.png)
Thanks

**Comment by ValentinH** [comment]
This is not possible at the moment. Moreover, it would be pretty complicated to implement it because the outer bar is the same one for below the min and above the max...

**Comment by atdiff** [comment]
That's what I noticed when looking through the code.  I think it'd be a cool feature though.  Would have to split the outer bar into 2 or something.

**Comment by ValentinH** [comment]
Yes, if you want, you can implement it and submit a pull request. However, it should be done in a way that doesn't add too much overhead to the existing code, i.e. only split the bar when the option is set.

**Comment by tanmaydesai89** [comment]
@atdiff You can play with CSS for now. I modified slider using following classes:

`.rzslider .rz-pointer {
    top: -6px;
    z-index: 3;
    width: 16px;
    height: 16px;
    cursor: pointer;
    background-color: #9da5b4;
    border-radius: 16px;
}

.rzslider .rz-pointer:after { 
display: none;
}

.rzslider .rz-bar {
  background: #828997;
}`

I hope this helps.

**Comment by ValentinH** [comment]
I don't think this modified the bar before and after the range with separate colors...

**Comment by GMaxera** [comment]
@ValentinH If you would implement this new feature, what approach you would use ? What part of the code you would suggest to modify ?
Just wondering if it's something I could do, but I need a guidance to avoid to look in the wrong place for implement this new feature.

**Comment by ValentinH** [comment]
As  we discussed above, it's pretty tricky to do it. Currently, there is the main bar which takes the whole width of the slider, and the selection bar that can be visible for single slider or range ones.

To display a separate color for value before and after a range, you need to other bars in the dom and you need to handle their position/size at each rendering of the slider. You can still look at how the selectionBar is handled if you want to give it a go.

In my opinion, it's a tough feature that will require some kinda dirty code to implement...

**Comment by GMaxera** [comment]
That's my idea, let me know if you see a future in it :-)

There is a 

<span class="rz-bar-wrapper"><span class="rz-bar"></span></span>

that's used for the background and there is a

<span class="rz-bar-wrapper" style="visibility: visible; width: 743px; left: 559px;">
<span class="rz-bar rz-selection" ng-style="barStyle"></span></span>

that display the selection.

My idea is to add two of this:
<span class="rz-bar-wrapper" style="visibility: visible; width: 743px; left: 0px;">
<span class="rz-bar rz-selection" ng-style="barOuterLeftStyle"></span></span>

<span class="rz-bar-wrapper" style="visibility: visible; width: 743px; right: 0px;">
<span class="rz-bar rz-selection" ng-style="barOuterRightStyle"></span></span>

That they would display the outer coloured bar.
And then at the line 1286 of rzslider.js calculate the dimension of the left and right outer bars.
There is enough data already calculated, so it won't be more that two additional sum there and two call of this.setDimension

What do you think ?

**Comment by GMaxera** [comment]
Oh no, it's stripped by HTML code

**Comment by ValentinH** [comment]
Yes, it's a good start. However, you will also need to handle clicks on these 2 new bars. I'm wondering if by default the click would go to the element under them, i.e. the main bar.

**Comment by GMaxera** [comment]
Good, ok. I'll start and we will see if I can proceed on solving this :-)

**Comment by GMaxera** [comment]
Created a pull request with a possible working solution.

**Comment by benson87** [comment]
can try use angularjs  rangeContainer

**Comment by GMaxera** [comment]
This feature is now part of this library from version 6.4.0.
http://jsfiddle.net/z3dLacot/

**Comment by ValentinH** [comment]
Yeah actually I forgot to close it. ;)

**Comment by atdiff** [comment]
Just updated my code with the latest. Really like the new feature - looks great! Thanks @GMaxera and @ValentinH!
