### ISSUE TITLE
Ability to set value at which labels combine?

### ISSUE THREAD

**Issue by atdiff** [angular-slider/angularjs-slider#524]
I have steps of 0.01 and a floor of 0 to a ceil of 0.50.  When the 2 selectors get within 0.09 of each other, they start to merge the labels.  They could go till at least 0.04 or 0.03 before they'd be next to each other.  Is there a way to make it so they labels don't merge and get retained on their related selectors - maybe a property to set or something?
In the interim, I've set a minRange of 0.10, but there are some cases where the user wants a range of 0.05.  So it'd be nice to prevent the combined labels unless it's absolutely necessary.

**Comment by ValentinH** [comment]
The combined label is not shown based on the values but based on the size of the min/max labels. If they overlap, then we show the combined one. ;)

**Comment by atdiff** [comment]
Thanks. Realized the line height on my selectors was causing the labels to overlap even though they didn't appear to physically overlap.
