### ISSUE TITLE
ticks rendering issue when floor or ciel value are high

### ISSUE THREAD

**Issue by AjitsinghKamal** [angular-slider/angularjs-slider#525]
### Steps to reproduce
1. set floor and ciel values in high range, say 10k or above
2. set showTicks to true 

Demo: http://jsfiddle.net/17m9j4og/1/ 

### Expected behaviour
ticks should be displayed at rengular intervals as expected

### Actual behaviour
rendered ticks fill up the slider bar;rendering time is too long

**Comment by ValentinH** [comment]
You are trying to render 40k ticks! Of course, it's slow... 

You should set a number to `showTicks` instead of true. Like `showTicks: 1000`

**Comment by AjitsinghKamal** [comment]
So, the default behaviour for showTicks is to add a tick at intervals of 10s.

By the way,the issue persist if the use case is for adding fewer ticks at large interval.Like if we do `showTicks:5` for every 10000s
Demo:http://jsfiddle.net/17m9j4og/2/

For such cases I think using `ticksArray: [10000, 20000, 30000, 40000, 50000]` is best
http://jsfiddle.net/17m9j4og/3/

**Comment by ValentinH** [comment]
The value you provide is not the number of ticks, it's the step between each tick.

**Comment by AjitsinghKamal** [comment]
Thanks for clearing that out . In that case , I think this issue can be closed.

**Comment by ValentinH** [comment]
You are welcome. 😄
