### ISSUE TITLE
It is possible to use modulo when specifying min/max values?

### ISSUE THREAD

**Issue by greenygh0st** [angular-slider/angularjs-slider#526]
It is possible to use modulo when specifying min/max values?

For the project I am working on I have to work with fiscal months formatted YYMM. So I need to be able to have something like:

1710, 1711, 1712, 1801, 1802, 1803...

If that is not currently a feature I would be interested in doing a PR for it.

**Comment by ValentinH** [comment]
For this kind of very custom steps, you can use the `stepsArray` option. ;)
