### ISSUE TITLE
onEnd Function getting fired on window resize.

### ISSUE THREAD

**Issue by developer-vtnetzwelt** [angular-slider/angularjs-slider#528]
### Steps to reproduce
1. Using onEnd event and its getting fired on window resize of browser.
2. Added a alert box on onEnd event and then opened dev tools with F12.
3. The function itself getting fired without touching slider.

Demo: http://jsfiddle.net/cwhgLcjv/167/

### Expected behaviour
when we are opening the dev tools and windows get resized till slider level the alert box appears as it hits onEnd event.

Best Regards

**Comment by ValentinH** [comment]
This is weird, but I can't reproduce what you described in the demo. Are you sure the demo is working?

**Comment by murillo94** [comment]
@developer-vtnetzwelt see this #79, maybe it helps you
