### ISSUE TITLE
Not working with decimals?

### ISSUE THREAD

**Issue by warhost** [angular-slider/angularjs-slider#529]
### Steps to reproduce
1. Go to the Demo JS Fiddle: https://jsfiddle.net/ValentinH/954eve2L/
2. Go to the $scope.minRangeSlider
3. Change minValue to 0.1, maxValue to 1, floor to 0.1 and ceil to 1, steps to 0.1
4. Run it, won't work.

### Expected behaviour
The slider should increase in steps of 0.1 from 0.1, being the smallest allowed value, up to 1, being the greatest.

### Actual behaviour
You can't drag the slider.

**Comment by ValentinH** [comment]
You need to set the precision option.
