### ISSUE TITLE
Possible to change the distance between the floor tick and the ceil tick？

### ISSUE THREAD

**Issue by REX-LCCCC** [angular-slider/angularjs-slider#533]
Hi,  after I use this component, I have solved a lot of issues. so thank for awesome angular component first.
And I wonder is it possible to change the distance between the floor tick and the ceil tick？

**Comment by ValentinH** [comment]
I'm not sure to understand what you mean, could you detail a bit more?

**Comment by REX-LCCCC** [comment]
![aaa](https://cloud.githubusercontent.com/assets/28821498/26274361/d07176a6-3d7a-11e7-8235-da2f8480c5b5.jpg)
I just want to change the distance between that two section which are highlighted in the picture. I have tried a lot, but all failed...

**Comment by ValentinH** [comment]
Do you mean to change the width of the slider or change the position of the ticks on the slider?

**Comment by REX-LCCCC** [comment]
I mean to change the position of the ticks, and make them closer.

**Comment by ValentinH** [comment]
you can't do that. The position of the ticks is determined by the position of the value it marks on the slider...
