### ISSUE TITLE
.onEnd attribute multiple calling 

### ISSUE THREAD

**Issue by oleszczyk** [angular-slider/angularjs-slider#536]
### Steps to reproduce
1. assign any notification action to '.onEnd' attribute
2. move and stop slider many times
3. notice that now single move-stop event fire many notifications (as many notifications as many moves have been proceeded)

### Expected behaviour
Single move-stop event should call only one '.onEnd' directive

### Actual behaviour
Single move-stop event calls '.onEnd'  as many times as many moves have been proceeded from page has been loaded.

**Comment by ValentinH** [comment]
cc @daniela-mateescu

**Comment by ValentinH** [comment]
@oleszczyk 6.2.1 should fix your issue! ;) Tell me if it's OK please 😄

**Comment by ValentinH** [comment]
Note for myself: the fix is probably fine but a unit test covering this issue should be added...
