### ISSUE TITLE
How do I avoid slider following the mouse on left click and move

### ISSUE THREAD

**Issue by shamresh** [angular-slider/angularjs-slider#538]
Hi,
If I click a slider end point and move the mouse, as expected the slider moves.

However, if I left click the slider and hold and then move the mouse the slider end point follows the mouse. How can I avoid this from happening? I prefer the above first behavior and want to disable holding down left click and moving the mouse.

**Comment by ValentinH** [comment]
What difference do you see between a "click" and a "left click"?

**Comment by ValentinH** [comment]
Closing as there was no answer for more than 10 days. Comment to re-open 😉
