### ISSUE TITLE
Need Max value for left slider and min value for right slider

### ISSUE THREAD

**Issue by kinoli** [angular-slider/angularjs-slider#539]
I need to have a value that the left slider can't pass and use that same value that the right slider can't pass. Is that a feature yet?

**Comment by ValentinH** [comment]
Nope there is not such a feature at the moment. There are the `min/maxLimit` that are non visible limits and `min/maxRange` that specify the min/max difference between low and high handles at the moment.

**Comment by ValentinH** [comment]
Closing as there was no answers for more than 10 days. Comment to re-open 😉
