### ISSUE TITLE
Update floor/ceil values externally and reload the slider

### ISSUE THREAD

**Issue by kinoli** [angular-slider/angularjs-slider#540]
Is there a way to reload the slider so it grabs updated options?

**Comment by ValentinH** [comment]
If you update the options from inside Angular, it should be automatic. Otherwise, you can force it by emitting a specific event (most of the time inside a $timeout to force a $digest):
```js
vm.refreshSlider = function () {
    $timeout(function () {
        $scope.$broadcast('rzSliderForceRender');
    });
};
```

**Comment by ValentinH** [comment]
Closing as there was no answers for 10 days.
