### ISSUE TITLE
Strict dependencies error

### ISSUE THREAD

**Issue by saimahaji** [angular-slider/angularjs-slider#541]
In my project im having strict dependencies enable.
When I try to upgrade my version my getting errors for strict dependencies
Eg: in rzslider.js the directive rzslider has dependency of 'RzSlider'

Actual: .directive('rzslider', function(RzSlider) {
Expected:  .directive('rzslider',["RzSlider", function(RzSlider) {

**Comment by ValentinH** [comment]
What file are you using? The dist ones should use this syntax.

**Comment by saimahaji** [comment]
I using rzslider.js from  src folder. Should use dist folder js?

**Comment by saimahaji** [comment]
Its working fine. Thanks
