### ISSUE TITLE
Watch on angular-slider 

### ISSUE THREAD

**Issue by Roix117** [angular-slider/angularjs-slider#542]
Hello i want to get the value slider on change, to check if it's good but return the value of the slider endlessly 
```js
     $scope.$watch('calForm.slider.value', function(newValue, oldValue) {
                if(newValue || newValue === 0) {
                    self.levelChange(newValue, oldValue);
                }
            }, true);
```

### Expected behaviour
Return the value of the slider once

### Actual behaviour
Return the value of the slider endlessly

**Comment by ValentinH** [comment]
You should use the `onChange` option for this purpose.

**Comment by Roix117** [comment]
Thanks
