### ISSUE TITLE
setiing rz-slider-options then getting hang problem?

### ISSUE THREAD

**Issue by rahi-rajeev** [angular-slider/angularjs-slider#543]
Hello Team,
i am using rzslider version 6.2.2 
in this slider when i am setting rz-slider-options then its hang

**Comment by ValentinH** [comment]
Hello!

Could you please set up a demo so I can understand what's going on? You can fork the jsfiddle in the readme...

**Comment by ValentinH** [comment]
Closing as there was no answers for 10 days.
