### ISSUE TITLE
Lag When Multiple Slider Value Change at Once

### ISSUE THREAD

**Issue by FilmCoder** [angular-slider/angularjs-slider#544]
### Steps to reproduce
1.  make several sliders which share the same angular modal
2.  move one slider, you will notice that the other lag behind in rendering

My actual use case is that I want to have multiple sliders, each with there OWN models.  However, I want the ability to select multiple sliders at once, then if you change one slider, other sliders which are also selected match the value of your changed slider as you change it.  However, I'm getting considerable lag.

I simplified the actual program I made by just having several sliders share the same model.  Move one of the 3 sliders around quickly an you'll see how the other two sliders lag behidn.

Demo: https://jsfiddle.net/4wytxhkz/

### Expected behaviour
When moving one slider, the others should move simultaneously with no lag.

### Actual behaviour
There is considerable lag on the other two sliders when you move one of them.  They all share the same model, there should be no lag.  Is this a rendering problem?

**Comment by ValentinH** [comment]
I'm very sorry for the delay, I missed your issue. Actually the solution is quite simple: add the `interval: 0` option. 😉

**Comment by FilmCoder** [comment]
Thank you so much!  I appreciate it, that makes perfect sense!
