### ISSUE TITLE
Slider is disabled in internet explorer

### ISSUE THREAD

**Issue by mdali602** [angular-slider/angularjs-slider#546]
**###** Steps to reproduce
1. Implented in **ionic1** project, Working **fine in chrome** but in **internet explorer slider is disabled**.
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by ValentinH** [comment]
When you say "disabled", you mean that it's displayed with the disabled state or it just doesn't work.

**Comment by ValentinH** [comment]
Closing as there was no answers for 10 days.
