### ISSUE TITLE
dynamic translate issue

### ISSUE THREAD

**Issue by astritademi62** [angular-slider/angularjs-slider#548]
1.  <select ng-model="selectedOpt"><option>A</option><option>B</option></select>

2. if (scope.selectedOpt == "A"){
              scope.slider.options.translate = function (value) {
                       return "A" + value;
              } 
     else if (scope.selectedOpt == "B"){
              scope.slider.options.translate = function (value) {
                       return value + "B";
              }
      else { return null;}

3.  What I want to happen is when I select "A" I want the slider values to display as "Avalue", and when I select "B" I want the slider values to display as "Bvalue", this is not the case though.

But, when I do just this...: 

scope.options.translate = function (value) {
        return "A" + value;
        }

...works just fine. I need the above example to work though.

**Comment by ValentinH** [comment]
Why not:
```js
scope.options.translate = function (value) {
    if (scope.selectedOpt == "A"){
        return "A" + value;
    }
    else if (scope.selectedOpt == "B") {
        return "B" + value;
    }
}
```

**Comment by astritademi62** [comment]
that was my first attempt, for some reason value would be undefined that way. 

anyway, I got it working by doing this instead:
`scope.options.translate = function (value) {
            switch(scope.selectedOpt) {
                  case "A" :
                           return "A" + value;
                  case "B" :
                           ....}`

Don't know why this worked and the above didn't, although this doesn't update automatically if I switch between them. I'm going to have to recompile the slider every time one of these changes happens. :/

If there is away to wipe the translate option completely and recreate it every time the value for selectedOpt changes I would love to know. Thank you.

**Comment by ValentinH** [comment]
Your setup looks weird. The translate option is a function that is executed at runtime, every time the slider needs to be redrawn. Thus, when your selectedOpt changes, the slider should be refreshed.

**Comment by astritademi62** [comment]
here's a more complete setup:

` //HTML//
<select ng-model="selectedOpt" ng-change="onOptChange">
            <option>"A"</option>
            <option>"B"</option>
  </select>
<rzslider rz-slider-model="slider.value" rz-slider-options="slider.options"></rzslider>`


`//JS//
scope.onChangeOpt = function () {
             scope.options.translate = function (value) {
                         switch(scope.selectedOpt) { 
                                 case "A" : return "A" + value; 
                                 case "B" : ....}
}
`

**Comment by ValentinH** [comment]
Please set up a demo showing the issue... You can use the JSFiddle example on the README

**Comment by astritademi62** [comment]
https://jsfiddle.net/954eve2L/1862/

This is what I have. It doesn't update the value. This doesn't update the value on my environment either until I recompile my HTML template.

**Comment by astritademi62** [comment]
okay so I made a few changes and I got it to this:

https://jsfiddle.net/954eve2L/1879/

this seems to work only the first time I select an option.

**Comment by astritademi62** [comment]
https://jsfiddle.net/954eve2L/1904/

SUCCESS!

**Comment by ValentinH** [comment]
Great! Actually, I had started to look into it earlier today and I tried to use the refreshSlider trick instead of your dynamic function one but it wasn't enough. Look like using the two methods was the way to go. 😄
