### ISSUE TITLE
How to use this library in agular 2/4

### ISSUE THREAD

**Issue by pranavkeke** [angular-slider/angularjs-slider#549]
Thanks for this lib.
How can I use it in angular 2

**Comment by ValentinH** [comment]
There is no support for Angular 2 at the moment. It would be a new library, rewritten almost from scratch, and since I'm not using Angular 2, I won't do it.

**Comment by ValentinH** [comment]
@pranavkeke we now have a angular version: https://github.com/angular-slider/ng5-slider/tree/master 🎉
