### ISSUE TITLE
showTickValue not displaying as expected

### ISSUE THREAD

**Issue by jemartin80** [angular-slider/angularjs-slider#550]
### Steps to reproduce
1. View Link http://jsfiddle.net/jnfsekpg/1/

### Expected behaviour
Should only have tick values displayed for integer values with tick marks shown at 0.5 increments.

### Actual behaviour
Shows tick values at 0.5 steps. If showTicks is false then tick values are only displayed for integer values, but no tick mark is shown for 0.5 increments.

**Comment by ValentinH** [comment]
Good point, I fixed it: http://jsfiddle.net/jujrs0v0/

Actually, I didn't thnink about this usage, but it was a good one 👍 

You can update to 6.3.0 to get the fix.
