### ISSUE TITLE
Add animation when dragging the slider

### ISSUE THREAD

**Issue by geniusit** [angular-slider/angularjs-slider#552]
### Steps to reproduce
1. Move the pin to right or left
2. Note that there aren't any animation from value to value.

### Expected behaviour
It would be nice if an animation is visible when the user starts to move the pin.
The angular material already implements it as weel.
Note the animation on the angular material slider : 
https://material.angularjs.org/latest/demo/slider

Rating: /5 - demo of theming classes example is particulary relevant.

When the user starts to move the pin, the pin starts to drag immediately. When the user release the mouse button, the pin will be move to the relevant value.  (the next value if dragged distance is > 50 % or the current one if distance is < 50% of the distance between the next value) 

### Actual behaviour
The pin will move only when the user has moved it ON the next / previous value. There aren't any animation on it. Animation improves UX

**Comment by ValentinH** [comment]
OK, I understand what you mean.

However, I'm sorry to say that with the current implementation of this library, it's pretty hard to do this kind of animation.

If you want to give it a try though, Pull requests are always welcome. 🙂

**Comment by ValentinH** [comment]
This will be released in v7.0.0
