### ISSUE TITLE
maxValue gets roundoff for rz-slider-high

### ISSUE THREAD

**Issue by yameenyasin** [angular-slider/angularjs-slider#557]
### Steps to reproduce
Please find the fiddle here http://jsfiddle.net/YameenYasin/fzfsmcL7/13/

### Expected behaviour
The max value is getting displayed as 10017221487 instead of 10017221487.02 in the given example

### Actual behaviour
The max or high value should be 10017221487.02

**Comment by yameenyasin** [comment]
using **enforceStep:false** fixed the issue. thanks

**Comment by ValentinH** [comment]
Actually, this issue was weird because it was working with smaller number: http://jsfiddle.net/gfsbhcrL/
