### ISSUE TITLE
Updating slider values

### ISSUE THREAD

**Issue by imran7404** [angular-slider/angularjs-slider#558]
I want to update my slider ceiling and value. When i send values to the slider option, a new slider is created with the first one. It happens when i open the debug mode and change the range. Then i send new ceiling and value values. 

```js
 $scope.compressorSlider = {
                value: recommendedCompressorWashPeriod, // want to change
                options: {
                    floor: 0,
                    ceil: recommendedCompressorWashPeriod, // want to change
                    step: 200,
                    minLimit: 200,
                    showTicks: true,
                    onChange: onCompressorWash
                }
```
![slider](https://user-images.githubusercontent.com/29626418/29611899-ac768be0-87ff-11e7-86f9-f7959150b45b.gif)

                 
            };

**Comment by ValentinH** [comment]
I'm not sure to understand your issue. You are trying to change the ceil but it doesn't change? Or it changes but the layout is then broken?

**Comment by imran7404** [comment]
I think, there is a problem with mouseup event. When i go to debug mode and drag the slider, mouse hang with the slider. while the mouse is hanged with slider, i change my ceil and step values through a function then the slider just crash or  create another slider or goes up from ceiling as you can see in the attach file with value 4200-0.

**Comment by imran7404** [comment]
i am waiting your reply?

**Comment by ValentinH** [comment]
I think this is the same as #476 but there is no fix at the moment.
