### ISSUE TITLE
Make it work with Ionic framework

### ISSUE THREAD

**Issue by rzajac** [angular-slider/angularjs-slider#56]

**Comment by ValentinH** [comment]
Anyone is using this library with Ionic? I need to know if this is still an issue or not.

**Comment by akorn2** [comment]
I was unable to successfully install this in my Ionic app.

**Comment by ValentinH** [comment]
Can you provide more information? Installation should not be a problem because I know that they are people using it (like @madhur in #178). My question was more about specific bugs they were detected only with ionic.

**Comment by georgebatalinski** [comment]
I had an issue with slider in Ionic - the problem was solved below: It works awesome other then that

Instead of:
```
 rz-slider-ceil="250000"
 rz-slider-step="1000"
```
 
I replaced with:
```
 rz-slider-options="options"
```

Inside 
this.valueRange - was always 0
```
offsetToValue: function (offset) {
          return (offset / this.maxPos) * this.valueRange + this.minValue;
        },
```

**Comment by ValentinH** [comment]
@georgebatalinski indeed with version 2, floor and ceil should be defined in options.
I don't understand what was the issue with `this.valueRange`

**Comment by georgebatalinski** [comment]
Good to know :) The way I found the way to solve it, is when I noticed that  `this.valueRange` == 0 with the following setup:
```
rz-slider-ceil="250000"
 rz-slider-step="1000"
```

**Comment by ValentinH** [comment]
So is there still a problem? I'm not sure to understand...

**Comment by georgebatalinski** [comment]
no problem :)

**Comment by JMoli** [comment]
I am getting white screen of death on Android with Ionic 1.7.14 when I include rzModule.

**Comment by ValentinH** [comment]
@JMoli  What error do you get?

**Comment by JMoli** [comment]
@ValentinH the problem was I started my rz-module script path declaration with a forward slash. This made it work with ionic serve, but not on my android device. I have not tested with IOS but this works with android platform in ionic for me no problems!

**Comment by ValentinH** [comment]
I'm closing it for now since I've seen several people using this slider along with Ionic without having issues.
