### ISSUE TITLE
Updating to 6.4.0 from 6.3.0 throws error

### ISSUE THREAD

**Issue by stripathix** [angular-slider/angularjs-slider#561]
Cannot set property rzsp of null.

My Template file also attached.

<img width="669" alt="screen shot 2017-08-26 at 12 06 01 am" src="https://user-images.githubusercontent.com/8480351/29727693-a225c6c0-89f2-11e7-9853-37e6e3bf4fda.png">

**Comment by GMaxera** [comment]
The HTML template is changed due to new feature I introduced.
Take a look at the new structure. There are additional span.

**Comment by GMaxera** [comment]
Can you post the "common/template/bn-rzSliderTpl.html" are you using ?

**Comment by stripathix** [comment]
<div class="rzslider">
  <span class="rz-bar-wrapper"><span class="rz-bar"></span></span>
  
  <span class="rz-bar-wrapper">
  <span class="rz-bar rz-selection" ng-style="barStyle"></span>
  </span>
  
  <span class="rz-pointer rz-pointer-min" ng-style=minPointerStyle>
    <span class="rz-ruleset-pointer" background-color="minPointerStyle.backgroundColor" slider-rule ng-style="{'color': '#fff'}" >
     </span> 
  </span>
  
  <span class="rz-pointer rz-pointer-max" ng-style=maxPointerStyle></span>
  
  <span class="rz-bubble rz-limit rz-floor"></span>
  
  <span class="rz-bubble rz-limit rz-ceil"></span>
  
  <span class="rz-bubble"></span>
  
  <span class="rz-bubble"></span>
  
  <span class="rz-bubble"></span>
  
  <ul ng-show="showTicks" class="rz-ticks">
    
    <li ng-repeat="t in ticks track by $index" class="rz-tick" ng-class="{'rz-selected': t.selected}" ng-style="t.style" ng-attr-uib-tooltip="{{ t.tooltip }}"
      ng-attr-tooltip-placement="{{t.tooltipPlacement}}" ng-attr-tooltip-append-to-body="{{ t.tooltip ? true : undefined}}">
      <span ng-if="t.value != null" class="rz-tick-value" ng-attr-uib-tooltip="{{ t.valueTooltip }}" ng-attr-tooltip-placement="{{t.valueTooltipPlacement}}">{{ t.value }}</span>
      <span ng-if="t.legend != null" class="rz-tick-legend">{{ t.legend }}</span>
      </li>
  </ul>
</div>

**Comment by stripathix** [comment]
This text file contains the html I am using:
[bn-rzSliderTpl.txt](https://github.com/angular-slider/angularjs-slider/files/1252827/bn-rzSliderTpl.txt)

**Comment by GMaxera** [comment]
You have to add two span at the start of the template.
Try to use the one I modified and let me know.
[bn-rzSliderTpl.txt](https://github.com/angular-slider/angularjs-slider/files/1253479/bn-rzSliderTpl.txt)

**Comment by ValentinH** [comment]
@GMaxera this issue is only for people using custom templates right?

**Comment by GMaxera** [comment]
Yes, it's only for people were using custom templates and they upgrade to 6.4.0

**Comment by ValentinH** [comment]
Ok. Maybe we should have release a major version since it's a breaking change...

**Comment by GMaxera** [comment]
Yes, you are right ... sorry I didn't think about that :-(

**Comment by ValentinH** [comment]
No worries, I didn't think about it either ;)

**Comment by stripathix** [comment]
Thanks for the update. This plugin is too good. See what I have done with this:
<img width="596" alt="screen shot 2017-08-28 at 11 32 02 pm" src="https://user-images.githubusercontent.com/8480351/29786557-36b9329c-8c49-11e7-936f-0ec6e122635f.png">

**Comment by ValentinH** [comment]
Wow, I think we created a monster! :D
