### ISSUE TITLE
customPositionToValue on Keyboad event

### ISSUE THREAD

**Issue by czery** [angular-slider/angularjs-slider#562]
Hi there,

I defined a customPositionToValue for the slider which works just fine when used with mouse drag. But if I use the keyboard to select a slider value the customPositionToValue function seems to be ignored. 

I have created a demo on JSFiddle: [https://jsfiddle.net/czery/mwy45dxt/](https://jsfiddle.net/czery/mwy45dxt/)

I guess this is not an expected behavior, is it? If so, does anyone have a clue on how to fix this?

Cheers and thanks in advance
czery

**Comment by ValentinH** [comment]
`customPositionToValue` should be used along with `customValueToPosition` which do the reverse job. However, these functions only work with a constant step, while in your example, your step changes.

**Comment by czery** [comment]
Hm, I think I did not get that right... What you mean with "reverse job"? When do I get a value which will be transformed into a position? When will the one or the other function be executed?

**Comment by ValentinH** [comment]
The slider to be rendered needs to be able to map a value to a screen position and also (to handle mouse events) it needs to be able to map a screen position to a value. 

See the "Custom scale" example on the website. 

However, in your case , this won't be enough since you don't have a constant step.

**Comment by czery** [comment]
Thanks for the information, @ValentinH 
So far so good, I have updated my Fiddle with the "customValueToPosition" function (and I do understand that this will not help me with my issue): [https://jsfiddle.net/czery/mwy45dxt/](https://jsfiddle.net/czery/mwy45dxt/)

Is there any way to define a listener for the keyboard event so that I could update the value based on the closest value of the given array? Something like `onKeyboardChange: setValue(value.getClosest(stepsArray))` 

Cheers
czery

**Comment by ValentinH** [comment]
No there's only the `onChange` callback where you can do this. But you won't differentiate keyboard and mouse.

**Comment by czery** [comment]
To close this: I managed to resolve my issue by using onStart and onChange to detect if keyboard press was "up" or "down" and then compare the new values against my input array.

Here ist the JSfiddle: [https://jsfiddle.net/czery/mwy45dxt/](https://jsfiddle.net/czery/mwy45dxt/)

**Comment by ValentinH** [comment]
Thanks for the feedback. Your solution work but is kind-of hackish. Also if you press the keyboard quickly, the result is bugged.

I found a solution by using the `stepsArray` function and adapting the custom scale functions.

Demo: https://jsfiddle.net/Ltprx6e7/

The important part of the code is the line like `val = $scope.stepsArray[val]`. Indeed, when using a `stepsArray`, internally, we manipulate the indexes of the array. Thus the val, minVal and maxVal args passed to the `customValueToPosition` and the returned value of `customPositionToValue` are the indexes in the array.

**Comment by czery** [comment]
Awesome! Yep, that seems to be cleaner implemented :)

Thanks for your support.
