### ISSUE TITLE
Slider orientation based on screen size

### ISSUE THREAD

**Issue by dfavaro** [angular-slider/angularjs-slider#564]
Is it possible to change slider orientation with "vertical" option based on screen size? In my case, I need to have an horizontal slider for mobile version and a vertical one for a desktop version.
Thanks

**Comment by ValentinH** [comment]
Yes this is possible, but you need to do it when you initialize the slider. This is not handled (and can't be handled) by the library.

**Comment by dfavaro** [comment]
It could be a nice feature for future builds. Any way thank you.
