### ISSUE TITLE
vertical option is not working...

### ISSUE THREAD

**Issue by astritademi62** [angular-slider/angularjs-slider#568]
https://jsfiddle.net/954eve2L/2127/

the slider fails to load properly if I set vertical option to true.

**Comment by GMaxera** [comment]
If you don't assign an explicit height to the container div on which the slider lives, then it can't work properly.

**Comment by astritademi62** [comment]
... I was hoping that there would be a simple way of toggling between vertical and horizontal orientation... oh well. Thanks.
