### ISSUE TITLE
Slider values collapsed by default

### ISSUE THREAD

**Issue by MadhuKumarGowda** [angular-slider/angularjs-slider#569]
### Steps to reproduce
1.  By default the ticks values are collapsed, when i click on slider, the value are displaying properly.

I am trying to implement slider in modal pop-up

**My HTML Code**
                                               
                                    <div style="height:400px !important">
                                       <rzslider id="maskRange" rz-slider-model="slider.value"
                                                  rz-slider-options="slider.options"></rzslider>
                                    </div>

**JScode**

 $scope.slider = {
        value: 40,
        options: {
            ceil: 200,
            floor: 40,
            step: 40,
            showTicks: true,
            showTicksValues: true,            
            precision: 1,
            vertical: true,
            onEnd: function () {
                todrawMaskOnRange();
            }
        }
    };

Screenshot for reference 
![slider issue](https://user-images.githubusercontent.com/20521582/30414145-c3215626-993f-11e7-9d92-a09fcd194fff.png)

i have notice one thing that, by default the style of ticks are set to transform: translateY(0px);

![noticed](https://user-images.githubusercontent.com/20521582/30414510-97d71896-9941-11e7-8c15-804753bd2c67.png)

Please help me out resolve this issue.

**Comment by ValentinH** [comment]
https://github.com/angular-slider/angularjs-slider#my-slider-is-not-rendered-correctly-on-load

**Comment by MadhuKumarGowda** [comment]
Thank you for the help :)

**Comment by ValentinH** [comment]
You are welcome 👍
