### ISSUE TITLE
Return slider to floor when scope variable changes

### ISSUE THREAD

**Issue by pi-kalinowski** [angular-slider/angularjs-slider#574]
Hello,

I've created a slide-to-approve component that will submit an action once the slider has made a full "swipe" from floor to ceil.

The issue I'm trying to overcome is resetting the slider back to floor if a certain event/scope change occurs **while on mousedown or touchstart.**  For touch devices, if my finger is in the process of swiping the control to the right I need it to return/animate while my finger is still on the screen and a certain event/scope change occurs.  The same scenario applies while using a mouse pointer and the event/scope change occurs while the mouse button is still held down.

I tried a mixture of disabling/enabling, disable->set value to 0->enable, etc. but nothing has worked.

Thoughts on a possible solution or feature that can handle this?

Thank you.

**Comment by ValentinH** [comment]
You could watch the onEnd event in set the model value back to 0.

**Comment by pi-kalinowski** [comment]
Thank you for the response.

Will this event fire if you're in the process of moving the slider when a scope variable changes?

For example, I'm actively sliding an element to the right and while the slide is still occurring a specific event fires (not an angularjs-slider event but a different Angular event).  When this event fires I need something to happen that will override the mousedown/touchstart action and cause the element to automatically go back to the starting position.

**Comment by ValentinH** [comment]
No, this event is only fired for internal changes.

**Comment by pi-kalinowski** [comment]
OK, so it seems I'll have to go outside of the slider library to accomplish this somehow.

I appreciate the help, thank you.

**Comment by ValentinH** [comment]
Indeed, it will be more efficient and flexible if you build this yourself as your use case is pretty far from what provide this library.
