### ISSUE TITLE
Custom template broken

### ISSUE THREAD

**Issue by iTz-Maleficas** [angular-slider/angularjs-slider#575]
### Steps to reproduce
1. Make a custom template
2. Add the template to angularjs slicer
3. Open console

### Expected behaviour
Display the custom template successfuly

### Actual behaviour
throw an error "TypeError: Cannot set property 'rzsp' of null" and broke the slicer

Note: this problem also happend in http://angular-slider.github.io/angularjs-slider/index.html

**Comment by GMaxera** [comment]
Can you attach the custom template you set and specify what version of angularjs-slider are you using ?

**Comment by iTz-Maleficas** [comment]
this problem also happend in http://angular-slider.github.io/angularjs-slider/index.html

**Comment by GMaxera** [comment]
Ok, the problem happen because in the version 6.4.0 has been introduced a new feature that required the change of the custom template.
We realized only after we released such version that it's not possible to use anymore the old custom template with version 6.4.0 of the library.

**Comment by GMaxera** [comment]
The new format for custom template used by 6.4.0 version requires some additional span at the beginning: https://github.com/angular-slider/angularjs-slider/blob/master/src/rzSliderTpl.html

**Comment by iTz-Maleficas** [comment]
thanks @GMaxera!
