### ISSUE TITLE
Tooltip for minValue and maxValue 

### ISSUE THREAD

**Issue by iTz-Maleficas** [angular-slider/angularjs-slider#576]
I have read the docu and i havent found info about this ... So I think this functionality is not present ...

Any idea to add it?
I probe to use angular-material tooltips, but when moving the slice the tooltip does not move

angularjs-slider: ^6.4.0
Custom template:
`<div class="rzslider">
      <span class="rz-bar-wrapper rz-left-out-selection"><span class=rz-bar></span></span> 
      <span class="rz-bar-wrapper rz-right-out-selection"><span class=rz-bar></span></span> 
      <span class="rz-bar-wrapper"><span class="rz-bar"></span></span> 
      <span class="rz-bar-wrapper">
        <span class="rz-bar rz-selection" ng-style="barStyle"></span>
      </span> 
      <span class="rz-pointer rz-pointer-min" ng-style=minPointerStyle></span> 
      <span class="rz-pointer rz-pointer-max" ng-style=maxPointerStyle></span> 
      <span class="rz-bubble rz-limit rz-floor"></span> 
      <span class="rz-bubble rz-limit rz-ceil"></span> 
      <span class="rz-bubble"></span> 
      <span class="rz-bubble"></span> 
      <span class="rz-bubble"></span> 
      <ul ng-show="showTicks" class="rz-ticks"> 
        <li ng-repeat="t in ticks track by $index" class="rz-tick"
            ng-class="{'rz-selected': t.selected}" ng-style="t.style"
            ng-attr-uib-tooltip="{{ t.tooltip }}" ng-attr-tooltip-placement="{{t.tooltipPlacement}}"
            ng-attr-tooltip-append-to-body="{{ t.tooltip ? true : undefined}}">
          <span ng-if="t.value != null" class="rz-tick-value"
                ng-attr-uib-tooltip="{{ t.valueTooltip }}"
                ng-attr-tooltip-placement="{{t.valueTooltipPlacement}}">{{ t.value }}</span>
          <span ng-if="t.legend != null" class="rz-tick-legend">{{ t.legend }}</span>
        </li>
      </ul>
      </div>`

**Comment by ValentinH** [comment]
It depends on how the tooltip is rendered. It needs to be inside the handle element so it follows it.
