### ISSUE TITLE
Question: is it possible to prevent value change when clicking outside slider-thumb ?

### ISSUE THREAD

**Issue by gpiroux** [angular-slider/angularjs-slider#579]
The idea is to use this slider on ionic v1 and allow the user to scroll the page starting from an element containing a slider.

In that case, the slider should modify the value only if dragged from the slider-thumb. Is it possible ?

**Comment by ValentinH** [comment]
You can set the `onlyBindHandles` to true.

**Comment by ValentinH** [comment]
Demo: http://jsfiddle.net/dsu2kjdz/
