### ISSUE TITLE
Support inline events declaration rz-slider-end="myFunc()" without using options object in js

### ISSUE THREAD

**Issue by Ekus** [angular-slider/angularjs-slider#581]
### Steps to reproduce
A common pattern in angularjs is to have an existing collection of business objects (from json) and bind the angular controls to them and their properties. E.g. if I already have 10 items in cart, and all textboxes, dropdowns, ranges etc work with them directly, why would I create 10 superficial _options_ objects? The sliders are going to have identical options anyway, except for the business object.

    <div ng-repeat="item in cart.items">
            <rzslider rz-slider-model-"item.price" rz-slider-end="processItem(item) />
    </div>

_rz-slider-end_ doesn't exist, and *ng-change* doesn't work without _ng-model_, and I typically need to pass the whole _item_ object to the event handler, not just one property/value.

### Expected behaviour
My rz-slider instances come from ng-repeat template and it's easier to instantiate them with inline attributes instead of separate js options objects.

### Actual behaviour
I have to potentially declare multiple options object and assign them to multiple sliders which is problematic with templates.

Update:
I worked around the problem by creating a function that provides separate _options_ object for each slider, **but this feels backward and complicates the process of simply displaying items from json:**

    $scope.getSliderOptions = function(item) { return { onEnd: function() {$scope.processItem(item);}}}

    <rzslider rz-slider-model="item.quantity" rz-slider-options="getSliderOptions(item)"

Whether you implement it or not, I'd like to thank you for this great component!

**Comment by ValentinH** [comment]
Hi @Ekus , thanks for submitting this clear issue.

The version 1.0 library was using this pattern but as you can see today in the options, there are so many. Thus, it was getting complex to handle all of them and provide realtime changes on these options. This is why we removed this API.

If you only need the `onEnd` event, you can create inline options:
```html
<rzslider rz-slider-model="vm.priceSlider.value"
          rz-slider-options="{ onEnd: vm.processItem}"></rzslider>
```

```js
vm.priceSlider = {
  value: 200
}
    
vm.processItem = function(sliderId, modelValue) {
  console.log(modelValue);
}
```

Demo: http://jsfiddle.net/6u9498u8/

**Comment by Ekus** [comment]
Thanks for the clarification and the inline options solution! I haven't seen it mentioned in the documentation, maybe it's good idea to include it, or highlight it in some popular scenarios.

I still believe inline attributes and binding are what makes angularjs so friendly to designers and non-coders, but I understand the challenge (albeit I was hoping angularjs had a mechanism to automate it). Thanks for the reply!
