### ISSUE TITLE
Max value not resetting on window resize

### ISSUE THREAD

**Issue by AriaGrt** [angular-slider/angularjs-slider#582]
### Steps to reproduce
Resize window

### Expected behaviour
Max value repositionning on end of slider
### Actual behaviour
Max value keeping pre-resize position

**Comment by ValentinH** [comment]
I don't see any issue here:
![slider-resize](https://user-images.githubusercontent.com/2678610/31651859-8402c22a-b31d-11e7-886a-a64a04acf5f0.gif)

Could you please provide an example of the issue?

**Comment by ValentinH** [comment]
Closing as there was no answer for a long time. Comment to re-open 😉
