### ISSUE TITLE
Changing Slider Does Not Affect Form State

### ISSUE THREAD

**Issue by mickeyvip** [angular-slider/angularjs-slider#584]
### Steps to reproduce
1. Add slider to a form 
2. Add some styling that depends on form being `$invalid`/`$dirty` (for example a button that says "Close" when there was no change and "Cancel" when there was a change)
3. Change slider

### Expected behaviour
The styling should be triggered since the form was changed, so it is now `$dirty` and might be `$invalid`.

### Actual behaviour
Form is left intact.

**Comment by ValentinH** [comment]
You need to handle this manually via the callback methods options: onStart, onChange or onEnd.

**Comment by mickeyvip** [comment]
@ValentinH, thank you. 

I am doing it manually, but Angular does not give us `form` easily. 

Currently I am adding `<div ng-init="formCtrl = formName"></div>` at the end of the `form` to have a handle of the `formController`, but it seemed hacky.
