### ISSUE TITLE
Slider is jumping on ios devices

### ISSUE THREAD

**Issue by eesdil** [angular-slider/angularjs-slider#587]
### Steps to reproduce
1. Use official fiddle
2. Try it on real iPad or iphone
3. Click two times on different values, see the video

Demo: http://jsfiddle.net/cwhgLcjv/

### Expected behaviour
Should smoothly go to the new value without jumping.
### Actual behaviour
The indicator is jumping to the previous value and just after to the last selected one
Noticed, that I used the bigger demo, but tried with the small one and it is happening there also.
![jumping_slider](https://user-images.githubusercontent.com/1408181/32132182-43cad3d2-bbbf-11e7-925f-25eefd6238d1.gif)

Seemingly this is working everywhere fine only ios devices are the affected ones.

**Comment by ValentinH** [comment]
Hmm that sucks. Never noticed this behavior, is it on the latest version of iOS?

I don't have an iDevice to reproduce this, but it was working one year ago. So it's either a regression on the slider side or a weird behavior introduce with the latest version of iOS...

**Comment by eesdil** [comment]
was trying it with v9…
Now tried with v11 and didnt see this behavior. Though it was moving the
page sometimes after click, but tgats somethingbelse.

On 29 Oct 2017, at 20:11, Valentin Hervieu <notifications@github.com> wrote:

Hmm that sucks. Never noticed this behavior, is it on the latest version of
iOS?

I don't have an iDevice to reproduce this, but it was working one year ago.
So it's either a regression on the slider side or a weird behavior
introduce with the latest version of iOS...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/angular-slider/angularjs-slider/issues/587#issuecomment-340286388>,
or mute the thread

**Comment by gnesher** [comment]
Can confirm this is indeed happening on latest ios (testing on ipad mini 4) going to investigate

**Comment by gnesher** [comment]
@eesdil so it seems that UIWebView limits rendering during dragging (touchmove event). This was solved in iOS8/9 with the introduction of a new web view WKWebView.

This means that in Safari on latest iOS slider will work fine but when using it with Cordova / Ionic (which still uses the old web view) you will have problems. Luckily you should be able to install  cordova-plugin-ionic-webview to sort the issue

Hope this helps (works fine for me)

**Comment by eesdil** [comment]
thanks @gnesher 
we are not using cordova/ionic. So the bug appears when you access the webpage from an iphone safari... so i am just wondering why in that case.
I will check the safari versions we have on the test devices

**Comment by gnesher** [comment]
@eesdil I've tested it on an iPad mini 2 (running v 10.3.3) I don't have older devices, but I think it should work well from v8 upwords

**Comment by ValentinH** [comment]
Closing for clean-up. Please comment if issue is still existing.
