### ISSUE TITLE
TypeScript: Invalid module name in augmentation - rzslider.d.ts

### ISSUE THREAD

**Issue by MiroslavKral** [angular-slider/angularjs-slider#591]
We are upgrading our application from AngularJS 1.5 to Angular 5. With Angular 5, there is TypeScript 2.4. We are building with webpack 3.8.1 and error is:

`Error:(6, 16) TS2665:Invalid module name in augmentation. Module 'angular' resolves to an untyped module at /node_modules/angular/index.js', which cannot be augmented.`

We have angularjs-slider 6.4.0.

### Steps to reproduce
1. Use angularjs-slider in TypeScript 2.4 project or with Angular 5.

### Expected behaviour
It is possible to fix this by moving angular import into module declaration in **rzslider.d.ts**:

```
declare module "angular" {

    import * as angular from "angular";

    export namespace RzSlider {
         ...
    }
}
```

### Actual behaviour
Actually, angular import is outside module declaration  in **rzslider.d.ts**:

```
import * as angular from "angular";

declare module "angular" {

    export namespace RzSlider {
         ...
    }
}
```

**Comment by trodi** [comment]
This library doesn't support Angular 2+. See https://github.com/angular-slider/angularjs-slider/issues/549#issuecomment-320487941 .

Looking at other `d.ts` files for angular projects (e.g., angular-toastr, angular-translate, angular-ui-bootstrap), they all follow the same pattern as done in this project. Looking at the tsc error of yours, it appears that you don't have `@types/angular` installed. I've not tested with typescript 2.4, but I believe everything should work in an Angular 1.x app as long as you've installed the `@types/angular` as well.

Hope this helps.

**Comment by MiroslavKral** [comment]
Thanks for reply and solution. We have hybrid application with AgularJS 1.5 and Angular 5 and angularjs-slider is used only in AngularJS part.

But I installed @types/angular and everything works now.

I found my solution there: https://stackoverflow.com/a/42702089

So this is not issue and it can be closed ;-)

**Comment by trodi** [comment]
Glad to help.

@ValentinH , can you close this? Also, should we update the installation section of the readme to indicate that typescript definitions are included and if using them, there is a peer dependency on `@types/angular`?

**Comment by ValentinH** [comment]
Yeah sure. Would you like to update the readme ?
