### ISSUE TITLE
[Q] No labels shown with default settings

### ISSUE THREAD

**Issue by peterlitvak** [angular-slider/angularjs-slider#592]
Maybe I'm missing something but with default settings as in the examples I cannot get any labels (numbers) to show, no min/max no current value. Is this a bug or just some missing option?

**Comment by peterlitvak** [comment]
I've also noticed that spans that suppose to show labels have visibility set to "hidden".

**Comment by trodi** [comment]
It appears that the simple case without options on the [demo page](http://angular-slider.github.io/angularjs-slider/) works as expected and is using the latest version, 6.4. It is likely that you are missing something. 

The best way to file an issue is to follow the [issue template](https://github.com/angular-slider/angularjs-slider/blob/master/issue_template.md). It also provides a [jsfiddle template](http://jsfiddle.net/cwhgLcjv/) so you can show exactly what you are trying and others can help debug etc.

**Comment by peterlitvak** [comment]
Thank you, it seems to be a styling issue on my side, which will be hard to reproduce in a standalone way. Maybe you can give me some pointers as for the known or possible conflicts with bootrstrap styles? Also any idea why the labels will have style set to hidden? Like so:
```
<span class="rz-bubble rz-limit rz-ceil" style="visibility: hidden; left: 778px;">24</span>
```

**Comment by peterlitvak** [comment]
It is a styling issue, something was setting a font size to 0px.

**Comment by ValentinH** [comment]
@peterlitvak : the labels are hidden when the slider pointer is above them.
