### ISSUE TITLE
Not supporting mobile touch in angular project

### ISSUE THREAD

**Issue by saikumar100** [angular-slider/angularjs-slider#596]
Hi,
I tried to use this plugin in an angular project.
It is great that works in desktop , but it is not working on mobile.
I'm using this " jquery-3.2.1.min.js" version of jquery.
I'm using this version of slider angularjs-slider@6.4.1
I know that it works on mobile originally, but just not working on my angular project.

Just wonder how to make it work on mobile?
(I have already included angular-touch and have ngTouch module in my app)
Thanks,
Nick.

**Comment by ValentinH** [comment]
You probably have some library conflicting with this one. Indeed, our demo website works fine on mobile: http://angular-slider.github.io/angularjs-slider/
