### ISSUE TITLE
TypeError: (intermediate value)(...) is not a function

### ISSUE THREAD

**Issue by mlatzko** [angular-slider/angularjs-slider#597]
I use the angularjs-slider together with other 3rd party JS code an bundle it into one file. Because since version 6.4.1 the trailing semicolon is missing at the end of the closure, in `src/rzslider.js`, which causes an type error when bundled together with other libraries.

e.g. `(function(){})()(function(){})()` Error
e.g. `(function(){})();(function(){})()` No error

**Comment by bilalhammoud** [comment]
since yesterday i am running into this issue as well, could you fix it please as soon as possible

**Comment by logan-jobzmall** [comment]
The workaround I found is to make sure to terminate lines 2661 and 2662 with ';' in the dist/rzslider.js. Don't know how that computes in the main src. But it should help.

**Comment by mlatzko** [comment]
> Moreover, using https://github.com/angular-slider/angularjs-slider/blob/master/dist/rzslider.min.js should be fine since the last char is the semicolon.

As @ValentinH points out in the closed pull request #598 I now use the mininfied version. This solves the problem. Thx @ValentinH
