### ISSUE TITLE
Slider length is changing to 1300 px on refresh add with bootstrap

### ISSUE THREAD

**Issue by lakshmi1984** [angular-slider/angularjs-slider#600]
### Steps to reproduce
1. Add a slider in a div with col-md-3 
2. If I comes fine on load of page
3. But when I refresh the page the slider length is increased to 1301 px ahile on load its only 240px
4.my min value is 10000 and max value is 1000000 

I have updated the JSFiddle. I couldn't create the exact scenario. But here also it doesn't show the high value and pointer of the right hand side.

http://jsfiddle.net/4hcxjo1o/

![rz slider issue](https://user-images.githubusercontent.com/15357058/33197813-a00753a6-d10d-11e7-8fef-adbaa0154497.png)
### Expected behaviour
The width of the slider bar should not get changed on refresh

### Actual behaviour
The width of the slider bar gets changed to 1301 from 240 on refresh in my scenario

**Comment by ValentinH** [comment]
Closing for clean-up. Please comment to re-open if needed.
