### ISSUE TITLE
Modal issues

### ISSUE THREAD

**Issue by kusanghi** [angular-slider/angularjs-slider#601]
**Have a problem, I used to turn up for a slider widget:**

When pressing on button first, slider Widgets do not appear
Then close the pop up and open the back, slider widgets appear.

**This is my description video :** [https://drive.google.com/file/d/1gUMvG1eQoUnNRyZ74XlH3hHCY_IMAX5O/view?usp=sharing](https://drive.google.com/file/d/1gUMvG1eQoUnNRyZ74XlH3hHCY_IMAX5O/view?usp=sharing)

**Comment by ValentinH** [comment]
I'm 99% sure this is your issue: https://github.com/angular-slider/angularjs-slider#my-slider-is-not-rendered-correctly-on-load 🙂
