### ISSUE TITLE
Template for directive 'rzslider' must have exactly one root element. rzSliderTpl.html

### ISSUE THREAD

**Issue by lirad** [angular-slider/angularjs-slider#602]
I have added the minified JS and CSS versions to my project and I am trying to execute the demo example:

` <rzslider rz-slider-model="minSlider.value"></rzslider>`

However i get the following error:

> http://errors.angularjs.org/1.4.5/$compile/tplrt?p0=rzslider&p1=rzSliderTpl.html

> Error: $compile:tplrt
> Invalid Template Root
> Template for directive 'rzslider' must have exactly one root element. rzSliderTpl.html

I am not a very experienced webdeveloper and it might be something really simple, however I cannot find anything to help me correct it. Any help would be appreciated! Thank you and regards.

**Comment by ValentinH** [comment]
Hi @lirad, welcome!

Where did you take the minified version from? NPM? Directly from this project sources?

Here's a minimal working demo if it can helps: http://jsfiddle.net/cwhgLcjv/

**Comment by lirad** [comment]
Hello @ValentinH. I managed to make it to work adding the 'rzSliderTpl.html' file to the angular-slider folder and setting the 'templateUrl' to use an absolute path instead of relative one. 

Thank you so much for this project and for your support.

Best regards,

**Comment by ValentinH** [comment]
You should not have to do this. Just using the dist files should be fine.
