### ISSUE TITLE
Semicolon in CSS file

### ISSUE THREAD

**Issue by aNieto2k** [angular-slider/angularjs-slider#604]
https://github.com/angular-slider/angularjs-slider/blob/087a4ad3dc800ef904729e256cc8e79ef90e32a1/Gruntfile.js#L98

This option add a semicolon in css file, before the SourceMap. That produce a syntactic error in the CSS file.

**Comment by ValentinH** [comment]
Grrr. I was too fast. Sorry for this

**Comment by ValentinH** [comment]
6.4.3 fixes it ;)
