### ISSUE TITLE
valueLabel potion problem

### ISSUE THREAD

**Issue by Costellos** [angular-slider/angularjs-slider#607]
This could be something simple, but I'm haven't been able to find a fix.  When my slider is in the last position it looks like the value box cant go outside the bounds of the wrapper, and as such stops my box a bit short, even though the center of the circle is now to the right of the box above it.

![image](https://user-images.githubusercontent.com/8760268/33567299-b569180c-d8f0-11e7-9853-045e927ac170.png)

See fiddle: http://jsfiddle.net/o40x1uda/2/

Live example: http://costellocoding.com/test/angularSlider/demo/

Thanks,
Steve C

**Comment by ValentinH** [comment]
Closing for clean-up. Please comment to re-open if needed.
