### ISSUE TITLE
Loading of rzModule fails with Mailchimp

### ISSUE THREAD

**Issue by danjessen** [angular-slider/angularjs-slider#608]
I experience a issue on a website one of my customers have, where they added a mailchimp signup form (popup).

```html
<script type="text/javascript" src="//s3.amazonaws.com/downloads.mailchimp.com/js/signup-forms/popup/embed.js" data-dojo-config="usePlainJson: true, isDebug: false"></script><script type="text/javascript">require(["mojo/signup-forms/Loader"], function(L) { L.start({"baseUrl":"mc.us9.list-manage.com","uuid":"xxx","lid":"yyy"}) })</script>
```

It broke the angular and rzslider module because of the way their dojo handles AMD and require. I made a fix to the rzModule that fixes this for me. Because I can't tamper with the mailchimp script:

```javascript
if (typeof define === 'function' && define.amd && define.amd.angular) {
```

**Comment by ValentinH** [comment]
Closing for clean-up. Please comment to re-open if needed.
