### ISSUE TITLE
Can we have a simple example please

### ISSUE THREAD

**Issue by diplodata** [angular-slider/angularjs-slider#609]
I'm new to Angular and struggling to figure out how a simple slider works. Your example pages [here](http://angular-slider.github.io/angularjs-slider/) and [here](https://jsfiddle.net/ValentinH/954eve2L/) are hundreds of lines long, and make it impossible to see what the basic configuration should look like. Is it not possible to have a couple of minimal examples?

**Comment by GMaxera** [comment]
It's small enough? http://jsfiddle.net/z3dLacot/

**Comment by ValentinH** [comment]
Good point, I have updated the readme with those 2 examples:
- Simple example for single slider: http://jsfiddle.net/cwhgLcjv
- Simple example for double slider: http://jsfiddle.net/ye1kpfrj

**Comment by diplodata** [comment]
Very useful, thanks guys. Also found this - to show how to fire a change event http://jsfiddle.net/muwetwLc/
