### ISSUE TITLE
Change poistion legend

### ISSUE THREAD

**Issue by siliconprime-thangcao** [angular-slider/angularjs-slider#613]
When i change position legend of value, pointer can't touch or select to drag like image below, because z-index of legend greater than pointer, so when we hover mouse, i can't drag
![image](https://user-images.githubusercontent.com/21030723/35315171-7defed9e-00fd-11e8-9194-8d7eb9e5d0c6.png)

**Comment by ValentinH** [comment]
The trick is to use `pointer-events: none`:)
Demo: http://jsfiddle.net/ua31ckvh/
