### ISSUE TITLE
Adds labelOverlapSeparator option to customize default ' - '

### ISSUE THREAD

**Issue by ben-henoida** [angular-slider/angularjs-slider#615]
When the range labels overlap the separator string is ' - '.
The problem is that this character can be interpreted as 'minus'.

### Steps to reproduce
1. slider range with high value just above 0
http://jsfiddle.net/04sr3ty0/1/

### Expected behaviour
Should be able to tell if the high value is positive of negative

### Actual behaviour
Looks like the range is -2 to -1 when in fact it is -2 to +1

I am happy to create a pull request to fix this minor issue

**Comment by ValentinH** [comment]
Hi @ben-henoida ,

I've never thought about this, but this makes sense! ^^

What character should we use in your opinion?

**Comment by ben-henoida** [comment]
' .. ' is common enough to represent range :  -2 .. 1
How about a making it an option ?

**Comment by ValentinH** [comment]
Yes let's make it an option and keep the default to be `-` so we don't make a breaking change. 👍 If you can make a PR for this, it would be awesome! ;)

**Comment by ben-henoida** [comment]
PR created : https://github.com/angular-slider/angularjs-slider/pull/616

**Comment by ValentinH** [comment]
Released in https://github.com/angular-slider/angularjs-slider/releases/tag/6.5.0
