### ISSUE TITLE
Initial value takes a bit to be properly positioned

### ISSUE THREAD

**Issue by free-easy** [angular-slider/angularjs-slider#618]
### Steps to reproduce

Demo: http://angular-slider.github.io/angularjs-slider/
See `Toggle slider example`

### Expected behaviour
This "flicker" shouldn't happen.

### Actual behaviour
It happens

**Comment by ValentinH** [comment]
Unfortunately, this is due to how angular works. We can't measure the slider dimension before rendering it, thus we can't know where to position the knob up-front.
