### ISSUE TITLE
On npm 6.4.3 is the latest

### ISSUE THREAD

**Issue by andreeib** [angular-slider/angularjs-slider#619]
Hey Valentin, on npm the latest release is 6.4.3 so the last two don't show up (6.4.4, 6.5.0).

### Steps to reproduce
1. See https://registry.npmjs.org/angularjs-slider/6.4.4
2. and https://registry.npmjs.org/angularjs-slider/6.5.0

**Comment by ValentinH** [comment]
Indeed, these 2 versions can't be seen on the NPM website. However, the 2 versions are available in NPM if you try to install them using command-line.

I'll ask NPM support.

**Comment by ValentinH** [comment]
See https://github.com/npm/registry/issues/282

**Comment by andreeib** [comment]
If i run install with no version it installs 6.4.3:
```
> npm i angularjs-slider
...
+ angularjs-slider@6.4.3
added 1 package in 1.239s
```

Error when I try 6.4.4 or 6.5.0:
```
> npm i angularjs-slider@6.4.4
npm ERR! code ETARGET
npm ERR! notarget No matching version found for angularjs-slider@6.4.4
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
...
```

Maybe you have the versions in the local npm cache?

**Comment by andreeib** [comment]
Also missing from the CDN:
https://cdnjs.com/libraries/angularjs-slider

**Comment by ValentinH** [comment]
Fixed.

I published them on my work computer where the default registry is our internal one ^^
