### ISSUE TITLE
Out of the box error telling me "unexpected token . " in rzslider.min.css  

### ISSUE THREAD

**Issue by ramyfarid922** [angular-slider/angularjs-slider#621]
### Steps to reproduce
1. Installed rzSlider through Bower
2. Added the import in index.html
3. Importing the rzSlider.min.css causes it

### Expected behaviour
Slider should appear in my HTML with no errors

### Actual behaviour
Slider is not appearing and its CSS file is not loading correctly because of a syntax error

**Comment by ValentinH** [comment]
The demo works fine: http://angular-slider.github.io/angularjs-slider/

What version are you using? Could you provide an failing example?

**Comment by ValentinH** [comment]
Closing for clean-up. Please comment to re-open if needed.
