### ISSUE TITLE
With stepsArray and ticksArray the Value not showing on position

### ISSUE THREAD

**Issue by olafchromik** [angular-slider/angularjs-slider#624]
### Steps to reproduce
1. Setting value: 10
2. Setting ticksArray: [0, 9, 24, 49, 99, 115, 135, 153]
3. Setting custom stepsArray until 10.000

Demo: http://jsfiddle.net/th8jbm20/4/

### Expected behaviour
- Value on 10

### Actual behaviour
- Value on 1

**Comment by ValentinH** [comment]
Sorry for the super late answer, I'm doing some cleanup on this project.

You were actually missing the `showTicksValues` option set to true.

See http://jsfiddle.net/ValentinH/v37gacqL/
