### ISSUE TITLE
Data formats are not included

### ISSUE THREAD

**Issue by Miqueliu** [angular-slider/angularjs-slider#625]
Data formats are not considered, for another languages (not English), as it happens to numbers or currencies.

[Here](http://jsfiddle.net/e8tssnk2/1/) is an example in Spanish.

**Comment by Miqueliu** [comment]
@ValentinH, maybe didn't you understand this trouble?

**Comment by ValentinH** [comment]
Sorry, I missed this issue. However, I don't really understand what's the issue. Also your demo isn't working as it's missing the step and precision to work with floating numbers.

**Comment by Miqueliu** [comment]
The problem is that each culture has an own system of data writing. Your implementation (and many others) is USA-centrist. To avoid this, AngularJS solutions it with [`$locale` service](https://docs.angularjs.org/guide/i18n).

My example is only to demostrate differences between native filters (right way) and your slider (wrong). Don't care floatings!

**Comment by ValentinH** [comment]
I don't really like the way you request help... But I'm in a nice mood today so I'll help you anyway:
The default is USA-centrist but we provide a `translate` function that enables the developer to choose how values are displayed on the slider.

Here's a demo: http://jsfiddle.net/xctrqyjb/
