### ISSUE TITLE
1.how to change pointer button icon? 

### ISSUE THREAD

**Issue by laijuncheng** [angular-slider/angularjs-slider#630]
1.how to change pointer button icon?

**Comment by ValentinH** [comment]
Could you please elaborate what you want to do, what did you try already?

**Comment by laijuncheng** [comment]
ok , i see 
`.custom-slider.rzslider .rz-pointer {
  width: 8px;
  height: 16px;
  top: auto;
  bottom: 0;
  background-color: #333;
  border-top-left-radius: 3px;
  border-top-right-radius: 3px;
}`

you can insert `background: url()`

**Comment by laijuncheng** [comment]
@ValentinH emmm,  my english is not good , and git can't  upload image, so i don't  know how to describe my question, but good luck,  i found the solution
