### ISSUE TITLE
Drag only when mouse is at pointer

### ISSUE THREAD

**Issue by wewake4** [angular-slider/angularjs-slider#631]
Hi, Great work with slider !!!

I have a custom requirement that pointer can move only when the cursor is at the pointer and user drags it. While dragging if mouse moves away from the pointer then pointer should stop. Is there any way by which we can do it?

**Comment by ValentinH** [comment]
Hi,

There is no option to implement what you want to achieve. I think the easiest for you would be to fork this project. ;)
