### ISSUE TITLE
Slider position offset after exit fullscreen

### ISSUE THREAD

**Issue by vs-kiann** [angular-slider/angularjs-slider#633]
Hi there, 

I am not sure what would be causing this issue. i am implementing a trim feature, so when the user in the fullscreen, angular-slider will appear and user can drag to the position they want. however, when the user exit fullscreen, the slider still retains the position when its in fullscreen even the user has exit the fullscreen. 

[Image](https://imgur.com/a/okUBHIZ)

**Comment by ValentinH** [comment]
You need to broadcast the `reCalcViewDimensions` event on the scope. See https://github.com/angular-slider/angularjs-slider#slider-events

**Comment by ValentinH** [comment]
Could you please provide a JSFiddle showing the issue? You can fork this one as a start point: http://jsfiddle.net/cwhgLcjv .
