### ISSUE TITLE
Rotated Slider

### ISSUE THREAD

**Issue by wewake4** [angular-slider/angularjs-slider#637]
### Steps to reproduce
1. Install slider
2. Include slider
3. Move slider

### Expected behaviour
Move along with the mouse

### Actual behaviour
The slider shows a strange behavior: when I start to move the slider , It moves in opposite direction.

` <rzslider rz-slider-model="vm.priceSlider.value" rz-slider-options="vm.priceSlider.options" style="transform: rotate(3.2108rad);"></rzslider>`

**Comment by ValentinH** [comment]
We don't support rotation on the sliders. However, we do support vertical slider by setting the  vertical option to true.

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉
