### ISSUE TITLE
Development setup instructions

### ISSUE THREAD

**Issue by trodi** [angular-slider/angularjs-slider#640]
I know there isn't active new development on this project. However, we could improve the ease to contribute to this project. There should be a section in the readme or contributing file that explains how to get a dev environment up and running.

Specifically, `grunt-cli` is required to build this project. Every time I make a change here I have to remember that I have to `npm i -g grunt-cli` because I always delete it afterwards, otherwise all the npm scripts will not work.

At the very least we should have documentation that states how to instal the grunt cli and all other setup steps. Ideally, this documentation section only has to say run `npm i` and all dependencies should be installed and you're ready to go.

**Comment by ValentinH** [comment]
We have the CONTRIBUTING.md file that should explain all the steps needed to contribute.
I just added the `grunt-cli` to the devDependencies so you don't have to install it globally. 
Just released 6.6.1 for your TS definitions 😉
