### ISSUE TITLE
Breaking on upgrading to 6.6.1 from 6.5.1

### ISSUE THREAD

**Issue by stripathix** [angular-slider/angularjs-slider#642]
Getting error on upgrading from 6.5.1 to 6.6.1. Are there any breaking changes released in 6.6.1?

angular.js:14961 TypeError: Cannot read property 'on' of null
    at Slider.bindEvents (rzslider.js:1881)
    at Slider.manageEventsBindings (rzslider.js:795)
    at Slider.init (rzslider.js:380)
    at new Slider (rzslider.js:348)
    at Object.link (rzslider.js:2670)
    at angular.js:1393
    at angular.js:10676
    at wa (angular.js:10682)
    at p (angular.js:10071)
    at angular.js:10410 "<div class="rzslider" ng-if="gridViewCtrl.slider" rz-slider-tpl-url="common/template/bn-rzSliderTpl.html" rz-slider-model="gridViewCtrl.settings.departureTime" rz-slider-options="gridViewCtrl.slider.options">"

<img width="625" alt="screen shot 2018-07-02 at 11 54 34 pm" src="https://user-images.githubusercontent.com/8480351/42180088-825ef00e-7e53-11e8-8e26-dfcdf7cd7641.png">

**Comment by ValentinH** [comment]
Sorry for this error. Could you try to share an example showing the error please?

**Comment by ValentinH** [comment]
Actually, I just noticed that this version should be a breaking change if you use a custom template. Is it your case?

**Comment by ValentinH** [comment]
Just updated the release note: https://github.com/angular-slider/angularjs-slider/releases/tag/6.6.0

Sorry again.

**Comment by stripathix** [comment]
Yes, I am using a custom template. Thanks for the update. It works after adding below html node in my template:

`  <span class="rz-pointer rz-pointer-min" ng-style=minPointerStyle>
    <span class="rz-ruleset-pointer" background-color="minPointerStyle.backgroundColor" slider-rule ng-style="{'color': '#fff'}" >
     </span>
  </span>`
