### ISSUE TITLE
rzSliderTpl.html not found

### ISSUE THREAD

**Issue by binggiry** [angular-slider/angularjs-slider#643]
I want to render a slidebar that can NOT be edited.
my code is like the following.
I have error like

GET http://localhost:8081/rzSliderTpl.html?v=1530646338472 404 (Not Found)    angular.min.js:103
Error: [$compile:tpload] http://errors.angularjs.org/1.5.5/$compile/tpload?p0=rzSliderTpl.html&p1=404&p2=Not%20Found     angular.min.js:117

my angularjs-slide version is 1.1.0

How can I fix this error?

$scope.slider = {
    value: 24,
    options: {
      readyOnly: true,
      disabled: true,
      floor: 1,
      ceil: 24,
    }
  }

          <rzslider name="mySlider"
                    rz-slider-model="slider.value"
                    rz-slider-options="slider.options"
          ></rzslider>

Demo: http://jsfiddle.net/cwhgLcjv/ (fork this example and update the link)

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by ValentinH** [comment]
If you are really using the version 1.1.0, you should really upgrade to the latest one (6.6.1). There were so many changes since that version.

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉
