### ISSUE TITLE
Clicking slider handles or selection bar scrolls to window top

### ISSUE THREAD

**Issue by dexbytesmanish** [angular-slider/angularjs-slider#646]
I am facing issue that when I click on slider handles or selection bar it scrolls to window top. can you pleas suggest way to avoid this situation ?

**Comment by ValentinH** [comment]
Could you please provide a demo? I have never such an issue with this library.

**Comment by dexbytesmanish** [comment]
Hello Valentin,

 

Please go to : https://www.the-online-gallery.com/artworks

1.       Scroll down to bottom

2.       Click on Price dropdown to open slider

3.       Click on any handle of the price slider

 

By just clicking handle it scrolls to window top.

 

Thanks,

Manish

**Comment by ValentinH** [comment]
This is not an issue with this library. The problem comes from the fact you navigate to `page/1/sort-by/default%20sorting/price/1-28200` when the slider is clicked and thus, the page scrolls to top.

If you don't want this, you should only navigate when the price value has really changed.

**Comment by ValentinH** [comment]
`onEnd` is called when the user finished on interaction with the slider. In this callback, you can write any custom logic to prevent unwanted actions.

**Comment by dexbytesmanish** [comment]
Ok, so how should I avoid this situation that if price value has not really changed not change the URL ?

**Comment by ValentinH** [comment]
You can compare the new values with the previous ones, if they haven't changed, don't do anything.

**Comment by dexbytesmanish** [comment]
How do I get new values and previous values ?

**Comment by ValentinH** [comment]
You need to store the previous values somehow. Anyway, if you want the price slider to reflect what's in the url, you need to know what's the current selection is. Thus, compare to this.

This is custom logic so I can't help more.

**Comment by dexbytesmanish** [comment]
I have debugged in Web Inspector by setting breakpoint just before URL navigation and it is being observed that it is scrolling to window top before navigation.
