### ISSUE TITLE
issue with alpha channel in from-to of selectionBarGradient

### ISSUE THREAD

**Issue by nebulaszlonemethi** [angular-slider/angularjs-slider#648]
### Steps to reproduce
Configure a slider like eg.:
`...
selectionBarGradient: {
    from: "rgba(255, 0, 0, 0.15)",
    to: "#ff0000"
}
...
`
### Expected behaviour
The bg color of the selection bar should start at rgba(255, 0, 0, 0.15)

### Actual behaviour
The bg color of the selection bar starts somewhere else because of the default bg color of the bar.

#### Quick workaround with css, works only on white background:
`.rzslider .rz-selection[style*="background-image"] {
    background: #fff;
}
`

**Comment by ValentinH** [comment]
Indeed, since the selection bar is rendered on top of the main one, this is expected.

Your workaround is nice though!
