### ISSUE TITLE
slider does not handle correctly if "vertical" option changes runtime

### ISSUE THREAD

**Issue by nebulaszlonemethi** [angular-slider/angularjs-slider#649]
### Steps to reproduce
1. Setup a horz. slider
2. Toggle the "vertical" option on-off, even together with broadcasting the "rzSliderForceRender" event

Demo: http://jsfiddle.net/nlac73/qnku3d8y/

### Expected behaviour
The slider should be toggling between horizontal-vertical state

### Actual behaviour
The slider does not switch back to horizontal state while toggling the option, it remains vertical.

**Comment by ValentinH** [comment]
Fix will be released in 7.0.0
