### ISSUE TITLE
Slider element id or data attribute

### ISSUE THREAD

**Issue by jpaulo1987** [angular-slider/angularjs-slider#650]
**Question**: is there a way to dynamically find out the id or data-attribute of a slider that triggered an 'onChange' event (inside the onChange function)?
I can not use the "sliderId' option because i have multiple sliders on the same page that share the same options object (since the options for all of them are the same, except for the id).

**Comment by ValentinH** [comment]
The only way is to use the `sliderId`. You can definitely share the options between the sliders and just set the id for each of them by creating a new object like:
```{...options, id: '123'}``` or with  `Object.assign()`.

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉
