### ISSUE TITLE
slider pointers do not resize (reposition) after parent div resize

### ISSUE THREAD

**Issue by rawbeans** [angular-slider/angularjs-slider#651]
When the parent div of a slider is resized, some of the slider elements resize with it, but the rz-pointer elements do not.

Correctly resizes:
- rz-slider (outer container)
- full length rz-bar-wrapper rz-bar

Does not resize:
- rz-left-out-selection
- rz-right-out-selection
- rz-pointer

However after interacting with the pointers (clicking on the slider, or dragging the pointers) they update to correct positions

Demo: http://jsfiddle.net/mbkjvdfx/

Resize works fine on window resize, but not parent div resize.

**Comment by ValentinH** [comment]
This is because this library only listen on window resize event. For other events, you have to tell the library when the refresh. Use https://github.com/angular-slider/angularjs-slider#slider-events .

**Comment by yweing0720** [comment]
why are they not passing out a function to call like [this plonker](http://embed.plnkr.co/C2G3Cg/)

**Comment by ValentinH** [comment]
Indeed this could be possible. What problem does it solves that is not solved by the `rzSliderForceRender` event though?

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉
