### ISSUE TITLE
Cannot able to select exact amount during slider in iPhone7/10 .

### ISSUE THREAD

**Issue by kishoreaoe** [angular-slider/angularjs-slider#652]
Scenario:
1. Place angularjs-slider with minimum 0 to maximum as 2,000,000 (2 million)
2. Try to select 1million using slider
3. My step value is: 5000 .
Observations:
During this slider, am able to select 995,000 and also 1,005,000 but exact one million am not able to select. 

Could someone help on this bug. Is there any temporary fix for this.!?

Thanks and Regards,
Kishore Kumar. K

**Comment by ValentinH** [comment]
Sorry for not answering earlier. If you are still facing this issue, please comment and provide a demo to reopen.
