### ISSUE TITLE
Translate function doesn't work inline.

### ISSUE THREAD

**Issue by graphical-iain** [angular-slider/angularjs-slider#654]
It appears the the translate function doesn't work inline.

Demo: http://jsfiddle.net/3qj592ra/5/

### Expected behaviour
All options should behave the same used inline and as an external object.

### Actual behaviour
The translate function causes an error when it is included inline.

**Comment by ValentinH** [comment]
Is this supported by AngularJs?

**Comment by graphical-iain** [comment]
I'm not that versed with AngularJs, so I'm not sure. But you asking that made me think of a workaround. I can put the function in the controller and reference it in the inline object. I only need the value and options inline, so that works.

**Comment by ValentinH** [comment]
Indeed this is much better also on a performance point of view probably :)
