### ISSUE TITLE
A Square border box is displaying while dragging the slider in mobile

### ISSUE THREAD

**Issue by kishoreaoe** [angular-slider/angularjs-slider#656]
**Scenario:**
1. Include the slider in a page.
2. Configure the Slider Options.
3. Try to drag the slider and we could able to see SQUARE border box appearing.

**Comment by ValentinH** [comment]
Do you mean this border:
![image](https://user-images.githubusercontent.com/2678610/46791183-d92ce800-cd40-11e8-8458-f35d03927b50.png)
?

**Comment by ValentinH** [comment]
Yeap, just add:
```css
.rz-pointer:focus {
  outline: none;
}
```

**Comment by kishoreaoe** [comment]
thanks alot. That's solved the problem 👍
