### ISSUE TITLE
Slider stop working after last update

### ISSUE THREAD

**Issue by ysoftsolutions** [angular-slider/angularjs-slider#663]
Hello, I am using angular-slider from last 6 months and it is working fine in my mobile application. It suddenly stop working after "refactor(module): Rename module name from rzModule to rzSlider" this update. My mobile app stop working. Can you please suggest us without updating my mobile application how I can use old version of it.

**Comment by ValentinH** [comment]
Yes this was released as a major version so it contains breaking changes. You should stick to 6.6.1 version if you cannot update your app.
