### ISSUE TITLE
Slider looses responsiveness on zooming and reloading page

### ISSUE THREAD

**Issue by rmishra7** [angular-slider/angularjs-slider#669]
### Steps to reproduce
1. Drag the slider
2. Zoom the page to 150%
3. Reload the page
3. The slider looses its responsiveness and range becomes distorted

Demo: http://jsfiddle.net/cwhgLcjv/ (fork this example and update the link)

### Expected behaviour
It should be responsive despite zooming and on reloading range should not get distorted

### Actual behaviour
The slider looses its responsiveness and range becomes distorted
![img1](https://user-images.githubusercontent.com/20298170/57449076-a3b99000-7278-11e9-8a88-628ee552e0c5.JPG)
![img2](https://user-images.githubusercontent.com/20298170/57449077-a3b99000-7278-11e9-8ed0-6380b294a5a4.JPG)
![img3](https://user-images.githubusercontent.com/20298170/57449078-a3b99000-7278-11e9-9518-c52b4b37ae2e.JPG)
![img4](https://user-images.githubusercontent.com/20298170/57449079-a4522680-7278-11e9-8278-e6945a33c58e.JPG)
![img5](https://user-images.githubusercontent.com/20298170/57449080-a4522680-7278-11e9-9f7b-26c06eafc6d1.JPG)

**Comment by ValentinH** [comment]
How are you zooming? I've tried on the demo website and everything is fine.

**Comment by rmishra7** [comment]
It's working fine now, Thanks!
