### ISSUE TITLE
Docs broken link to "Open Source Stamina"

### ISSUE THREAD

**Issue by AlmogCohen** [angular-slider/angularjs-slider#670]
The paragraph in the docs links to a broken link `Open Source Stamina` to the medium post which actually seemed to be interesting :)
https://cl.ly/77e2c3

Maybe it is possible to link directly to https://kentcdodds.com/blog/open-source-stamina

**Comment by ValentinH** [comment]
Hey, indeed Kent has left Medium and moved to his own blog. Would you like to do a PR to fix the link?

**Comment by AlmogCohen** [comment]
Enjoy! Feel free to close this when you merge it

**Comment by ValentinH** [comment]
Done, thanks for the quick action :)
