### ISSUE TITLE
Last tick not display as expected on first load

### ISSUE THREAD

**Issue by tux240** [angular-slider/angularjs-slider#673]
Hello,

On first load, the last tick is not showed on the main bar as expected.
Here is a screenshot :
![Screenshot 2019-07-01 at 20 15 51](https://user-images.githubusercontent.com/5692554/60457832-4d941800-9c3d-11e9-8676-b3c87709130d.png)

Do you have some ideas ?

**Comment by trodi** [comment]
Likely the slider needs to recalculate it's dimensions, see [docs](https://github.com/angular-slider/angularjs-slider#slider-events). Here's a link to [common issues](https://github.com/angular-slider/angularjs-slider#common-issues).

Remember to use the [issue template](https://github.com/angular-slider/angularjs-slider/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) that github prompts you with to ensure you provide all needed information (e.g., JSFiddle of the issue).

**Comment by tux240** [comment]
It works by following the common issue. Thanks
