### ISSUE TITLE
Range slider: Identify min and max on change event

### ISSUE THREAD

**Issue by wholeinsoul** [angular-slider/angularjs-slider#674]
How can I identify which slider (min or max) changed inside the onChange event ? 

Thanks.

**Comment by ValentinH** [comment]
From the doc:
![Screenshot_20191214-204215](https://user-images.githubusercontent.com/2678610/70853927-07fa9d00-1eb5-11ea-8c3d-578e27ccc3e5.jpg)

**Comment by wholeinsoul** [comment]
Thanks for such a quick response. And I'm sorry for not looking into docs. I kept looking into examples :-(

**Comment by ValentinH** [comment]
No problem :)
