### ISSUE TITLE
brocken compiling with less v4

### ISSUE THREAD

**Issue by WuglyakBolgoink** [angular-slider/angularjs-slider#678]
to support LESS v4 you must wrap math operations with `(...)`

example 
```
    margin-top: (-@handleSize / 2);
    padding-top: @handleSize / 2;
```

give back 
```
    margin-top: -16px;
    padding-top: 32px/2;
```

and in this case `padding-top` will be ignored in browser and `margin-top` is correct!

please fix this asap!

**Comment by ValentinH** [comment]
Thanks for reporting this. Would you like to create a PR?

**Comment by WuglyakBolgoink** [comment]
@ValentinH are you published to npm now?

**Comment by ValentinH** [comment]
It should be the case already or maybe I published to the wrong registry 🙈

**Comment by WuglyakBolgoink** [comment]
@ValentinH 
> It should be the case already or maybe I published to the wrong registry 🙈

till now, nothing )

**Comment by ValentinH** [comment]
It should be good now: v7.0.1

**Comment by WuglyakBolgoink** [comment]
@ValentinH yes! thanks!
